// AUTO-GENERATED by slack-compiler/gen_worker_mapping.py from mapping.json.
// Do not hand-edit — re-run the generator after any classify.py change.
// Runtime lookup for render_reading_to_slack: which atoms this Worker can
// compile to a real Slack block, and which target/bucket each needs — the
// same classification compile_atoms.py's Python harness uses, made available
// to the Worker itself so an agentic caller isn't limited to what a human ran
// a Python script for.
export const SLACK_MAPPING = {
  "accordion_item": {
    "bucket": "A",
    "target": "container"
  },
  "alert_banner": {
    "bucket": "A",
    "target": "section"
  },
  "callout": {
    "bucket": "A",
    "target": "section"
  },
  "collapsible_panel": {
    "bucket": "A",
    "target": "container"
  },
  "cta_button": {
    "bucket": "A",
    "target": "actions"
  },
  "data_table_sortable": {
    "bucket": "A",
    "target": "table"
  },
  "divider": {
    "bucket": "A",
    "target": "divider"
  },
  "heading": {
    "bucket": "A",
    "target": "header"
  },
  "image": {
    "bucket": "A",
    "target": "image"
  },
  "image_with_caption": {
    "bucket": "A",
    "target": "image"
  },
  "inline_alert": {
    "bucket": "A",
    "target": "section"
  },
  "key_value": {
    "bucket": "A",
    "target": "table"
  },
  "link_button": {
    "bucket": "A",
    "target": "actions"
  },
  "metric_row": {
    "bucket": "A",
    "target": "table"
  },
  "module_map": {
    "bucket": "A",
    "target": "table"
  },
  "nav_link": {
    "bucket": "A",
    "target": "actions"
  },
  "numbered_list": {
    "bucket": "A",
    "target": "table"
  },
  "page_header": {
    "bucket": "A",
    "target": "header"
  },
  "section_break": {
    "bucket": "A",
    "target": "divider"
  },
  "spacer": {
    "bucket": "A",
    "target": "divider"
  },
  "stat_card": {
    "bucket": "A",
    "target": "card"
  },
  "step_progress": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "stepper": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "steps": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "summary_box": {
    "bucket": "A",
    "target": "card"
  },
  "table": {
    "bucket": "A",
    "target": "table"
  },
  "text_callout": {
    "bucket": "A",
    "target": "section"
  },
  "benchmark_comparison": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "chartjs_bar": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "chartjs_line": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "chartjs_pie": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "confidence_bar": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "donut_stat": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "mini_sparkline_set": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "skill_bars": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "sparkline": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "stacked_area": {
    "bucket": "A",
    "target": "data_visualization"
  },
  "match_schedule": {
    "bucket": "A",
    "target": "table"
  },
  "standings_table": {
    "bucket": "A",
    "target": "table"
  },
  "action_required_card": {
    "bucket": "A",
    "target": "section"
  },
  "carousel": {
    "bucket": "A",
    "target": "carousel"
  },
  "caution_block": {
    "bucket": "A",
    "target": "section"
  },
  "color_swatch_grid": {
    "bucket": "A",
    "target": "table"
  },
  "counter_group": {
    "bucket": "A",
    "target": "table"
  },
  "dark_divider": {
    "bucket": "A",
    "target": "divider"
  },
  "data_grid": {
    "bucket": "A",
    "target": "table"
  },
  "expandable_list": {
    "bucket": "A",
    "target": "container"
  },
  "faq_accordion": {
    "bucket": "A",
    "target": "container"
  },
  "gallery": {
    "bucket": "A",
    "target": "carousel"
  },
  "glass_card": {
    "bucket": "A",
    "target": "card"
  },
  "icon_checklist": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "icon_stat_row": {
    "bucket": "A",
    "target": "table"
  },
  "image_pair": {
    "bucket": "A",
    "target": "carousel"
  },
  "metric_comparison_card": {
    "bucket": "A",
    "target": "card"
  },
  "metric_delta": {
    "bucket": "A",
    "target": "card"
  },
  "next_step_strip": {
    "bucket": "A",
    "target": "table"
  },
  "person_card": {
    "bucket": "A",
    "target": "card"
  },
  "pipeline": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "pull_stat": {
    "bucket": "A",
    "target": "card"
  },
  "resources_list": {
    "bucket": "A",
    "target": "table"
  },
  "section_label": {
    "bucket": "A",
    "target": "header"
  },
  "side_by_side_spec": {
    "bucket": "A",
    "target": "table"
  },
  "split_stat": {
    "bucket": "A",
    "target": "card"
  },
  "status_timeline": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "take_away_card": {
    "bucket": "A",
    "target": "card"
  },
  "task_list": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "two_tone_card": {
    "bucket": "A",
    "target": "container"
  },
  "video_card": {
    "bucket": "A",
    "target": "card"
  },
  "video_pair": {
    "bucket": "A",
    "target": "carousel"
  },
  "video_thumbnail": {
    "bucket": "A",
    "target": "image"
  },
  "zoomable_image": {
    "bucket": "A",
    "target": "image"
  },
  "author_bio_card": {
    "bucket": "A",
    "target": "card"
  },
  "headline_list": {
    "bucket": "A",
    "target": "table"
  },
  "news_digest": {
    "bucket": "A",
    "target": "table"
  },
  "related_posts_grid": {
    "bucket": "A",
    "target": "table"
  },
  "search_result_card": {
    "bucket": "A",
    "target": "card"
  },
  "series_overview_card": {
    "bucket": "A",
    "target": "table"
  },
  "source_citation": {
    "bucket": "A",
    "target": "table"
  },
  "table_of_contents": {
    "bucket": "A",
    "target": "table"
  },
  "tooltip_glossary": {
    "bucket": "A",
    "target": "table"
  },
  "brevet_automatismes": {
    "bucket": "A",
    "target": "table"
  },
  "brevet_timeline": {
    "bucket": "A",
    "target": "table"
  },
  "capability_checklist": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "certification_card": {
    "bucket": "A",
    "target": "card"
  },
  "checklist_interactive": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "cohort_progress_board": {
    "bucket": "A",
    "target": "table"
  },
  "course_progress_card": {
    "bucket": "A",
    "target": "table"
  },
  "flashcard_deck": {
    "bucket": "A",
    "target": "table"
  },
  "learning_objectives": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "match_exercise": {
    "bucket": "A",
    "target": "table"
  },
  "onboarding_stepper": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "prerequisite_checklist": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "rubric_card": {
    "bucket": "A",
    "target": "table"
  },
  "article_hero": {
    "bucket": "A",
    "target": "card"
  },
  "case_study_card": {
    "bucket": "A",
    "target": "card"
  },
  "comparison_grid": {
    "bucket": "A",
    "target": "table"
  },
  "cta_section": {
    "bucket": "A",
    "target": "actions"
  },
  "dark_hero": {
    "bucket": "A",
    "target": "card"
  },
  "expert_endorsement": {
    "bucket": "A",
    "target": "card"
  },
  "feature_matrix": {
    "bucket": "A",
    "target": "table"
  },
  "follow_button": {
    "bucket": "A",
    "target": "actions"
  },
  "follow_cta": {
    "bucket": "A",
    "target": "actions"
  },
  "follow_up_chips": {
    "bucket": "A",
    "target": "actions"
  },
  "github_repo_card": {
    "bucket": "A",
    "target": "card"
  },
  "gradient_hero": {
    "bucket": "A",
    "target": "card"
  },
  "linkedin_post_image": {
    "bucket": "A",
    "target": "image"
  },
  "media_mention_card": {
    "bucket": "A",
    "target": "card"
  },
  "newsletter_cta": {
    "bucket": "A",
    "target": "actions"
  },
  "pricing_tier_card": {
    "bucket": "A",
    "target": "card"
  },
  "pricing_tier_group": {
    "bucket": "A",
    "target": "table"
  },
  "rating_summary_bar": {
    "bucket": "A",
    "target": "table"
  },
  "review_callout": {
    "bucket": "A",
    "target": "card"
  },
  "testimonial_card": {
    "bucket": "A",
    "target": "card"
  },
  "catalogue_provenance": {
    "bucket": "A",
    "target": "table"
  },
  "domain_brief": {
    "bucket": "A",
    "target": "card"
  },
  "llm_comparison_table": {
    "bucket": "A",
    "target": "table"
  },
  "model_card": {
    "bucket": "A",
    "target": "card"
  },
  "multi_surface": {
    "bucket": "A",
    "target": "table"
  },
  "renderer_stats": {
    "bucket": "A",
    "target": "table"
  },
  "token_budget_meter": {
    "bucket": "A",
    "target": "card"
  },
  "api_param_table": {
    "bucket": "A",
    "target": "table"
  },
  "breaking_banner": {
    "bucket": "A",
    "target": "section"
  },
  "changelog_entry": {
    "bucket": "A",
    "target": "table"
  },
  "deprecation_notice": {
    "bucket": "A",
    "target": "section"
  },
  "entity_list": {
    "bucket": "A",
    "target": "table"
  },
  "env_var_list": {
    "bucket": "A",
    "target": "table"
  },
  "experimental_banner": {
    "bucket": "A",
    "target": "section"
  },
  "inventory_table": {
    "bucket": "A",
    "target": "table"
  },
  "jira_ticket": {
    "bucket": "A",
    "target": "card"
  },
  "leaderboard_card": {
    "bucket": "A",
    "target": "table"
  },
  "live_aggregator": {
    "bucket": "A",
    "target": "table"
  },
  "notification_stack": {
    "bucket": "A",
    "target": "table"
  },
  "order_status_card": {
    "bucket": "A",
    "target": "card"
  },
  "poll_block": {
    "bucket": "A",
    "target": "table"
  },
  "product_spec_table": {
    "bucket": "A",
    "target": "table"
  },
  "product_thumbnail": {
    "bucket": "A",
    "target": "image"
  },
  "shortcut_legend": {
    "bucket": "A",
    "target": "table"
  },
  "sprint_board": {
    "bucket": "A",
    "target": "plan/task_card"
  },
  "status_dashboard": {
    "bucket": "A",
    "target": "table"
  },
  "vote_button_group": {
    "bucket": "A",
    "target": "actions"
  },
  "back_button": {
    "bucket": "B",
    "target": "markdown"
  },
  "badge": {
    "bucket": "B",
    "target": "markdown"
  },
  "badge_group": {
    "bucket": "B",
    "target": "markdown"
  },
  "blockquote": {
    "bucket": "B",
    "target": "markdown"
  },
  "body": {
    "bucket": "B",
    "target": "markdown"
  },
  "bullet_list": {
    "bucket": "B",
    "target": "markdown"
  },
  "chip_group": {
    "bucket": "B",
    "target": "markdown"
  },
  "code": {
    "bucket": "B",
    "target": "markdown"
  },
  "code_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "code_diff": {
    "bucket": "B",
    "target": "markdown"
  },
  "diagram": {
    "bucket": "B",
    "target": "markdown"
  },
  "empty_state": {
    "bucket": "B",
    "target": "markdown"
  },
  "file_tree": {
    "bucket": "B",
    "target": "markdown"
  },
  "google_icon": {
    "bucket": "B",
    "target": "markdown"
  },
  "highlight_box": {
    "bucket": "B",
    "target": "markdown"
  },
  "hub": {
    "bucket": "B",
    "target": "markdown"
  },
  "icon_list": {
    "bucket": "B",
    "target": "markdown"
  },
  "info_card": {
    "bucket": "B",
    "target": "markdown"
  },
  "inline_code": {
    "bucket": "B",
    "target": "markdown"
  },
  "json_tree_viewer": {
    "bucket": "B",
    "target": "markdown"
  },
  "key_takeaways": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_grid": {
    "bucket": "B",
    "target": "markdown"
  },
  "markdown_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "paragraph": {
    "bucket": "B",
    "target": "markdown"
  },
  "progress_bar": {
    "bucket": "B",
    "target": "markdown"
  },
  "progress_ring": {
    "bucket": "B",
    "target": "markdown"
  },
  "quiet_link": {
    "bucket": "B",
    "target": "markdown"
  },
  "quote": {
    "bucket": "B",
    "target": "markdown"
  },
  "script_run_button": {
    "bucket": "B",
    "target": "markdown"
  },
  "status_pill": {
    "bucket": "B",
    "target": "markdown"
  },
  "subheading": {
    "bucket": "B",
    "target": "markdown"
  },
  "tabbed_code": {
    "bucket": "B",
    "target": "markdown"
  },
  "tag_chip": {
    "bucket": "B",
    "target": "markdown"
  },
  "text_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "timeline": {
    "bucket": "B",
    "target": "markdown"
  },
  "tool_tile": {
    "bucket": "B",
    "target": "markdown"
  },
  "tree_view": {
    "bucket": "B",
    "target": "markdown"
  },
  "annotated_code": {
    "bucket": "B",
    "target": "markdown"
  },
  "annotation_highlight": {
    "bucket": "B",
    "target": "markdown"
  },
  "audio_link": {
    "bucket": "B",
    "target": "markdown"
  },
  "audio_player": {
    "bucket": "B",
    "target": "markdown"
  },
  "avatar_group": {
    "bucket": "B",
    "target": "markdown"
  },
  "before_after": {
    "bucket": "B",
    "target": "markdown"
  },
  "before_after_stack": {
    "bucket": "B",
    "target": "markdown"
  },
  "code_snippet_pair": {
    "bucket": "B",
    "target": "markdown"
  },
  "copy_code_button": {
    "bucket": "B",
    "target": "markdown"
  },
  "decision_tree": {
    "bucket": "B",
    "target": "markdown"
  },
  "document_link": {
    "bucket": "B",
    "target": "markdown"
  },
  "expandable_text": {
    "bucket": "B",
    "target": "markdown"
  },
  "feedback_prompt": {
    "bucket": "B",
    "target": "markdown"
  },
  "highlighted_text": {
    "bucket": "B",
    "target": "markdown"
  },
  "icon_badge": {
    "bucket": "B",
    "target": "markdown"
  },
  "icon_row": {
    "bucket": "B",
    "target": "markdown"
  },
  "inline_feedback_message": {
    "bucket": "B",
    "target": "markdown"
  },
  "lozenge": {
    "bucket": "B",
    "target": "markdown"
  },
  "math_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "pdf_preview": {
    "bucket": "B",
    "target": "markdown"
  },
  "progress_circle": {
    "bucket": "B",
    "target": "markdown"
  },
  "reaction_group": {
    "bucket": "B",
    "target": "markdown"
  },
  "repo_links": {
    "bucket": "B",
    "target": "markdown"
  },
  "sidebar_note": {
    "bucket": "B",
    "target": "markdown"
  },
  "tag_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "tag_cloud": {
    "bucket": "B",
    "target": "markdown"
  },
  "text_analysis": {
    "bucket": "B",
    "target": "markdown"
  },
  "text_highlight": {
    "bucket": "B",
    "target": "markdown"
  },
  "version_badge": {
    "bucket": "B",
    "target": "markdown"
  },
  "abbr_tooltip": {
    "bucket": "B",
    "target": "markdown"
  },
  "anchor_list": {
    "bucket": "B",
    "target": "markdown"
  },
  "article_series_nav": {
    "bucket": "B",
    "target": "markdown"
  },
  "closing": {
    "bucket": "B",
    "target": "markdown"
  },
  "concept_ladder": {
    "bucket": "B",
    "target": "markdown"
  },
  "concept_rung": {
    "bucket": "B",
    "target": "markdown"
  },
  "display_quote": {
    "bucket": "B",
    "target": "markdown"
  },
  "footnote": {
    "bucket": "B",
    "target": "markdown"
  },
  "footnote_group": {
    "bucket": "B",
    "target": "markdown"
  },
  "further_reading": {
    "bucket": "B",
    "target": "markdown"
  },
  "glossary_inline": {
    "bucket": "B",
    "target": "markdown"
  },
  "glossary_term": {
    "bucket": "B",
    "target": "markdown"
  },
  "intro": {
    "bucket": "B",
    "target": "markdown"
  },
  "post_metadata_bar": {
    "bucket": "B",
    "target": "markdown"
  },
  "reading_progress_bar": {
    "bucket": "B",
    "target": "markdown"
  },
  "share_quote": {
    "bucket": "B",
    "target": "markdown"
  },
  "social_share_bar": {
    "bucket": "B",
    "target": "markdown"
  },
  "time_estimate": {
    "bucket": "B",
    "target": "markdown"
  },
  "embed_codepen": {
    "bucket": "B",
    "target": "markdown"
  },
  "embed_gist": {
    "bucket": "B",
    "target": "markdown"
  },
  "embed_google_slides": {
    "bucket": "B",
    "target": "markdown"
  },
  "embed_stackblitz": {
    "bucket": "B",
    "target": "markdown"
  },
  "embed_tweet": {
    "bucket": "B",
    "target": "markdown"
  },
  "figma_embed": {
    "bucket": "B",
    "target": "markdown"
  },
  "framed_screenshot": {
    "bucket": "B",
    "target": "markdown"
  },
  "live_demo_embed": {
    "bucket": "B",
    "target": "markdown"
  },
  "lottie_animation": {
    "bucket": "B",
    "target": "markdown"
  },
  "maps_embed": {
    "bucket": "B",
    "target": "markdown"
  },
  "media_stream_card": {
    "bucket": "B",
    "target": "markdown"
  },
  "social_feed_embed": {
    "bucket": "B",
    "target": "markdown"
  },
  "youtube": {
    "bucket": "B",
    "target": "markdown"
  },
  "scroll_gallery": {
    "bucket": "B",
    "target": "markdown"
  },
  "achievement_badge": {
    "bucket": "B",
    "target": "markdown"
  },
  "cert_disclaimer": {
    "bucket": "B",
    "target": "markdown"
  },
  "completion_gate": {
    "bucket": "B",
    "target": "markdown"
  },
  "difficulty_badge": {
    "bucket": "B",
    "target": "markdown"
  },
  "fill_in_blank": {
    "bucket": "B",
    "target": "markdown"
  },
  "knowledge_check": {
    "bucket": "B",
    "target": "markdown"
  },
  "lesson_nav": {
    "bucket": "B",
    "target": "markdown"
  },
  "progress_checkpoint": {
    "bucket": "B",
    "target": "markdown"
  },
  "quiz_question": {
    "bucket": "B",
    "target": "markdown"
  },
  "quiz_result_summary": {
    "bucket": "B",
    "target": "markdown"
  },
  "quiz_set": {
    "bucket": "B",
    "target": "markdown"
  },
  "scenario_branch": {
    "bucket": "B",
    "target": "markdown"
  },
  "scenario_case": {
    "bucket": "B",
    "target": "markdown"
  },
  "score_summary": {
    "bucket": "B",
    "target": "markdown"
  },
  "spaced_repetition_card": {
    "bucket": "B",
    "target": "markdown"
  },
  "study_timer": {
    "bucket": "B",
    "target": "markdown"
  },
  "video_checkpoint": {
    "bucket": "B",
    "target": "markdown"
  },
  "xp_bar": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_context": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_similar": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_quotes": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_structure": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_eli5": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_freeform": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_synthesis": {
    "bucket": "B",
    "target": "markdown"
  },
  "lens_themes": {
    "bucket": "B",
    "target": "markdown"
  },
  "blockquote_with_avatar": {
    "bucket": "B",
    "target": "markdown"
  },
  "contributor_list": {
    "bucket": "B",
    "target": "markdown"
  },
  "customer_logo_grid": {
    "bucket": "B",
    "target": "markdown"
  },
  "dark_feature_grid": {
    "bucket": "B",
    "target": "markdown"
  },
  "feature_grid": {
    "bucket": "B",
    "target": "markdown"
  },
  "icon_feature_grid": {
    "bucket": "B",
    "target": "markdown"
  },
  "pros_cons_list": {
    "bucket": "B",
    "target": "markdown"
  },
  "rating_comparison": {
    "bucket": "B",
    "target": "markdown"
  },
  "rating_stars": {
    "bucket": "B",
    "target": "markdown"
  },
  "social_proof_banner": {
    "bucket": "B",
    "target": "markdown"
  },
  "star_rating_display": {
    "bucket": "B",
    "target": "markdown"
  },
  "versus_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "ai_build_trace": {
    "bucket": "B",
    "target": "markdown"
  },
  "atom_anatomy": {
    "bucket": "B",
    "target": "markdown"
  },
  "copy_prompt": {
    "bucket": "B",
    "target": "markdown"
  },
  "gemini_handoff": {
    "bucket": "B",
    "target": "markdown"
  },
  "gemini_prompt": {
    "bucket": "B",
    "target": "markdown"
  },
  "live_edit": {
    "bucket": "B",
    "target": "markdown"
  },
  "prompt_template": {
    "bucket": "B",
    "target": "markdown"
  },
  "prompt_to_schema": {
    "bucket": "B",
    "target": "markdown"
  },
  "api_reference": {
    "bucket": "B",
    "target": "markdown"
  },
  "cli_command": {
    "bucket": "B",
    "target": "markdown"
  },
  "command_step": {
    "bucket": "B",
    "target": "markdown"
  },
  "countdown_ring": {
    "bucket": "B",
    "target": "markdown"
  },
  "countdown_timer": {
    "bucket": "B",
    "target": "markdown"
  },
  "deadline_ticker": {
    "bucket": "B",
    "target": "markdown"
  },
  "feed_status": {
    "bucket": "B",
    "target": "markdown"
  },
  "http_request_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "keyboard_shortcut": {
    "bucket": "B",
    "target": "markdown"
  },
  "live_clock": {
    "bucket": "B",
    "target": "markdown"
  },
  "live_metric": {
    "bucket": "B",
    "target": "markdown"
  },
  "live_vote": {
    "bucket": "B",
    "target": "markdown"
  },
  "log_output": {
    "bucket": "B",
    "target": "markdown"
  },
  "notification_badge": {
    "bucket": "B",
    "target": "markdown"
  },
  "presence_bar": {
    "bucket": "B",
    "target": "markdown"
  },
  "raise_hand": {
    "bucket": "B",
    "target": "markdown"
  },
  "release_notes": {
    "bucket": "B",
    "target": "markdown"
  },
  "risk_flag": {
    "bucket": "B",
    "target": "markdown"
  },
  "roadmap_card": {
    "bucket": "B",
    "target": "markdown"
  },
  "sla_timer_display": {
    "bucket": "B",
    "target": "markdown"
  },
  "terminal_block": {
    "bucket": "B",
    "target": "markdown"
  },
  "toast_notification": {
    "bucket": "B",
    "target": "markdown"
  },
  "playbook": {
    "bucket": "B",
    "target": "markdown"
  },
  "breadcrumb": {
    "bucket": "D",
    "target": "image"
  },
  "color_section": {
    "bucket": "D",
    "target": "image"
  },
  "columns": {
    "bucket": "D",
    "target": "image"
  },
  "content_tabs": {
    "bucket": "D",
    "target": "image"
  },
  "copy_to_clipboard": {
    "bucket": "D",
    "target": "image"
  },
  "data_source": {
    "bucket": "D",
    "target": "image"
  },
  "firestore_read": {
    "bucket": "D",
    "target": "image"
  },
  "nav_bar": {
    "bucket": "D",
    "target": "image"
  },
  "pagination": {
    "bucket": "D",
    "target": "image"
  },
  "palette": {
    "bucket": "D",
    "target": "image"
  },
  "print_button": {
    "bucket": "D",
    "target": "image"
  },
  "progress_store": {
    "bucket": "D",
    "target": "image"
  },
  "segmented_control": {
    "bucket": "D",
    "target": "image"
  },
  "sheet_preview": {
    "bucket": "D",
    "target": "image"
  },
  "skeleton": {
    "bucket": "D",
    "target": "image"
  },
  "spinner": {
    "bucket": "D",
    "target": "image"
  },
  "split_pane": {
    "bucket": "D",
    "target": "image"
  },
  "tab_bar": {
    "bucket": "D",
    "target": "image"
  },
  "tabs": {
    "bucket": "D",
    "target": "image"
  },
  "tooltip": {
    "bucket": "D",
    "target": "image"
  },
  "adsb_feed": {
    "bucket": "D",
    "target": "image"
  },
  "airspace_command_deck": {
    "bucket": "D",
    "target": "image"
  },
  "canvas_plexus": {
    "bucket": "D",
    "target": "image"
  },
  "geo_contour_waves": {
    "bucket": "D",
    "target": "image"
  },
  "geo_europe_airspace": {
    "bucket": "D",
    "target": "image"
  },
  "geo_iso_fleet": {
    "bucket": "D",
    "target": "image"
  },
  "geo_iso_heli_hover": {
    "bucket": "D",
    "target": "image"
  },
  "geo_iso_rocket_launch": {
    "bucket": "D",
    "target": "image"
  },
  "geo_iso_takeoff": {
    "bucket": "D",
    "target": "image"
  },
  "geo_mercator_radar": {
    "bucket": "D",
    "target": "image"
  },
  "globe_3d": {
    "bucket": "D",
    "target": "image"
  },
  "isometric_mesh": {
    "bucket": "D",
    "target": "image"
  },
  "metar_feed": {
    "bucket": "D",
    "target": "image"
  },
  "orbit_diagram": {
    "bucket": "D",
    "target": "image"
  },
  "skill_radar": {
    "bucket": "D",
    "target": "image"
  },
  "conversion_funnel": {
    "bucket": "D",
    "target": "image"
  },
  "gauge_sla": {
    "bucket": "D",
    "target": "image"
  },
  "github_activity_grid": {
    "bucket": "D",
    "target": "image"
  },
  "heatmap": {
    "bucket": "D",
    "target": "image"
  },
  "masonry_elevation": {
    "bucket": "D",
    "target": "image"
  },
  "punch_card": {
    "bucket": "D",
    "target": "image"
  },
  "sankey_flow": {
    "bucket": "D",
    "target": "image"
  },
  "scatter_trend": {
    "bucket": "D",
    "target": "image"
  },
  "sequence_diagram": {
    "bucket": "D",
    "target": "image"
  },
  "trend_indicator": {
    "bucket": "D",
    "target": "image"
  },
  "uptime_timeline": {
    "bucket": "D",
    "target": "image"
  },
  "word_cloud": {
    "bucket": "D",
    "target": "image"
  },
  "bento_grid": {
    "bucket": "D",
    "target": "image"
  },
  "comparison_morph": {
    "bucket": "D",
    "target": "image"
  },
  "css_dropdown_menu": {
    "bucket": "D",
    "target": "image"
  },
  "css_modal": {
    "bucket": "D",
    "target": "image"
  },
  "css_slide_panel": {
    "bucket": "D",
    "target": "image"
  },
  "flip_card": {
    "bucket": "D",
    "target": "image"
  },
  "hover_card": {
    "bucket": "D",
    "target": "image"
  },
  "image_hotspots": {
    "bucket": "D",
    "target": "image"
  },
  "navigation_menu": {
    "bucket": "D",
    "target": "image"
  },
  "particle_burst": {
    "bucket": "D",
    "target": "image"
  },
  "ambient_gradient": {
    "bucket": "D",
    "target": "image"
  },
  "animated_beam": {
    "bucket": "D",
    "target": "image"
  },
  "animated_border": {
    "bucket": "D",
    "target": "image"
  },
  "animated_border_card": {
    "bucket": "D",
    "target": "image"
  },
  "animated_counter": {
    "bucket": "D",
    "target": "image"
  },
  "aurora_background": {
    "bucket": "D",
    "target": "image"
  },
  "badge_showcase": {
    "bucket": "D",
    "target": "image"
  },
  "big_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "blur_fade_in": {
    "bucket": "D",
    "target": "image"
  },
  "card_stack": {
    "bucket": "D",
    "target": "image"
  },
  "confetti_burst": {
    "bucket": "D",
    "target": "image"
  },
  "confetti_trigger": {
    "bucket": "D",
    "target": "image"
  },
  "count_up_stat": {
    "bucket": "D",
    "target": "image"
  },
  "cursor_glow": {
    "bucket": "D",
    "target": "image"
  },
  "cursor_trail": {
    "bucket": "D",
    "target": "image"
  },
  "depth_stack": {
    "bucket": "D",
    "target": "image"
  },
  "dot_grid_background": {
    "bucket": "D",
    "target": "image"
  },
  "effect_overlay": {
    "bucket": "D",
    "target": "image"
  },
  "encrypted_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "floating_badge": {
    "bucket": "D",
    "target": "image"
  },
  "floating_orbs": {
    "bucket": "D",
    "target": "image"
  },
  "floating_particles": {
    "bucket": "D",
    "target": "image"
  },
  "flow_connector": {
    "bucket": "D",
    "target": "image"
  },
  "focus_lens": {
    "bucket": "D",
    "target": "image"
  },
  "glitch_text": {
    "bucket": "D",
    "target": "image"
  },
  "glow_button": {
    "bucket": "D",
    "target": "image"
  },
  "glowing_stat": {
    "bucket": "D",
    "target": "image"
  },
  "gradient_border_card": {
    "bucket": "D",
    "target": "image"
  },
  "gradient_heading": {
    "bucket": "D",
    "target": "image"
  },
  "gradient_text": {
    "bucket": "D",
    "target": "image"
  },
  "highlight_sweep": {
    "bucket": "D",
    "target": "image"
  },
  "hint_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "icon_liftoff": {
    "bucket": "D",
    "target": "image"
  },
  "kinetic_headline": {
    "bucket": "D",
    "target": "image"
  },
  "liquid_button": {
    "bucket": "D",
    "target": "image"
  },
  "loading_dots": {
    "bucket": "D",
    "target": "image"
  },
  "loading_skeleton": {
    "bucket": "D",
    "target": "image"
  },
  "magnetic_button": {
    "bucket": "D",
    "target": "image"
  },
  "magnetic_element": {
    "bucket": "D",
    "target": "image"
  },
  "marquee": {
    "bucket": "D",
    "target": "image"
  },
  "marquee_strip": {
    "bucket": "D",
    "target": "image"
  },
  "mesh_gradient": {
    "bucket": "D",
    "target": "image"
  },
  "meteor_shower": {
    "bucket": "D",
    "target": "image"
  },
  "neon_glow": {
    "bucket": "D",
    "target": "image"
  },
  "neon_text": {
    "bucket": "D",
    "target": "image"
  },
  "noise_card": {
    "bucket": "D",
    "target": "image"
  },
  "number_flip": {
    "bucket": "D",
    "target": "image"
  },
  "number_odometer": {
    "bucket": "D",
    "target": "image"
  },
  "parallax_card": {
    "bucket": "D",
    "target": "image"
  },
  "parallax_section": {
    "bucket": "D",
    "target": "image"
  },
  "pattern_background": {
    "bucket": "D",
    "target": "image"
  },
  "progress_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "pulse_dot": {
    "bucket": "D",
    "target": "image"
  },
  "reaction_shower": {
    "bucket": "D",
    "target": "image"
  },
  "reveal": {
    "bucket": "D",
    "target": "image"
  },
  "reveal_line": {
    "bucket": "D",
    "target": "image"
  },
  "reveal_on_scroll": {
    "bucket": "D",
    "target": "image"
  },
  "ripple_button": {
    "bucket": "D",
    "target": "image"
  },
  "schema_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "scramble_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "scroll_progress": {
    "bucket": "D",
    "target": "image"
  },
  "scroll_to_top": {
    "bucket": "D",
    "target": "image"
  },
  "scroll_trigger": {
    "bucket": "D",
    "target": "image"
  },
  "shimmer_button": {
    "bucket": "D",
    "target": "image"
  },
  "shimmer_text": {
    "bucket": "D",
    "target": "image"
  },
  "skeleton_stage_card": {
    "bucket": "D",
    "target": "image"
  },
  "sonar_pulse": {
    "bucket": "D",
    "target": "image"
  },
  "speed_counter": {
    "bucket": "D",
    "target": "image"
  },
  "split_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "spotlight_card": {
    "bucket": "D",
    "target": "image"
  },
  "spotlight_cursor": {
    "bucket": "D",
    "target": "image"
  },
  "spring_nodes": {
    "bucket": "D",
    "target": "image"
  },
  "stagger_list": {
    "bucket": "D",
    "target": "image"
  },
  "step_reveal_sequence": {
    "bucket": "D",
    "target": "image"
  },
  "stripe_background": {
    "bucket": "D",
    "target": "image"
  },
  "surface_unlocked": {
    "bucket": "D",
    "target": "image"
  },
  "svg_path_draw": {
    "bucket": "D",
    "target": "image"
  },
  "terminal_boot": {
    "bucket": "D",
    "target": "image"
  },
  "text_reveal_mask": {
    "bucket": "D",
    "target": "image"
  },
  "tilt_card": {
    "bucket": "D",
    "target": "image"
  },
  "typewriter": {
    "bucket": "D",
    "target": "image"
  },
  "typewriter_text": {
    "bucket": "D",
    "target": "image"
  },
  "typing_indicator": {
    "bucket": "D",
    "target": "image"
  },
  "wave_divider": {
    "bucket": "D",
    "target": "image"
  },
  "word_flip": {
    "bucket": "D",
    "target": "image"
  },
  "word_reveal": {
    "bucket": "D",
    "target": "image"
  },
  "word_scramble": {
    "bucket": "D",
    "target": "image"
  },
  "primitive_plate": {
    "bucket": "D",
    "target": "image"
  },
  "action_items": {
    "bucket": "D",
    "target": "image"
  },
  "agenda_block": {
    "bucket": "D",
    "target": "image"
  },
  "calendar_today": {
    "bucket": "D",
    "target": "image"
  },
  "calendar_upcoming": {
    "bucket": "D",
    "target": "image"
  },
  "call_mood_board": {
    "bucket": "D",
    "target": "image"
  },
  "chat_sequence": {
    "bucket": "D",
    "target": "image"
  },
  "conversation_snippet": {
    "bucket": "D",
    "target": "image"
  },
  "doc_ai_summary": {
    "bucket": "D",
    "target": "image"
  },
  "drive_file_card": {
    "bucket": "D",
    "target": "image"
  },
  "drive_file_list": {
    "bucket": "D",
    "target": "image"
  },
  "drive_folder_contents": {
    "bucket": "D",
    "target": "image"
  },
  "drive_image": {
    "bucket": "D",
    "target": "image"
  },
  "drive_recent_files": {
    "bucket": "D",
    "target": "image"
  },
  "drive_storage_usage": {
    "bucket": "D",
    "target": "image"
  },
  "gmail_inbox": {
    "bucket": "D",
    "target": "image"
  },
  "gmail_summary": {
    "bucket": "D",
    "target": "image"
  },
  "gmail_unread_count": {
    "bucket": "D",
    "target": "image"
  },
  "heatmap_calendar": {
    "bucket": "D",
    "target": "image"
  },
  "multi_doc_ai_brief": {
    "bucket": "D",
    "target": "image"
  },
  "sentiment_summary": {
    "bucket": "D",
    "target": "image"
  },
  "sheet_form": {
    "bucket": "D",
    "target": "image"
  },
  "sheet_stats": {
    "bucket": "D",
    "target": "image"
  },
  "tasks_today": {
    "bucket": "D",
    "target": "image"
  },
  "user_greeting": {
    "bucket": "D",
    "target": "image"
  },
  "user_profile_card": {
    "bucket": "D",
    "target": "image"
  },
  "workspace_logo": {
    "bucket": "D",
    "target": "image"
  },
  "workspace_logo_grid": {
    "bucket": "D",
    "target": "image"
  },
  "workspace_logo_strip": {
    "bucket": "D",
    "target": "image"
  },
  "cohort_retention": {
    "bucket": "D",
    "target": "image"
  },
  "schema_qr": {
    "bucket": "D",
    "target": "image"
  },
  "surface_map": {
    "bucket": "D",
    "target": "image"
  },
  "url_anatomy": {
    "bucket": "D",
    "target": "image"
  },
  "command_palette": {
    "bucket": "D",
    "target": "image"
  },
  "incident_log": {
    "bucket": "D",
    "target": "image"
  },
  "service_status_board": {
    "bucket": "D",
    "target": "image"
  },
  "stat_pulse": {
    "bucket": "D",
    "target": "image"
  },
  "weather_now": {
    "bucket": "D",
    "target": "image"
  },
  "weather_outlook": {
    "bucket": "D",
    "target": "image"
  },
  "gdm_rocket_panel": {
    "bucket": "D",
    "target": "image"
  },
  "iso_fireworks_panel": {
    "bucket": "D",
    "target": "image"
  }
};

export const SLACK_CHART_TYPES = {
  "chartjs_bar": "bar",
  "chartjs_line": "line",
  "chartjs_pie": "pie",
  "stacked_area": "area",
  "sparkline": "line",
  "benchmark_comparison": "bar",
  "skill_bars": "bar",
  "confidence_bar": "bar",
  "donut_stat": "pie",
  "mini_sparkline_set": "line"
};
