"""The a2ui-state catalog (behavioral vocabulary) must publish cleanly and stay
in sync with the renderer's state primitives — the companion to the atom catalog
that makes wired-surface authoring validate against one agreed vocabulary.
"""
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent
CATALOG = ROOT / "public" / "catalogue" / "a2ui-state-v1.json"
SRC = ROOT / "spec" / "a2ui-state.yaml"

# The primitives the wired renderer's engine dispatches (A2UIState.html switch).
RENDERER_PRIMITIVES = {
    "ValueStore", "Computed", "DerivedStore", "ArrayFilter",
    "NumericThreshold", "StepNavigator", "StringValidator", "Timer",
}


def test_catalog_published():
    # a2ui-state-v1.json is now an A2UI-v1.0 catalog document (components/functions
    # object maps), not the legacy descriptor — see test_a2ui_catalog_schema.py.
    assert CATALOG.exists(), "run scripts/gen_state_catalog.py (catalog-rebuild)"
    d = json.loads(CATALOG.read_text())
    # catalogId/$id must be a RESOLVABLE URI (not the bare slug) — a host dereferences it
    assert d["$id"] == d["catalogId"]
    assert d["catalogId"].startswith("http") and d["catalogId"].endswith("a2ui-state-v1.json")
    assert d["components"] and d["functions"]


def test_catalog_matches_renderer_primitives():
    """The published catalog must declare exactly the primitives the renderer
    implements — no drift, or a wired surface validates against a lie. Primitives
    live in `components` alongside column-render-hints; isolate them via the source."""
    d = json.loads(CATALOG.read_text())
    src_prims = {p["id"] for p in yaml.safe_load(SRC.read_text())["primitives"]}
    declared = set(d["components"]) & src_prims
    assert declared == RENDERER_PRIMITIVES, (
        f"a2ui-state catalog drift vs renderer: "
        f"missing {RENDERER_PRIMITIVES - declared}, extra {declared - RENDERER_PRIMITIVES}"
    )


def test_catalog_regenerates_from_source():
    """Catalog is a pure function of spec/a2ui-state.yaml (cattle, not pets):
    every source primitive is a component, every derived op is a function."""
    src = yaml.safe_load(SRC.read_text())
    d = json.loads(CATALOG.read_text())
    for p in src["primitives"]:
        assert p["id"] in d["components"], f"primitive {p['id']} missing from catalog components"
    assert {op["op"] for op in src.get("derived_store_ops", [])} == set(d["functions"])


def test_references_the_atom_catalog():
    """A wired surface needs both catalogs — the state catalog must point at the
    atom catalog so the pairing is discoverable. Under the strict v1.0 catalog
    schema the companion reference rides in `instructions` (not a custom key)."""
    d = json.loads(CATALOG.read_text())
    assert "a2ui-atoms-v1" in d.get("instructions", ""), \
        "companion atom catalog not referenced in instructions"


SNAPSHOTS = [
    ROOT / "apps-script-surface" / "gas-wired-renderer" / "exprs_schema_snapshot.gs",
    ROOT / "apps-script-surface" / "gas-wired-renderer-starter" / "exprs_schema_snapshot.gs",
]


def test_snapshot_is_generated_and_in_sync():
    """The renderer authoring-prompt snapshot is GENERATED from the sources —
    it must be byte-current with what gen_state_catalog produces, and both copies
    identical (no hand-edit drift). Regenerate via catalog-rebuild if this fails."""
    import subprocess
    import sys

    subprocess.run([sys.executable, str(ROOT / "scripts" / "gen_state_catalog.py")],
                   check=True, capture_output=True)
    texts = [p.read_text() for p in SNAPSHOTS if p.exists()]
    assert texts, "no snapshot files found"
    for p, t in zip(SNAPSHOTS, texts):
        assert "GENERATED by scripts/gen_state_catalog.py" in t, f"{p} not marked generated"
        # every published state primitive must appear in the prompt snapshot
        for prim in RENDERER_PRIMITIVES:
            assert prim in t, f"{p} missing primitive {prim} — snapshot drifted from source"
    assert len(set(texts)) == 1, "the two snapshot copies drifted from each other"


# The derived-store ops the engine's augment loop actually implements
# (A2UIState.html: the `add` colDef switch + SERIES_OPS). The catalog must declare
# EXACTLY these — no more (the ratio_pct ghost: catalogued, never implemented),
# no fewer (multiply_diff/pct_diff/signal_threshold/series were live-but-uncatalogued).
# Keep this set in sync with the engine; test_renderer_derived_ops_matches_engine
# guards the set itself against source drift.
RENDERER_DERIVED_OPS = {
    "elapsed_seconds", "format_duration", "threshold_by_field",
    "multiply_diff", "pct_diff", "signal_threshold",
    "sma", "rsi", "bband_upper", "bband_lower",
}

ENGINE = ROOT / "apps-script-surface" / "gas-wired-renderer" / "A2UIState.html"


def test_catalog_derived_ops_match_renderer():
    """The published derived_store_ops must be exactly what the engine implements —
    the drift guard whose absence let ratio_pct (catalogued, unimplemented) survive."""
    d = json.loads(CATALOG.read_text())
    declared = set(d.get("functions", {}))          # derived-store ops are catalog functions
    assert declared == RENDERER_DERIVED_OPS, (
        f"derived_store_ops drift vs engine: "
        f"missing {RENDERER_DERIVED_OPS - declared}, extra {declared - RENDERER_DERIVED_OPS}"
    )


def test_renderer_derived_ops_matches_engine():
    """Guard the guard: RENDERER_DERIVED_OPS must match what A2UIState.html actually
    dispatches, so the expected set can't silently rot away from the engine."""
    import re
    src = ENGINE.read_text()
    # augment-loop switch cases are lowercase-snake (primitive dispatch is CamelCase;
    # gas: verbs carry a colon) — so [a-z][a-z_]* selects exactly the op cases.
    case_ops = set(re.findall(r"case '([a-z][a-z_]*)':\s*r\[colDef", src))
    series_ops = set()
    m = re.search(r"SERIES_OPS\s*=\s*\{([^}]*)\}", src)
    if m:
        series_ops = set(re.findall(r"(\w+)\s*:", m.group(1)))
    engine_ops = case_ops | series_ops
    assert engine_ops == RENDERER_DERIVED_OPS, (
        f"RENDERER_DERIVED_OPS out of sync with engine source: "
        f"engine has {engine_ops}, set has {RENDERER_DERIVED_OPS}"
    )
