"""scene_stage / clipart: the scene-atom kit's atoms.

Their schema blocks are visibility:private and live in a2ui-private/private-atoms/; what is public is the renderer (the estate's
shared infra), the pack entry and the declared debt. These tests pin that split and prove the generated GAS files render in a bare
runtime (no DOM, no TextEncoder), the way Apps Script and the Worker run renderers.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
GAS = ROOT / "apps-script-surface" / "gas-wired-renderer"
FILES = sorted(GAS.glob("atoms_scene*.gs"))            # the estate concatenates atoms_*.gs in sorted order
NODE = shutil.which("node")


def test_the_atoms_sit_in_the_effects_pack_and_no_new_dangling_catalogue_is_advertised():
    """A new extension pack would be advertised in the public index without a catalogue file (test_staging forbids growing that debt),
    so the scene atoms live in a2ui-effects-v1, whose selection text names them."""
    packs = yaml.safe_load((ROOT / "atoms" / "atom-packs.yaml").read_text())
    assert "a2ui-scenes-v1" not in packs
    assert {"clipart", "scene_stage"} <= set(packs["a2ui-effects-v1"])
    assert "scene_stage" in (ROOT / "scripts" / "gen_catalog_index.py").read_text()


def test_the_atoms_are_public_stable_and_no_longer_declared_debt():
    """Promoted 2026-09-20 (Curtis: publish them publicly): definitions live in the public schema, stable, no visibility flag."""
    blocks = {b["type"]: b for b in yaml.safe_load((ROOT / "atoms" / "schema.yaml").read_text())["blocks"] if isinstance(b, dict)}
    for t_ in ("scene_stage", "clipart"):
        assert t_ in blocks and blocks[t_].get("stage", "stable") == "stable" and "visibility" not in blocks[t_], t_
        assert blocks[t_]["source"]["license"] == "MIT"
        assert "mcp-apps" in blocks[t_]["surfaces"]["works_on"]
    debt = yaml.safe_load((ROOT / "project.yaml").read_text())["known_debt"]["unregistered_atoms"]
    assert not ({"scene_stage", "clipart"} & set(debt)), "no longer schema-absent"


def test_generated_files_are_marked_and_split_engine_from_data():
    assert [f.name for f in FILES] == ["atoms_scene.gs", "atoms_scene_data.gs"]
    for f in FILES:
        assert f.read_text().startswith("// GENERATED by scene-atom/gen_scene_gs.py"), f.name
    engine, data = (f.read_text() for f in FILES)
    assert "_RENDERERS['scene_stage']" in engine and "_RENDERERS['clipart']" in engine
    assert "var SCENE_STAGE_DATA = " in data and "SCENE_STAGE_DATA" in engine
    for banned in ("import.meta", "fetch(", "document.", "window.", "localStorage", "require("):
        assert banned not in engine, banned


def test_python_static_renderer_degrades_visibly_and_escapes_payload_text():
    from renderers.web_article import _RENDERERS
    html = _RENDERERS["scene_stage"]({"type": "scene_stage", "preset": "data-centre", "title": "<script>alert(1)</script>"})
    assert "<script" not in html and "&lt;script&gt;" in html and "data-centre" in html and "MCP Apps" in html
    clip = _RENDERERS["clipart"]({"type": "clipart", "asset": "desk", "alt": 'a "desk" <b>'})
    assert "<b>" not in clip and "&quot;desk&quot;" in clip
    assert "clipart" in _RENDERERS["clipart"]({"type": "clipart"}), "even an empty block must not render nothing"


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_gas_files_render_scenes_in_a_bare_runtime_without_a_dom():
    js = r"""
    const vm = require('vm'), fs = require('fs'); const ctx = vm.createContext({});
    vm.runInContext('var _RENDERERS = {};', ctx);
    for (const f of JSON.parse(process.argv[1])) vm.runInContext(fs.readFileSync(f, 'utf8'), ctx);   // sorted, as the estate loads them
    const run = (src) => vm.runInContext(src, ctx);
    ctx.b1 = {type: 'scene_stage', preset: 'data-centre'};
    ctx.b2 = {type: 'scene_stage', preset: 'wind-farm', title: '<script>alert(1)</script>', theme: {time: 'night'}};
    ctx.b3 = {type: 'scene_stage', preset: 'no-such-place'};
    ctx.c1 = {type: 'clipart', asset: 'desk', scale: 2, flip: true, label: 'A desk'};
    ctx.c2 = {type: 'clipart', asset: 'not-a-prop'};
    const out = {textEncoder: run('typeof TextEncoder'), globals: Object.keys(ctx).filter(k => !/^[bc]\d$/.test(k)).sort(),
      renderers: Object.keys(ctx._RENDERERS).sort(),
      s1: run('_RENDERERS.scene_stage(b1)'), s2: run('_RENDERERS.scene_stage(b2)'), s3: run('_RENDERERS.scene_stage(b3)'),
      c1: run('_RENDERERS.clipart(c1)'), c2: run('_RENDERERS.clipart(c2)')};
    console.log(JSON.stringify(out));
    """
    r = subprocess.run([NODE, "-e", js, json.dumps([str(f) for f in FILES])], capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    o = json.loads(r.stdout)
    assert o["textEncoder"] == "undefined" and o["globals"] == ["SCENE_STAGE_DATA", "SceneStage", "_RENDERERS"]
    assert o["renderers"] == ["clipart", "scene_stage"]
    for k in ("s1", "s2"):
        assert o[k].startswith('<figure class="a2ui-scene"') and "<animate" in o[k] and "scene-atom:provenance" in o[k], k
        assert not re.search(r"<script|onload=|onclick=|javascript:", o[k]), f"{k}: the drawn scene must contain no script"
    assert "&lt;script&gt;" in o["s2"], "titles are escaped"
    prov = json.loads(re.search(r"<scene-atom:provenance[^>]*>(.*?)</scene-atom:provenance>", o["s1"]).group(1).replace("&quot;", '"').replace("&amp;", "&"))
    assert prov["assets"] and all(a["license"] == "MIT" and len(a["sha256"]) == 64 for a in prov["assets"])
    assert "spec.preset must be one of" in o["s3"] and "no-such-place" not in o["s3"].split("one of")[0]
    assert o["c1"].startswith('<figure class="a2ui-clipart"') and "scale(-1 1)" in o["c1"] and "A desk" in o["c1"]
    assert "must be an id from the asset index" in o["c2"]


def test_the_mcp_apps_bundle_carries_the_engine_and_the_data():
    """Bundled since 2026-09-20 (size-guard ceiling raised with Curtis's go-ahead). If a host rejects the size, the data file goes back
    into EXCLUDE_FILES and the atoms answer with a readable card there (the engine still says so, see the other test)."""
    import sys
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    names = {f.name for f in g.renderer_files()}
    assert "atoms_scene.gs" in names and "atoms_scene_data.gs" in names
    assert "not bundled on this surface" in (GAS / "atoms_scene.gs").read_text()


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_a_layout_without_scenery_actors_or_camera_still_renders_and_a_bad_one_says_what_is_wrong():
    """Found by a blind LLM-style test: a model writing a layout in full may leave out actors/scenery/camera; those default."""
    js = r"""
    const vm = require('vm'), fs = require('fs'); const ctx = vm.createContext({}); vm.runInContext('var _RENDERERS = {};', ctx);
    for (const f of JSON.parse(process.argv[1])) vm.runInContext(fs.readFileSync(f, 'utf8'), ctx);
    ctx.ok = {type: 'scene_stage', backdrop: 'interior-office', ground: 'concrete', stage: {width: 1400, zoom: 1300, focus_y: -260}, scenery: [{prop: 'desk', x: 600}]};
    ctx.bare = {type: 'scene_stage', backdrop: 'sky-hills', ground: 'grass', stage: {width: 1400, zoom: 1300, focus_y: -260}};
    ctx.bad = {type: 'scene_stage', backdrop: 'sky-hills', stage: {width: 1400, zoom: 1300, focus_y: -260}};
    console.log(JSON.stringify(['ok', 'bare', 'bad'].map(k => vm.runInContext('_RENDERERS.scene_stage(' + k + ')', ctx))));
    """
    r = subprocess.run([NODE, "-e", js, json.dumps([str(f) for f in FILES])], capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    ok, bare, bad = json.loads(r.stdout)
    assert ok.startswith("<figure") and bare.startswith("<figure") and "<animate" in ok
    assert "spec.ground must be one of" in bad


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_itself_renders_scenes_and_clipart():
    """Build the real MCP Apps bundle in memory, run its DOM-free core in Node, and render both atoms through renderAtoms."""
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    bundle = g.build_bundle()
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", bundle, re.S) if "a2ui-core" in b[:300]][0]
    blocks = [{"type": "scene_stage", "preset": "wind-farm", "theme": {"time": "dusk"}}, {"type": "scene_stage", "preset": "no-such"},
              {"type": "clipart", "asset": "wind-turbine", "scale": 1.5, "label": "A turbine"}]
    with tempfile.TemporaryDirectory() as td:
        driver = Path(td) / "driver.js"
        driver.write_text("global.window = global;\n" + core + "\nvar out = " + json.dumps(blocks) +
                          ".map(function (b) { return renderAtoms([b], {theme: 'light'}); });\nconsole.log(JSON.stringify(out));\n")
        proc = subprocess.run([NODE, str(driver)], capture_output=True, text=True, timeout=120)
    assert proc.returncode == 0, proc.stderr[-2000:]
    scene, bad, clip = json.loads(proc.stdout)
    assert 'class="a2ui-scene"' in scene and "<animate" in scene and "scene-atom:provenance" in scene, scene[:300]
    assert "not bundled on this surface" not in scene and "spec.preset must be one of" in bad
    assert 'class="a2ui-clipart"' in clip and "A turbine" in clip
    assert len(bundle) < 3_200_000


def test_published_scene_assets_match_the_data_the_renderer_embeds():
    """public/catalogue/assets-index-v1.json and scene-spec.schema.json are generated by the kit (diagram-studio/scene-atom) and copied
    here. The index lists the WHOLE kit; the bundles embed the core props and a trusted hash for every prop, and the Worker module holds
    the full set. All of that must describe the same registry, or an agent is offered props the renderer cannot verify."""
    idx = json.loads((ROOT / "public" / "catalogue" / "assets-index-v1.json").read_text())
    data = json.loads((GAS / "atoms_scene_data.gs").read_text().split("var SCENE_STAGE_DATA = ", 1)[1].rsplit(";", 1)[0])
    full_src = (ROOT / "apps-script-surface" / "scene-kit" / "atoms_scene_full.gs").read_text()
    full = json.loads(full_src.split("var SCENE_STAGE_FULL = ", 1)[1].rsplit(";", 1)[0])
    assert idx["registry_sha256"] == data["registry_sha256"].replace(".", ""), "index and embedded data come from different registries: recopy from the kit"
    ids = {a["id"] for a in idx["assets"]}
    assert all(a["stage"] == "stable" for a in idx["assets"])
    assert ids == set(data["trusted_sha256"]) == {e["id"] for e in full["entries"]}, "every published prop has a trusted hash and is in the full kit"
    core = {e["id"] for e in data["entries"]}
    assert core < ids and len(core) < len(ids), "the bundles embed only the core, not the whole kit"
    for e in full["entries"]:
        assert data["trusted_sha256"][e["id"]] == e["sha256"]
    for f in (GAS / "atoms_scene.gs", GAS / "atoms_scene_data.gs", ROOT / "apps-script-surface" / "scene-kit" / "atoms_scene_full.gs"):
        assert not re.search(r"\b[0-9a-f]{40,}\b", f.read_text()), f"{f.name}: a long hex run would trip ops/pre_push_audit.py (digests are stored as two 32-hex halves)"
    assert {p["id"] for p in idx["presets"]} == set(data["layouts"]["layouts"])
    schema = json.loads((ROOT / "public" / "catalogue" / "scene-spec.schema.json").read_text())
    assert set(schema["properties"]["preset"]["enum"]) == set(data["layouts"]["layouts"])
    assert set(schema["properties"]["scenery"]["items"]["properties"]["prop"]["enum"]) == ids


def test_the_full_kit_stays_out_of_the_bundle_and_the_apps_script_project_but_in_the_worker_module():
    import sys
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    import gen_worker_renderers as w
    assert "atoms_scene_full.gs" not in {f.name for f in g.renderer_files()}, "MCP Apps bundle size guard"
    assert not (GAS / "atoms_scene_full.gs").exists(), "clasp pushes gas-wired-renderer/: the full kit must live elsewhere"
    assert "atoms_scene_full.gs" in {f.name for f in w.gs_load_order()}, "the Worker attaches props from it"
    assert "SceneStage };" in (ROOT / "scripts" / "gen_worker_renderers.py").read_text()


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_renders_a_non_core_prop_from_a_server_attachment_and_refuses_a_tampered_one():
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", g.build_bundle(), re.S) if "a2ui-core" in b[:300]][0]
    kit_files = [str(f) for f in FILES] + [str(ROOT / "apps-script-surface" / "scene-kit" / "atoms_scene_full.gs")]
    js_kit = r"""
    const vm = require('vm'), fs = require('fs'); const ctx = vm.createContext({}); vm.runInContext('var _RENDERERS = {};', ctx);
    for (const f of JSON.parse(process.argv[1])) vm.runInContext(fs.readFileSync(f, 'utf8'), ctx);
    ctx.b = {type: 'scene_stage', preset: 'farm-harvest', scenery_add: [{prop: 'laptop', x: 800}, {prop: 'cow', x: 900}]};
    console.log(JSON.stringify(vm.runInContext('SceneStage.kitFor(b)', ctx)));
    """
    kit = json.loads(subprocess.run([NODE, "-e", js_kit, json.dumps(kit_files)], capture_output=True, text=True, timeout=120, check=True).stdout)
    assert {e["id"] for e in kit["entries"]} >= {"laptop", "cow"}
    bad = json.loads(json.dumps(kit)); bad["entries"][0]["svg"] += "<!-- tampered -->"
    block = {"type": "scene_stage", "preset": "farm-harvest", "scenery_add": [{"prop": "laptop", "x": 800}, {"prop": "cow", "x": 900}]}
    with tempfile.TemporaryDirectory() as td:
        driver = Path(td) / "d.js"
        driver.write_text("global.window = global;\n" + core + "\nvar blocks = " + json.dumps([block, {**block, "_kit": kit}, {**block, "_kit": bad}]) +
                          ";\nconsole.log(JSON.stringify(blocks.map(function (b) { return renderAtoms([b], {theme: 'light'}); })));\n")
        out = json.loads(subprocess.run([NODE, str(driver)], capture_output=True, text=True, timeout=120, check=True).stdout)
    without, with_kit, tampered = out
    assert 'id="a-laptop"' not in without and "border:1px solid #fca5a5" in without, "no attachment: the bundle cannot draw a non-core prop and says so"
    assert 'class="a2ui-scene"' in with_kit and 'id="a-laptop"' in with_kit and 'id="a-cow"' in with_kit
    assert "failed verification" in tampered and "a-laptop" not in tampered


def test_every_scene_atom_field_description_survived_yaml_parsing():
    """An unquoted ' #' starts a YAML comment: 'string (optional, #rrggbb)' once lost everything after 'optional,'. Guard the whole block."""
    blocks = {b["type"]: b for b in yaml.safe_load((ROOT / "atoms" / "schema.yaml").read_text())["blocks"] if isinstance(b, dict)}
    for t in ("scene_stage", "clipart"):
        for k, v in blocks[t]["fields"].items():
            assert isinstance(v, str) and len(v) > 25 and not v.rstrip().endswith((",", "(optional,")), f"{t}.{k} looks truncated: {v!r}"
    assert "#rrggbb" in blocks["scene_stage"]["fields"]["accent"]


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_draws_a_valid_sketch_and_refuses_an_invalid_one():
    """The escape hatch (sketch items) runs in every renderer: same allowlist as agent_sketchpad, refusal not silent skipping."""
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", g.build_bundle(), re.S) if "a2ui-core" in b[:300]][0]
    good = ['<rect x="-30" y="-24" width="60" height="24" fill="#a9784a" stroke="#23303a" stroke-width="2"/>', '<circle cx="0" cy="-34" r="10" fill="#f2c230"/>']
    blocks = [{"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"sketch": good, "x": 900, "scale": 2}]},
              {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"sketch": ['<script>alert(1)</script>'], "x": 900}]},
              {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"sketch": ['<image href="https://evil.example/a.png"/>'], "x": 900}]}]
    with tempfile.TemporaryDirectory() as td:
        d = Path(td) / "d.js"
        d.write_text("global.window = global;\n" + core + "\nvar b = " + json.dumps(blocks) + ";\nconsole.log(JSON.stringify(b.map(function (x) { return renderAtoms([x], {theme: 'light'}); })));\n")
        ok, script, image = json.loads(subprocess.run([NODE, str(d)], capture_output=True, text=True, timeout=120, check=True).stdout)
    assert 'fill="#a9784a"' in ok and 'class="a2ui-scene"' in ok and "<script" not in ok.replace("<metadata", "")
    for bad in (script, image):
        assert "not an allowed sketch element" in bad and "evil.example" not in bad.split("not an allowed")[0] and 'class="a2ui-scene"' not in bad


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_draws_house_style_sketches_with_animation_and_refuses_unsafe_animation():
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", g.build_bundle(), re.S) if "a2ui-core" in b[:300]][0]
    wag = '<g><animateTransform attributeName="transform" type="rotate" values="-14 0 0;14 0 0;-14 0 0" dur="0.5s" repeatCount="indefinite"/><rect x="-4" y="-30" width="8" height="30" fill="@wood"/></g>'
    blocks = [{"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"sketch": [wag], "anim": {"kind": "sway", "amount": 4}, "x": 900}]},
              {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"sketch": ['<g><animate attributeName="href" values="a;b" dur="1s"/></g>'], "x": 900}]},
              {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"sketch": ['<rect fill="@nonsense" width="1" height="1"/>'], "x": 900}]},
              {"type": "scene_stage", "preset": "airfield"}]
    with tempfile.TemporaryDirectory() as td:
        d = Path(td) / "d.js"
        d.write_text("global.window = global;\n" + core + "\nvar b = " + json.dumps(blocks) + ";\nconsole.log(JSON.stringify(b.map(function (x) { return renderAtoms([x], {theme: 'light'}); })));\n")
        out = json.loads(subprocess.run([NODE, str(d)], capture_output=True, text=True, timeout=120, check=True).stdout)
    ok, href, token, airfield = out
    assert 'fill="#b0804f"' in ok and 'type="rotate" values="-14 0 0;14 0 0;-14 0 0"' in ok and 'values="-4 0 0;4 0 0;-4 0 0"' in ok, "palette name resolved; both animation tiers present"
    assert "not an allowed sketch element" in href and 'attributeName="href"' not in href.split("not an allowed")[0]
    assert "not an allowed sketch element" in token
    assert "not embedded" in airfield or "jet-airliner" in airfield or 'class="a2ui-scene"' in airfield, "the airfield preset is known to the bundle"


def test_the_scene_stage_atom_lists_are_generated_from_the_kit_not_typed_by_hand():
    """The preset list once stayed at 45 long after there were 53 (no airfield, no interior-home), so a model was told the preset did not exist.
    scripts/sync_scene_stage_docs.py rewrites the lists from public/catalogue/scene-spec.schema.json; this fails if they drift."""
    import sys
    sys.path.insert(0, str(ROOT / "scripts"))
    import sync_scene_stage_docs as s
    text = (ROOT / "atoms" / "schema.yaml").read_text(encoding="utf-8")
    assert s.synced(text) == text, "run python3 scripts/sync_scene_stage_docs.py"
    spec = json.loads((ROOT / "public" / "catalogue" / "scene-spec.schema.json").read_text())["properties"]
    blocks = {b["type"]: b for b in yaml.safe_load(text)["blocks"] if isinstance(b, dict)}
    f = blocks["scene_stage"]["fields"]
    assert all(p in f["preset"] for p in spec["preset"]["enum"]) and f"({len(spec['preset']['enum'])} ready presets)" in blocks["scene_stage"]["compact_description"]
    assert all(b in f["backdrop"] for b in spec["backdrop"]["enum"]) and all(g in f["ground"] for g in spec["ground"]["enum"])


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_draws_real_text_labels_and_refuses_bad_ones():
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", g.build_bundle(), re.S) if "a2ui-core" in b[:300]][0]
    blocks = [{"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"x": 900, "label": "Site 4\nOpen", "colour": "@red", "bold": True}]},
              {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"x": 900, "label": "<script>alert(1)</script>"}]},
              {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"x": 900, "label": "hi", "colour": "not-a-colour"}]}]
    with tempfile.TemporaryDirectory() as td:
        d = Path(td) / "d.js"
        d.write_text("global.window = global;\n" + core + "\nvar b = " + json.dumps(blocks) + ";\nconsole.log(JSON.stringify(b.map(function (x) { return renderAtoms([x], {theme: 'light'}); })));\n")
        ok, script, badColour = json.loads(subprocess.run([NODE, str(d)], capture_output=True, text=True, timeout=120, check=True).stdout)
    assert "<text" in ok and ">Site 4<" in ok and ">Open<" in ok and 'class="a2ui-scene"' in ok, ok[:300]
    assert "&lt;script&gt;" in script and "<script>alert" not in script.replace("&lt;script&gt;", "")
    assert "spec.scenery" in badColour and "colour must be" in badColour


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_reuses_a_real_prop_via_use_once_the_worker_attaches_it():
    """A non-core prop reused via <use> needs the SAME Worker-attaches-then-bundle-renders path as a normal `prop` reference. kitFor (the
    Worker's per-block attachment scanner) must scan sketch fragments for these references too, not only the plain `prop` field -- this is
    the gap a first version of the feature had, found by testing the real attachment path end to end rather than only local calls."""
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", g.build_bundle(), re.S) if "a2ui-core" in b[:300]][0]
    full_src = (ROOT / "apps-script-surface" / "scene-kit" / "atoms_scene_full.gs").read_text()
    block = {"type": "scene_stage", "preset": "wind-farm", "scenery_add": [{"x": 900, "sketch": ['<use href="#a-cow" transform="scale(0.5)"/>']}]}
    with tempfile.TemporaryDirectory() as td:
        js_kit = Path(td) / "kit.js"
        js_kit.write_text("global.window = global;\n" + core + "\n" + full_src + "\nconsole.log(JSON.stringify(SceneStage.kitFor(" + json.dumps(block) + ")));\n")
        kit = json.loads(subprocess.run([NODE, str(js_kit)], capture_output=True, text=True, timeout=120, check=True).stdout)
        assert kit and any(e["id"] == "cow" for e in kit["entries"]), "kitFor must find 'cow' inside the sketch's <use>, not only in a plain `prop` field"
        d = Path(td) / "d.js"
        d.write_text("global.window = global;\n" + core + "\nvar noAttach = renderAtoms([" + json.dumps(block) + "], {theme: 'light'});\n"
                     "var withAttach = renderAtoms([" + json.dumps({**block, "_kit": kit}) + "], {theme: 'light'});\n"
                     "console.log(JSON.stringify([noAttach, withAttach]));\n")
        no_attach, with_attach = json.loads(subprocess.run([NODE, str(d)], capture_output=True, text=True, timeout=120, check=True).stdout)
    assert "border:1px solid #fca5a5" in no_attach, "without attachment, a non-core reused prop is refused readably, same as a normal prop reference"
    assert 'id="a-cow"' in with_attach and 'href="#a-cow"' in with_attach and "border:1px solid #fca5a5" not in with_attach
