"""scene_stage / clipart: the scene-atom kit's atoms.

Their schema blocks are visibility:private and live in a2ui-private/private-atoms/; what is public is the renderer (the estate's
shared infra), the pack entry and the declared debt. These tests pin that split and prove the generated GAS files render in a bare
runtime (no DOM, no TextEncoder), the way Apps Script and the Worker run renderers.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
GAS = ROOT / "apps-script-surface" / "gas-wired-renderer"
FILES = sorted(GAS.glob("atoms_scene*.gs"))            # the estate concatenates atoms_*.gs in sorted order
NODE = shutil.which("node")


def test_the_pack_holds_exactly_the_two_scene_atoms_and_the_index_knows_it():
    packs = yaml.safe_load((ROOT / "atoms" / "atom-packs.yaml").read_text())
    assert packs["a2ui-scenes-v1"] == ["clipart", "scene_stage"]
    assert '"a2ui-scenes-v1": ("Scenes & clipart"' in (ROOT / "scripts" / "gen_catalog_index.py").read_text()


def test_the_schema_blocks_stay_private_and_the_debt_is_declared():
    schema_types = {b["type"] for b in yaml.safe_load((ROOT / "atoms" / "schema.yaml").read_text())["blocks"] if isinstance(b, dict)}
    assert not ({"scene_stage", "clipart"} & schema_types), "the definitions must live in a2ui-private, not the public schema"
    debt = yaml.safe_load((ROOT / "project.yaml").read_text())["known_debt"]["unregistered_atoms"]
    assert {"scene_stage", "clipart"} <= set(debt)


def test_generated_files_are_marked_and_split_engine_from_data():
    assert [f.name for f in FILES] == ["atoms_scene.gs", "atoms_scene_data.gs"]
    for f in FILES:
        assert f.read_text().startswith("// GENERATED by scene-atom/gen_scene_gs.py"), f.name
    engine, data = (f.read_text() for f in FILES)
    assert "_RENDERERS['scene_stage']" in engine and "_RENDERERS['clipart']" in engine
    assert "var SCENE_STAGE_DATA = " in data and "SCENE_STAGE_DATA" in engine
    for banned in ("import.meta", "fetch(", "document.", "window.", "localStorage", "require("):
        assert banned not in engine, banned


def test_python_static_renderer_degrades_visibly_and_escapes_payload_text():
    from renderers.web_article import _RENDERERS
    html = _RENDERERS["scene_stage"]({"type": "scene_stage", "preset": "data-centre", "title": "<script>alert(1)</script>"})
    assert "<script" not in html and "&lt;script&gt;" in html and "data-centre" in html and "MCP Apps" in html
    clip = _RENDERERS["clipart"]({"type": "clipart", "asset": "desk", "alt": 'a "desk" <b>'})
    assert "<b>" not in clip and "&quot;desk&quot;" in clip
    assert "clipart" in _RENDERERS["clipart"]({"type": "clipart"}), "even an empty block must not render nothing"


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_gas_files_render_scenes_in_a_bare_runtime_without_a_dom():
    js = r"""
    const vm = require('vm'), fs = require('fs'); const ctx = vm.createContext({});
    vm.runInContext('var _RENDERERS = {};', ctx);
    for (const f of JSON.parse(process.argv[1])) vm.runInContext(fs.readFileSync(f, 'utf8'), ctx);   // sorted, as the estate loads them
    const run = (src) => vm.runInContext(src, ctx);
    ctx.b1 = {type: 'scene_stage', preset: 'data-centre'};
    ctx.b2 = {type: 'scene_stage', preset: 'wind-farm', title: '<script>alert(1)</script>', theme: {time: 'night'}};
    ctx.b3 = {type: 'scene_stage', preset: 'no-such-place'};
    ctx.c1 = {type: 'clipart', asset: 'desk', scale: 2, flip: true, label: 'A desk'};
    ctx.c2 = {type: 'clipart', asset: 'not-a-prop'};
    const out = {textEncoder: run('typeof TextEncoder'), globals: Object.keys(ctx).filter(k => !/^[bc]\d$/.test(k)).sort(),
      renderers: Object.keys(ctx._RENDERERS).sort(),
      s1: run('_RENDERERS.scene_stage(b1)'), s2: run('_RENDERERS.scene_stage(b2)'), s3: run('_RENDERERS.scene_stage(b3)'),
      c1: run('_RENDERERS.clipart(c1)'), c2: run('_RENDERERS.clipart(c2)')};
    console.log(JSON.stringify(out));
    """
    r = subprocess.run([NODE, "-e", js, json.dumps([str(f) for f in FILES])], capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    o = json.loads(r.stdout)
    assert o["textEncoder"] == "undefined" and o["globals"] == ["SCENE_STAGE_DATA", "SceneStage", "_RENDERERS"]
    assert o["renderers"] == ["clipart", "scene_stage"]
    for k in ("s1", "s2"):
        assert o[k].startswith('<figure class="a2ui-scene"') and "<animate" in o[k] and "scene-atom:provenance" in o[k], k
        assert not re.search(r"<script|onload=|onclick=|javascript:", o[k]), f"{k}: the drawn scene must contain no script"
    assert "&lt;script&gt;" in o["s2"], "titles are escaped"
    prov = json.loads(re.search(r"<scene-atom:provenance[^>]*>(.*?)</scene-atom:provenance>", o["s1"]).group(1).replace("&quot;", '"').replace("&amp;", "&"))
    assert prov["assets"] and all(a["license"] == "MIT" and len(a["sha256"]) == 64 for a in prov["assets"])
    assert "spec.preset must be one of" in o["s3"] and "no-such-place" not in o["s3"].split("one of")[0]
    assert o["c1"].startswith('<figure class="a2ui-clipart"') and "scale(-1 1)" in o["c1"] and "A desk" in o["c1"]
    assert "stable registry ids" in o["c2"]


def test_the_mcp_apps_bundle_carries_the_engine_but_not_the_data():
    """Kept out on purpose so the bundle stays inside test_bundle_size_guard; the atoms then answer with a readable card there."""
    import sys
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    names = {f.name for f in g.renderer_files()}
    assert "atoms_scene.gs" in names and "atoms_scene_data.gs" not in names
    assert "not bundled on this surface" in (GAS / "atoms_scene.gs").read_text()
