"""scene_stage / clipart: the scene-atom kit's atoms.

Their schema blocks are visibility:private and live in a2ui-private/private-atoms/; what is public is the renderer (the estate's
shared infra), the pack entry and the declared debt. These tests pin that split and prove the generated GAS files render in a bare
runtime (no DOM, no TextEncoder), the way Apps Script and the Worker run renderers.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
GAS = ROOT / "apps-script-surface" / "gas-wired-renderer"
FILES = sorted(GAS.glob("atoms_scene*.gs"))            # the estate concatenates atoms_*.gs in sorted order
NODE = shutil.which("node")


def test_the_atoms_sit_in_the_effects_pack_and_no_new_dangling_catalogue_is_advertised():
    """A new extension pack would be advertised in the public index without a catalogue file (test_staging forbids growing that debt),
    so the scene atoms live in a2ui-effects-v1, whose selection text names them."""
    packs = yaml.safe_load((ROOT / "atoms" / "atom-packs.yaml").read_text())
    assert "a2ui-scenes-v1" not in packs
    assert {"clipart", "scene_stage"} <= set(packs["a2ui-effects-v1"])
    assert "scene_stage" in (ROOT / "scripts" / "gen_catalog_index.py").read_text()


def test_the_atoms_are_public_stable_and_no_longer_declared_debt():
    """Promoted 2026-09-20 (Curtis: publish them publicly): definitions live in the public schema, stable, no visibility flag."""
    blocks = {b["type"]: b for b in yaml.safe_load((ROOT / "atoms" / "schema.yaml").read_text())["blocks"] if isinstance(b, dict)}
    for t_ in ("scene_stage", "clipart"):
        assert t_ in blocks and blocks[t_].get("stage", "stable") == "stable" and "visibility" not in blocks[t_], t_
        assert blocks[t_]["source"]["license"] == "MIT"
        assert "mcp-apps" in blocks[t_]["surfaces"]["works_on"]
    debt = yaml.safe_load((ROOT / "project.yaml").read_text())["known_debt"]["unregistered_atoms"]
    assert not ({"scene_stage", "clipart"} & set(debt)), "no longer schema-absent"


def test_generated_files_are_marked_and_split_engine_from_data():
    assert [f.name for f in FILES] == ["atoms_scene.gs", "atoms_scene_data.gs"]
    for f in FILES:
        assert f.read_text().startswith("// GENERATED by scene-atom/gen_scene_gs.py"), f.name
    engine, data = (f.read_text() for f in FILES)
    assert "_RENDERERS['scene_stage']" in engine and "_RENDERERS['clipart']" in engine
    assert "var SCENE_STAGE_DATA = " in data and "SCENE_STAGE_DATA" in engine
    for banned in ("import.meta", "fetch(", "document.", "window.", "localStorage", "require("):
        assert banned not in engine, banned


def test_python_static_renderer_degrades_visibly_and_escapes_payload_text():
    from renderers.web_article import _RENDERERS
    html = _RENDERERS["scene_stage"]({"type": "scene_stage", "preset": "data-centre", "title": "<script>alert(1)</script>"})
    assert "<script" not in html and "&lt;script&gt;" in html and "data-centre" in html and "MCP Apps" in html
    clip = _RENDERERS["clipart"]({"type": "clipart", "asset": "desk", "alt": 'a "desk" <b>'})
    assert "<b>" not in clip and "&quot;desk&quot;" in clip
    assert "clipart" in _RENDERERS["clipart"]({"type": "clipart"}), "even an empty block must not render nothing"


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_gas_files_render_scenes_in_a_bare_runtime_without_a_dom():
    js = r"""
    const vm = require('vm'), fs = require('fs'); const ctx = vm.createContext({});
    vm.runInContext('var _RENDERERS = {};', ctx);
    for (const f of JSON.parse(process.argv[1])) vm.runInContext(fs.readFileSync(f, 'utf8'), ctx);   // sorted, as the estate loads them
    const run = (src) => vm.runInContext(src, ctx);
    ctx.b1 = {type: 'scene_stage', preset: 'data-centre'};
    ctx.b2 = {type: 'scene_stage', preset: 'wind-farm', title: '<script>alert(1)</script>', theme: {time: 'night'}};
    ctx.b3 = {type: 'scene_stage', preset: 'no-such-place'};
    ctx.c1 = {type: 'clipart', asset: 'desk', scale: 2, flip: true, label: 'A desk'};
    ctx.c2 = {type: 'clipart', asset: 'not-a-prop'};
    const out = {textEncoder: run('typeof TextEncoder'), globals: Object.keys(ctx).filter(k => !/^[bc]\d$/.test(k)).sort(),
      renderers: Object.keys(ctx._RENDERERS).sort(),
      s1: run('_RENDERERS.scene_stage(b1)'), s2: run('_RENDERERS.scene_stage(b2)'), s3: run('_RENDERERS.scene_stage(b3)'),
      c1: run('_RENDERERS.clipart(c1)'), c2: run('_RENDERERS.clipart(c2)')};
    console.log(JSON.stringify(out));
    """
    r = subprocess.run([NODE, "-e", js, json.dumps([str(f) for f in FILES])], capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    o = json.loads(r.stdout)
    assert o["textEncoder"] == "undefined" and o["globals"] == ["SCENE_STAGE_DATA", "SceneStage", "_RENDERERS"]
    assert o["renderers"] == ["clipart", "scene_stage"]
    for k in ("s1", "s2"):
        assert o[k].startswith('<figure class="a2ui-scene"') and "<animate" in o[k] and "scene-atom:provenance" in o[k], k
        assert not re.search(r"<script|onload=|onclick=|javascript:", o[k]), f"{k}: the drawn scene must contain no script"
    assert "&lt;script&gt;" in o["s2"], "titles are escaped"
    prov = json.loads(re.search(r"<scene-atom:provenance[^>]*>(.*?)</scene-atom:provenance>", o["s1"]).group(1).replace("&quot;", '"').replace("&amp;", "&"))
    assert prov["assets"] and all(a["license"] == "MIT" and len(a["sha256"]) == 64 for a in prov["assets"])
    assert "spec.preset must be one of" in o["s3"] and "no-such-place" not in o["s3"].split("one of")[0]
    assert o["c1"].startswith('<figure class="a2ui-clipart"') and "scale(-1 1)" in o["c1"] and "A desk" in o["c1"]
    assert "stable registry ids" in o["c2"]


def test_the_mcp_apps_bundle_carries_the_engine_and_the_data():
    """Bundled since 2026-09-20 (size-guard ceiling raised with Curtis's go-ahead). If a host rejects the size, the data file goes back
    into EXCLUDE_FILES and the atoms answer with a readable card there (the engine still says so, see the other test)."""
    import sys
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    names = {f.name for f in g.renderer_files()}
    assert "atoms_scene.gs" in names and "atoms_scene_data.gs" in names
    assert "not bundled on this surface" in (GAS / "atoms_scene.gs").read_text()


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_a_layout_without_scenery_actors_or_camera_still_renders_and_a_bad_one_says_what_is_wrong():
    """Found by a blind LLM-style test: a model writing a layout in full may leave out actors/scenery/camera; those default."""
    js = r"""
    const vm = require('vm'), fs = require('fs'); const ctx = vm.createContext({}); vm.runInContext('var _RENDERERS = {};', ctx);
    for (const f of JSON.parse(process.argv[1])) vm.runInContext(fs.readFileSync(f, 'utf8'), ctx);
    ctx.ok = {type: 'scene_stage', backdrop: 'interior-office', ground: 'concrete', stage: {width: 1400, zoom: 1300, focus_y: -260}, scenery: [{prop: 'desk', x: 600}]};
    ctx.bare = {type: 'scene_stage', backdrop: 'sky-hills', ground: 'grass', stage: {width: 1400, zoom: 1300, focus_y: -260}};
    ctx.bad = {type: 'scene_stage', backdrop: 'sky-hills', stage: {width: 1400, zoom: 1300, focus_y: -260}};
    console.log(JSON.stringify(['ok', 'bare', 'bad'].map(k => vm.runInContext('_RENDERERS.scene_stage(' + k + ')', ctx))));
    """
    r = subprocess.run([NODE, "-e", js, json.dumps([str(f) for f in FILES])], capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stderr
    ok, bare, bad = json.loads(r.stdout)
    assert ok.startswith("<figure") and bare.startswith("<figure") and "<animate" in ok
    assert "spec.ground must be one of" in bad


@pytest.mark.skipif(NODE is None, reason="node is not installed")
def test_the_mcp_apps_bundle_itself_renders_scenes_and_clipart():
    """Build the real MCP Apps bundle in memory, run its DOM-free core in Node, and render both atoms through renderAtoms."""
    import sys
    import tempfile
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_mcp_apps_bundle as g
    bundle = g.build_bundle()
    core = [b for b in re.findall(r"<script>\n(.*?)\n</script>", bundle, re.S) if "a2ui-core" in b[:300]][0]
    blocks = [{"type": "scene_stage", "preset": "wind-farm", "theme": {"time": "dusk"}}, {"type": "scene_stage", "preset": "no-such"},
              {"type": "clipart", "asset": "wind-turbine", "scale": 1.5, "label": "A turbine"}]
    with tempfile.TemporaryDirectory() as td:
        driver = Path(td) / "driver.js"
        driver.write_text("global.window = global;\n" + core + "\nvar out = " + json.dumps(blocks) +
                          ".map(function (b) { return renderAtoms([b], {theme: 'light'}); });\nconsole.log(JSON.stringify(out));\n")
        proc = subprocess.run([NODE, str(driver)], capture_output=True, text=True, timeout=120)
    assert proc.returncode == 0, proc.stderr[-2000:]
    scene, bad, clip = json.loads(proc.stdout)
    assert 'class="a2ui-scene"' in scene and "<animate" in scene and "scene-atom:provenance" in scene, scene[:300]
    assert "not bundled on this surface" not in scene and "spec.preset must be one of" in bad
    assert 'class="a2ui-clipart"' in clip and "A turbine" in clip
    assert len(bundle) < 3_200_000


def test_published_scene_assets_match_the_data_the_renderer_embeds():
    """public/catalogue/assets-index-v1.json and scene-spec.schema.json are generated by the kit (diagram-studio/scene-atom) and copied
    here; they must describe exactly what atoms_scene_data.gs embeds, or an agent is offered props the renderer refuses."""
    idx = json.loads((ROOT / "public" / "catalogue" / "assets-index-v1.json").read_text())
    data_src = (GAS / "atoms_scene_data.gs").read_text()
    data = json.loads(data_src.split("var SCENE_STAGE_DATA = ", 1)[1].rsplit(";", 1)[0])
    assert idx["registry_sha256"] == data["registry_sha256"], "index and embedded data come from different registries: recopy from the kit"
    embedded = {e["id"] for e in data["entries"]}
    assert {a["id"] for a in idx["assets"]} <= embedded and all(a["stage"] == "stable" for a in idx["assets"])
    assert {p["id"] for p in idx["presets"]} == set(data["layouts"]["layouts"])
    schema = json.loads((ROOT / "public" / "catalogue" / "scene-spec.schema.json").read_text())
    assert set(schema["properties"]["preset"]["enum"]) == set(data["layouts"]["layouts"])
    assert set(schema["properties"]["scenery"]["items"]["properties"]["prop"]["enum"]) >= {a["id"] for a in idx["assets"]}
