#!/usr/bin/env python3
"""styles/gcp.catalogue.json (mined by mine_gcp.py) -> the Worker's data module. Names, categories, colours and stencil NAMES only: no artwork.
  python gen_worker_gcp.py > /path/to/a2ui-private/mcp-worker/src/diagram/gcp-catalogue.js"""
import json
from pathlib import Path
d = json.loads((Path(__file__).parent / 'styles/gcp.catalogue.json').read_text())
out = {'source': d['source'], 'categories': d['categories'], 'core': d['core_products'], 'zone_style': d['zone_style'],
       'zones': [{'name': z['name'].replace('<sup>', '').replace('</sup>', ''), 'fill': z['fill']} for z in d['zones']], 'paths': d['paths']}
print("// Generated by a2ui-catalogue/tools/diagram/gen_worker_gcp.py from draw.io's GCP sidebars (Apache-2.0, jgraph/drawio). Names, categories, colours and stencil names, not artwork.")
print("// core: the products draw.io draws from a named stencil (the only ones restyled). Do not edit by hand: re-run mine_gcp.py and gen_worker_gcp.py.")
print('export const GCP = ' + json.dumps(out, separators=(',', ':'), ensure_ascii=False) + ';')
