#!/usr/bin/env python3
"""styles/aws.catalogue.json (mined by mine_aws.py) -> the Worker's data module. Names, categories, colours and stencil NAMES only: no artwork.
  python gen_worker_data.py > /path/to/a2ui-private/mcp-worker/src/diagram/aws-catalogue.js"""
import json, sys
from pathlib import Path
d = json.loads((Path(__file__).parent / 'styles/aws.catalogue.json').read_text())
out = {'source': d['source'], 'categories': {k: {'fill': c['fill'], 'base': c['style_base'], 'services': [[s['icon'], s['name'], s['tag']] for s in c['services']]} for k, c in d['categories'].items()},
       'groups': [{'name': g['name'], 'style': g['style']} for g in d['groups']]}
print('// Generated by a2ui-catalogue/tools/diagram/gen_worker_data.py from draw.io\'s AWS sidebar (Apache-2.0, jgraph/drawio). Names, categories, colours and stencil names, not artwork.')
print('// Services: [stencil id, name, search tag]. Do not edit by hand: re-run mine_aws.py and gen_worker_data.py.')
print('export const AWS = ' + json.dumps(out, separators=(',', ':'), ensure_ascii=False) + ';')
