// GENERATED by scripts/gen_design_tokens.py from atoms/design-tokens.yaml -- do not edit; change the YAML and re-run.
var _TOKEN_ORDER = [["radius", "radius"], ["radius_sm", "radius-sm"], ["border_color", "border"], ["border_soft_color", "border-soft"], ["surface_color", "surface"], ["surface_muted_color", "surface-muted"], ["text_color", "text"], ["muted_color", "muted"], ["faint_color", "faint"], ["shadow", "shadow"]];
var _TOKEN_PRESETS = {
  "modern": {
    "radius": "12px",
    "radius-sm": "6px",
    "border": "#eaeaea",
    "border-soft": "#f1f1f1",
    "surface": "#ffffff",
    "surface-muted": "#fafafa",
    "text": "#171717",
    "muted": "#666666",
    "faint": "#8f8f8f",
    "shadow": "0 1px 2px rgba(0,0,0,.04),0 4px 12px rgba(0,0,0,.04)"
  }
};
var _TOKEN_SAFE = /^[#A-Za-z0-9_ .,()%\/-]{1,120}$/;

// `--a2ui-<name>:<value>;` for every token the palette block sets, in declared
// order. Explicit fields beat the preset; unsafe values are dropped.
function _tokenCss(b) {
  var key = b.preset;
  var preset = (typeof key === 'string' && Object.prototype.hasOwnProperty.call(_TOKEN_PRESETS, key)) ? _TOKEN_PRESETS[key] : {};
  var out = '';
  for (var i = 0; i < _TOKEN_ORDER.length; i++) {
    var field = _TOKEN_ORDER[i][0], name = _TOKEN_ORDER[i][1];
    var v = b[field];
    if (!(typeof v === 'string' && v)) v = preset[name];
    if (typeof v === 'string' && _TOKEN_SAFE.test(v)) out += '--a2ui-' + name + ':' + v + ';';
  }
  return out;
}
