// GENERATED by scene-atom/gen_scene_gs.py from scene.js + registry.json + layouts.json. Do not edit.
// Classic script for the estate's renderer concatenation (GAS deployments, MCP Apps bundle, Worker module).
// One global: SceneStage. Registers _RENDERERS.scene_stage and _RENDERERS.clipart. DOM-free, fetch-free.
var SceneStage = (function () {
'use strict';
/* scene-atom: theme prompt -> validated scene spec -> pan/zoom/animated SVG.
 *
 * Pipeline (every arrow is a checked boundary):
 *   prompt --interpretPrompt()--> spec --validateSpec()--> spec'
 *   registry.json --verifyRegistry()--> trusted props
 *   (spec', props) --buildScene()--> standalone animated SVG + provenance
 *
 * Nothing the user or an LLM types ever reaches the SVG as markup: the spec is
 * strictly typed data, artwork comes only from the hash-verified registry, and
 * every string that is emitted is escaped or numeric.
 */

const RENDERER_VERSION = '1.0.0';
const SVG_NS = 'http://www.w3.org/2000/svg';

/* ------------------------------------------------------------------ utils */
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
const lerp = (a, b, t) => a + (b - a) * t;
const smooth = (t) => { t = clamp(t, 0, 1); return t * t * (3 - 2 * t); };
const fmt = (n) => String(Math.round(n * 10) / 10);
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const hex2rgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const mix = (a, b, t) => {
  const A = hex2rgb(a), B = hex2rgb(b);
  return '#' + A.map((v, i) => Math.round(lerp(v, B[i], t)).toString(16).padStart(2, '0')).join('');
};

/* Pure-JS SHA-256 so hash verification works on plain-http LAN origins where
 * crypto.subtle is unavailable. Verified against hashlib in the test-suite. */
/* UTF-8 without TextEncoder (Apps Script's V8 and Workers-style runtimes may lack it). */
function utf8Bytes(str) {
  const out = [];
  for (let i = 0; i < str.length; i++) {
    let c = str.charCodeAt(i);
    if (c >= 0xd800 && c < 0xdc00 && i + 1 < str.length) { const d = str.charCodeAt(i + 1); if (d >= 0xdc00 && d < 0xe000) { c = 0x10000 + ((c - 0xd800) << 10) + (d - 0xdc00); i++; } }
    if (c < 0x80) out.push(c);
    else if (c < 0x800) out.push(0xc0 | (c >> 6), 0x80 | (c & 63));
    else if (c < 0x10000) out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63));
    else out.push(0xf0 | (c >> 18), 0x80 | ((c >> 12) & 63), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63));
  }
  return Uint8Array.from(out);
}

function sha256Hex(str) {
  const bytes = typeof TextEncoder !== 'undefined' ? new TextEncoder().encode(str) : utf8Bytes(str);
  const primes = [];
  for (let n = 2; primes.length < 64; n++) if (primes.every((p) => n % p)) primes.push(n);
  const frac = (x) => Math.floor((x - Math.floor(x)) * 4294967296);
  const K = primes.map((p) => frac(Math.cbrt(p)));
  const H = primes.slice(0, 8).map((p) => frac(Math.sqrt(p)));
  const l = bytes.length;
  const pl = Math.ceil((l + 9) / 64) * 64;
  const buf = new Uint8Array(pl);
  buf.set(bytes);
  buf[l] = 0x80;
  const view = new DataView(buf.buffer);
  view.setUint32(pl - 8, Math.floor((l * 8) / 4294967296));
  view.setUint32(pl - 4, (l * 8) >>> 0);
  const rotr = (x, n) => (x >>> n) | (x << (32 - n));
  const w = new Uint32Array(64);
  for (let off = 0; off < pl; off += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getUint32(off + i * 4);
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >>> 3);
      const s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >>> 10);
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) | 0;
    }
    let [a, b, c, d, e, f, g, h] = H;
    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const t1 = (h + S1 + ((e & f) ^ (~e & g)) + K[i] + w[i]) | 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const t2 = (S0 + ((a & b) ^ (a & c) ^ (b & c))) | 0;
      h = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0;
    }
    H[0] = (H[0] + a) | 0; H[1] = (H[1] + b) | 0; H[2] = (H[2] + c) | 0; H[3] = (H[3] + d) | 0;
    H[4] = (H[4] + e) | 0; H[5] = (H[5] + f) | 0; H[6] = (H[6] + g) | 0; H[7] = (H[7] + h) | 0;
  }
  return H.map((v) => (v >>> 0).toString(16).padStart(8, '0')).join('');
}

/* --------------------------------------------------- registry verification */
const TOKEN_RE = /\{\{([a-z]+)\}\}/g;
const BAD_VALUE_RE = /(javascript|data|vbscript)\s*:|expression\s*\(|@import|</i;

function svgProblems(text, allow) {
  const doc = (function () { throw new Error('SVG structure checks need a DOM; this build verifies sha256 and origin only'); })();
  if (doc.getElementsByTagName('parsererror').length) return ['not well-formed XML'];
  const problems = [];
  const root = doc.documentElement;
  if (root.namespaceURI !== SVG_NS || root.localName !== 'svg') problems.push('root must be <svg>');
  if (!root.getAttribute('viewBox')) problems.push('root <svg> needs a viewBox');
  for (const m of text.matchAll(TOKEN_RE)) if (!allow.tokens.includes(m[1])) problems.push(`unknown token {{${m[1]}}}`);
  if ((text.match(/\{\{/g) || []).length !== [...text.matchAll(TOKEN_RE)].length) problems.push('malformed {{token}}');
  const all = [root, ...root.querySelectorAll('*')];
  for (const el of all) {
    if (el.namespaceURI !== SVG_NS || !allow.elements.includes(el.localName)) problems.push(`element <${el.localName}> not allowed`);
    for (const a of el.attributes) {
      const isRootSpecial = el === root && (a.name === 'xmlns' || a.name === 'viewBox');
      if (!isRootSpecial && (a.namespaceURI || !allow.attributes.includes(a.localName))) {
        problems.push(`attribute ${a.name} on <${el.localName}> not allowed`);
        continue;
      }
      if (BAD_VALUE_RE.test(a.value)) problems.push(`unsafe value in ${a.name}`);
      for (const u of a.value.matchAll(/url\(([^)]*)\)/gi)) if (!u[1].trim().startsWith('#')) problems.push(`external url() in ${a.name}`);
    }
  }
  return problems;
}

/** Re-verify the ledger in the browser: hash, licence, origin fields, SVG safety. Throws on any failure.
 *  `skipSvgStructure` exists only for DOM-less tooling (Node CI, golden tests): the sha256 and origin checks still run, and the
 *  structural allowlist pass was done by build_registry.py when the hash was minted. A DOM-less production renderer needs a real XML parser instead. */
function verifyRegistry(reg, allow, { skipSvgStructure = false } = {}) {
  const errs = [];
  const seen = new Set();
  if (!reg || reg.schema !== 1 || !Array.isArray(reg.entries)) throw new Error('registry: bad schema');
  for (const e of reg.entries) {
    const tag = `registry[${e && e.id}]`;
    if (!e || !/^[a-z0-9-]+$/.test(e.id) || seen.has(e.id)) { errs.push(`${tag}: bad or duplicate id`); continue; }
    seen.add(e.id);
    if (typeof e.svg !== 'string') { errs.push(`${tag}: missing svg`); continue; }
    if (sha256Hex(e.svg) !== e.sha256) errs.push(`${tag}: sha256 mismatch (artwork changed without a provenance update)`);
    const o = e.origin || {};
    if (!allow.licenses.includes(o.license)) errs.push(`${tag}: licence ${o.license} not allowed`);
    if (!o.author) errs.push(`${tag}: no author`);
    if (o.type === 'third-party') {
      if (!/^https:\/\//.test(o.source_url || '')) errs.push(`${tag}: third-party art needs https source_url`);
      if (!o.retrieved) errs.push(`${tag}: third-party art needs retrieved date`);
      if (allow.attribution_required.includes(o.license) && !o.attribution) errs.push(`${tag}: licence requires attribution`);
    } else if (o.type !== 'original') errs.push(`${tag}: origin.type invalid`);
    if (!skipSvgStructure) errs.push(...svgProblems(e.svg, allow).map((p) => `${tag}: ${p}`));
    const tokenMap = (map, where) => {
      for (const [k, v] of Object.entries(map || {})) {
        if (!allow.tokens.includes(k)) errs.push(`${tag}: ${where} has unknown token ${k}`);
        if (typeof v !== 'string' || !new RegExp(allow.token_value_pattern).test(v)) errs.push(`${tag}: ${where} token ${k} must be #rrggbb or 0/1`);
      }
    };
    if (!allow.categories.includes(e.category)) errs.push(`${tag}: category ${e.category} is not allowed`);
    if (!Array.isArray(e.tags) || e.tags.length < 1 || e.tags.length > 10 || new Set(e.tags).size !== e.tags.length || !e.tags.every((t) => typeof t === 'string' && /^[a-z0-9-]{2,24}$/.test(t))) errs.push(`${tag}: tags must be 1-10 distinct lowercase words`);
    if ('library' in e && e.library !== true) errs.push(`${tag}: library, when present, must be true`);
    if ('promoted' in e && (e.promoted !== true || e.library !== true)) errs.push(`${tag}: promoted, when present, must be true and only applies to library props`);
    tokenMap(e.tokens, 'tokens');
    for (const [name, map] of Object.entries(e.variants || {})) {
      if (!/^[a-z0-9-]+$/.test(name)) errs.push(`${tag}: bad variant name ${name}`);
      tokenMap(map, `variant ${name}`);
      for (const k of Object.keys(map)) if (!e.svg.includes(`{{${k}}}`)) errs.push(`${tag}: variant ${name} sets ${k}, which this prop never uses`);
    }
    const resolvable = new Set([...allow.palette_tokens, ...Object.keys(e.tokens || {})]);
    for (const m of e.svg.matchAll(TOKEN_RE)) if (!resolvable.has(m[1])) errs.push(`${tag}: token {{${m[1]}}} has no default`);
  }
  for (const e of reg.entries) for (const r of e.requires || []) if (!seen.has(r)) errs.push(`registry[${e.id}]: requires unknown ${r}`);
  if (errs.length) throw new Error('Registry verification failed:\n' + errs.join('\n'));
  return true;
}


/** Pure half of loadAtom (no fetch, no DOM): verifies the registry and returns the atom. Used by Node tooling and renderers. */
function atomFromTexts(regText, allowText, layoutsText, opts) {
  const registry = JSON.parse(regText);
  const allow = JSON.parse(allowText);
  verifyRegistry(registry, allow, opts);
  const byId = Object.fromEntries(registry.entries.map((e) => [e.id, e]));
  const layouts = JSON.parse(layoutsText);          // presets only supply defaults; every spec built from them is still fully validated
  return { registry, allow, byId, layouts, registrySha256: sha256Hex(regText) };
}

/**
 * The smallest self-contained input a renderer needs for one spec: only the registry entries the scene draws (with their
 * own sha256, so they are re-verified), the allowlist, and the one layout the spec names. registry_sha256 is the FULL
 * registry's hash, so provenance is identical to a build from the whole kit.
 */
function bundleFor(specIn, atom) {
  const r = buildScene(specIn, atom);
  const ids = new Set();
  const add = (id) => { if (ids.has(id)) return; ids.add(id); for (const q of atom.byId[id].requires || []) add(q); };
  r.provenance.assets.forEach((a) => add(a.id));
  const preset = specIn && specIn.preset;
  return {
    schema: 1, registry_sha256: atom.registrySha256, allow: atom.allow,
    entries: atom.registry.entries.filter((e) => ids.has(e.id)),
    layouts: { version: 1, layouts: preset && atom.layouts.layouts[preset] ? { [preset]: atom.layouts.layouts[preset] } : {} },
  };
}

/** Rebuild an atom from a bundleFor() result; every entry is verified exactly as in the full registry. */
function atomFromBundle(b, opts) {
  const registry = { schema: 1, entries: b.entries };
  verifyRegistry(registry, b.allow, opts);
  return { registry, allow: b.allow, byId: Object.fromEntries(registry.entries.map((e) => [e.id, e])), layouts: b.layouts, registrySha256: b.registry_sha256 };
}

/* ------------------------------------------------------------- palettes */
const PALETTES = {
  day:   { skyTop: '#5fa8e6', skyBot: '#d3ebf8', body: '#f7f7f4', dark: '#23303a', wing: '#c9d1d8', glass: '#79b3c9', window: '#dbeaf2', structure: '#ebe4d6', roof: '#b3ab9c', beacon: '#e64a3b', cloud: '#ffffff', sun: '#ffe58a', moon: '#f4f1e6', leaf: '#3f7d4b', trunk: '#7a5a3a', grass: '#86b46c', verge: '#6f9a58', runway: '#4a5057', hillFar: '#a9c8b0', hillNear: '#8db592', sea: '#5aa6c8', lights: false, stars: false, celestial: 'sun', sunPos: [250, -140] },
  dawn:  { skyTop: '#55679f', skyBot: '#f5b48f', body: '#f5f0ea', dark: '#2a2f42', wing: '#c5c3cc', glass: '#8aa3c4', window: '#ffe9a8', structure: '#e6d9cf', roof: '#a99fa0', beacon: '#e64a3b', cloud: '#ffd9c8', sun: '#ffd08a', moon: '#f4f1e6', leaf: '#4b7256', trunk: '#6d5340', grass: '#7c9a6a', verge: '#66855a', runway: '#474b58', hillFar: '#8d8fb5', hillNear: '#6f7f9b', sea: '#7d9fc8', lights: true, stars: false, celestial: 'sun', sunPos: [-330, 30] },
  dusk:  { skyTop: '#2f2a5c', skyBot: '#ff8f5c', body: '#f3e9e4', dark: '#221f38', wing: '#bdb5c2', glass: '#7f8cb8', window: '#ffd98a', structure: '#d8c5c0', roof: '#8d7f8a', beacon: '#ff5a48', cloud: '#ffb08a', sun: '#ffb46a', moon: '#f4f1e6', leaf: '#3f5a52', trunk: '#5b4638', grass: '#6b7f5c', verge: '#586c4f', runway: '#3d3f4d', hillFar: '#6a5f92', hillNear: '#4d4b79', sea: '#6c74b0', lights: true, stars: false, celestial: 'sun', sunPos: [330, 34] },
  night: { skyTop: '#060a1e', skyBot: '#1b2652', body: '#dfe3ea', dark: '#0f1524', wing: '#9aa2b4', glass: '#4b6088', window: '#ffd66b', structure: '#39425c', roof: '#232a40', beacon: '#ff5a48', cloud: '#2c3760', sun: '#ffe58a', moon: '#f1f0e8', leaf: '#1f3a3a', trunk: '#3a2f2a', grass: '#22322f', verge: '#1a2825', runway: '#1e2126', hillFar: '#1a2444', hillNear: '#131b36', sea: '#182a4c', lights: true, stars: true, celestial: 'moon', sunPos: [260, -130] },
};
const LIGHT_TIMES = new Set(['dawn', 'dusk', 'night']);

function paletteFor(spec) {
  const p = { ...PALETTES[spec.theme.time], livery: spec.aircraft ? spec.aircraft.livery : spec.accent };
  if (spec.theme.weather === 'overcast') {
    const night = spec.theme.time === 'night';
    p.skyTop = mix(p.skyTop, night ? '#101522' : '#66707c', 0.6);
    p.skyBot = mix(p.skyBot, night ? '#1d2436' : '#aab2ba', 0.6);
    p.cloud = mix(p.cloud, night ? '#232a3c' : '#98a1ab', 0.55);
  }
  return p;
}

/* -------------------------------------------------- prompt interpretation */
const COLOURS = { red: '#d64541', orange: '#ee7b30', yellow: '#f2c230', green: '#3f9b5a', teal: '#1f9d9a', blue: '#2f6fd6', navy: '#23366b', purple: '#7a4fc4', pink: '#e85d9b', black: '#2b2f36', gold: '#d4a72c' };
const NOUN = '(?:jet|plane|airliner|aircraft|airplane|rocket|robot|workshop|machine)';
const SCENES = ['takeoff', 'landing', 'orchestrator', 'launch', 'workshop', 'stage'];
const STAGE_BACKDROPS = ['sky-city', 'sky-hills', 'sky-sea', 'sky-mountains', 'sky-desert', 'sky-arctic', 'sky-flat', 'space', 'interior-office', 'interior-industrial', 'interior-lab', 'interior-civic', 'interior-home', 'interior-dark'];
const STAGE_GROUNDS = ['grass', 'road', 'sand', 'snow', 'concrete', 'wood', 'water', 'none'];
const STAGE_MOTIONS = ['walk', 'ride', 'drive', 'fly', 'hover', 'orbit'];
/* Numeric limits of the stage spec: the validator, the JSON Schema (gen_spec_schema.mjs) and the LLM prompt all read this, so they cannot drift. */
const STAGE_LIMITS = {
  title: 80, seed: [0, 4294967295], duration: [6, 40], scenery: 80, actors: 30,
  width: [600, 4000], zoom: [500, 3200], focus_y: [-800, 200],
  scenery_x: [-600, 4600], scenery_y: [-1000, 300], scale: [0.2, 5],
  actor_x: [-800, 4800], actor_y: [-1000, 300], period: [3, 120], phase: [0, 1], ry: [0, 800],
  sketch_elements: 40, sketches: 8, sketch_chars: 4096, sketch_total: 24000,
};
const INTERIOR = ['workshop'];                       // scenes with no aircraft: an actors list instead
const MODES = { aircraft: ['follow', 'cinematic', 'wide'], interior: ['static', 'pan', 'push-in'] };
const WORKSHOP_ACTORS = [
  { prop: 'mini-robot', motion: 'walk', x0: 200, x1: 1000, y: 0, period: 18, phase: 0 },
  { prop: 'mini-robot', motion: 'walk', x0: 1500, x1: 1900, y: 0, period: 14, phase: 0.4 },
  { prop: 'crate', motion: 'ride', x0: 1070, x1: 1430, y: -50, period: 9, phase: 0 },
  { prop: 'crate', motion: 'ride', x0: 1070, x1: 1430, y: -50, period: 9, phase: 0.33 },
  { prop: 'crate', motion: 'ride', x0: 1070, x1: 1430, y: -50, period: 9, phase: 0.66 },
];
const SCENE_DEFAULTS = {
  takeoff: [{ prop: 'terminal-building', x: 220 }, { prop: 'control-tower', x: 500 }, { prop: 'windsock', x: 1080 }],
  landing: [{ prop: 'windsock', x: 300 }, { prop: 'papi-lights', x: 380 }, { prop: 'control-tower', x: 900 }, { prop: 'hangar', x: 1800 }],
  launch: [
    { prop: 'searchlight-beam', x: 250, y: 8 }, { prop: 'lightning-mast', x: 360, y: 8 }, { prop: 'launch-tower', x: 470, y: 8 },
    { prop: 'launch-pad', x: 600, y: 12 }, { prop: 'gantry-arm', x: 506, y: -186 }, { prop: 'lightning-mast', x: 850, y: 8 },
    { prop: 'control-bunker', x: 960, y: 8 }, { prop: 'searchlight-beam', x: 1080, y: 8 },
  ],
  workshop: [
    { prop: 'tool-bench', x: 150 }, { prop: 'pipe-run', x: 330, y: -330 }, { prop: 'gauge', x: 500, y: -250 }, { prop: 'tank', x: 630 },
    { prop: 'valve-wheel', x: 740, y: -100 }, { prop: 'gear-train', x: 830, y: -250 }, { prop: 'conveyor-belt', x: 1250 },
    { prop: 'robot-arm', x: 1130 }, { prop: 'status-led', x: 1540 }, { prop: 'control-panel', x: 1620 }, { prop: 'status-led', x: 1710 },
  ],
  orchestrator: [
    { prop: 'terminal-building', x: 200 }, { prop: 'mini-robot', x: 110, y: -108 }, { prop: 'radar-screen', x: 520 },
    { prop: 'control-tower', x: 700 }, { prop: 'mini-robot', x: 610 }, { prop: 'mini-robot', x: 800 },
    { prop: 'radar-dish', x: 950 }, { prop: 'windsock', x: 1150 },
  ],
};

/** Pick the layout preset whose keywords best match the text (null if none). */
function matchPreset(t, layouts) {
  let best = null, bestScore = 0;
  for (const id of Object.keys(layouts || {}).sort()) {
    let score = 0;
    for (const kw of layouts[id].keywords || []) if (new RegExp('\\b' + kw).test(t)) score += kw.length;
    if (score > bestScore) { best = id; bestScore = score; }
  }
  return best;
}

function interpretPrompt(text, layoutsFile) {
  const raw = String(text || '').slice(0, 400);
  const t = raw.toLowerCase();
  const notes = [];
  const pick = (re) => { const m = t.match(re); return m ? m[0] : null; };
  const set = (field, value, why) => notes.push({ field, value: String(value), why });

  let time = 'day', why;
  if ((why = pick(/\bnight\w*|midnight|moonlit|after dark\b/))) time = 'night';
  else if ((why = pick(/\bdusk\b|sunset|evening|twilight/))) time = 'dusk';
  else if ((why = pick(/\bdawn\b|sunrise|morning|daybreak/))) time = 'dawn';
  else if ((why = pick(/\bnoon\b|midday|afternoon|\bday(?:time)?\b|sunny/))) time = 'day';
  set('time of day', time, why ? `matched "${why}"` : 'default');
  const timeMatched = Boolean(why);

  let weather = 'clear';
  if ((why = pick(/overcast|storm\w*|rain\w*|gr[ae]y sky|gloomy/))) weather = 'overcast';
  else if ((why = pick(/cloud\w*|cumulus/))) weather = 'cloudy';
  set('weather', weather, why ? `matched "${why}"` : 'default');

  let setting = 'countryside';
  if ((why = pick(/island|coast\w*|beach|tropic\w*|\bsea\b|ocean|seaside/))) setting = 'coast';
  set('setting', setting, why ? `matched "${why}"` : 'default');

  let livery = '#2f6fd6', liveryMatched = false;
  const named = t.match(new RegExp(`\\b(${Object.keys(COLOURS).join('|')})\\b(?:\\s+\\w+){0,2}?\\s+${NOUN}\\b`));
  const hex = raw.match(/#[0-9a-fA-F]{6}\b/);
  if (named) { livery = COLOURS[named[1]]; liveryMatched = true; set('livery', livery, `"${named[1]}" before the aircraft noun`); }
  else if (hex) { livery = hex[0].toLowerCase(); liveryMatched = true; set('livery', livery, 'hex colour in prompt'); }
  else set('livery', livery, 'default');

  let duration = 16;
  if ((why = pick(/\b(?:slow\w*|leisurely|lazy)\b/))) duration = 22;
  else if ((why = pick(/\b(?:fast|quick\w*|snappy|brisk)\b/))) duration = 10;
  set('duration', duration + ' s', why ? `matched "${why}"` : 'default');

  let climb = 1;
  if ((why = pick(/\b(?:steep\w*|dramatic|aggressive)\b/))) climb = 1.4;
  else if ((why = pick(/\b(?:gentle|shallow|gradual)\b/))) climb = 0.7;
  set('climb', climb, why ? `matched "${why}"` : 'default');

  /* Order: an explicit workshop, then a ready-made stage layout (unless the prompt is about aircraft), then the looser scene words. */
  let scene = 'takeoff', preset = null;
  const aircraftWords = /\b(?:jet|plane|airliner|aircraft|airplane|airport|runway|take-?off|rocket|spacecraft)\b/.test(t);
  if ((why = pick(/workshop|tool[- ]?bench|machine shop/))) scene = 'workshop';
  else if (!aircraftWords && layoutsFile && layoutsFile.layouts && (preset = matchPreset(t, layoutsFile.layouts))) { scene = 'stage'; why = `layout "${preset}"`; }
  else if ((why = pick(/conveyor|assembly line|\brobots?\b/))) scene = 'workshop';
  else if ((why = pick(/orchestrat\w*|air[- ]traffic|\batc\b|multi[- ]agent|\bagents?\b/))) scene = 'orchestrator';
  else if ((why = pick(/rocket|launch\w*|lift[- ]?off|blast[- ]?off|spacecraft/))) scene = 'launch';
  else if ((why = pick(/\bland\w*|touch(?:es|ing)?[- ]?down|arriv\w*|approach\w*|coming in/))) scene = 'landing';
  set('scene', scene, why ? `matched ${why.startsWith('layout') ? why : `"${why}"`}` : 'default (take-off)');
  const interior = INTERIOR.includes(scene) || scene === 'stage';

  let mode = interior ? 'push-in' : 'cinematic';
  if (interior) {
    if ((why = pick(/\b(?:static|still|locked|wide|overview)\b/))) mode = 'static';
    else if ((why = pick(/\b(?:pan\w*|tour|drift\w*|follow\w*|tracking)\b/))) mode = 'pan';
    else why = null;
  } else if ((why = pick(/\bwide\b|overview|establishing/))) mode = 'wide';
  else if ((why = pick(/\bfollow\w*|tracking|chase|close[- ]?up/))) mode = 'follow';
  else if ((why = pick(/cinematic|movie|film/))) mode = 'cinematic';
  set('camera', mode, why ? `matched "${why}"` : 'default');

  const stageWhy = scene === 'stage' ? why : null;
  let code = 'AVN';
  if (!interior) {
    const codeM = raw.match(/\b(?:from|at|out of|departing)\s+([A-Z]{3,4})\b/);
    if (codeM) code = codeM[1];
    set('airport code', code, codeM ? `"${codeM[0]}"` : 'default');
  }

  if (scene === 'stage') {
    const L = layoutsFile.layouts[preset];
    const mode2 = stageWhy ? mode : L.camera;
    if (!stageWhy) set('camera', mode2 + ' (from the layout)', 'layout default');
    const t2 = timeMatched ? time : (L.time_hint || time);
    if (!timeMatched && L.time_hint) set('time of day', t2 + ' (from the layout)', 'layout default');
    const spec = {
      version: 1, scene: 'stage', preset, title: raw.trim().slice(0, 80) || preset, seed: parseInt(sha256Hex(t).slice(0, 8), 16),
      theme: { time: t2, weather, setting }, accent: liveryMatched ? livery : (L.accent || '#2f6fd6'), motion: { duration },
      camera: { mode: mode2 }, backdrop: L.backdrop, ground: L.ground, stage: { ...L.stage },
      scenery: L.scenery.map((it) => ({ ...it })), actors: L.actors.map((a) => ({ ...a })),
    };
    return { spec, notes };
  }

  const treeCount = setting === 'coast' ? 9 : 16;
  const spec = {
    version: 1,
    scene,
    title: raw.trim().slice(0, 80) || 'Plane taking off',
    seed: parseInt(sha256Hex(t).slice(0, 8), 16),
    theme: { time, weather, setting },
    ...(interior ? {} : { airport: { code }, aircraft: { prop: scene === 'launch' ? 'rocket' : 'jet-airliner', livery } }),
    ...(interior ? { accent: liveryMatched ? livery : '#d9853b', actors: WORKSHOP_ACTORS.map((a) => ({ ...a })) } : {}),
    motion: { duration, climb },
    camera: { mode },
    scenery: SCENE_DEFAULTS[scene].map((it) => ({ ...it })),
    decor: { trees: interior ? 0 : treeCount },
  };
  return { spec, notes };
}

/* ------------------------------------------------------------ spec check */
const ENUMS = { time: ['dawn', 'day', 'dusk', 'night'], weather: ['clear', 'cloudy', 'overcast'], setting: ['countryside', 'coast'], mode: [...MODES.aircraft, ...MODES.interior], scene: SCENES };
const SPEC_VOCAB = { time: ENUMS.time, weather: ENUMS.weather, setting: ENUMS.setting, stage_cameras: MODES.interior, backdrops: STAGE_BACKDROPS, grounds: STAGE_GROUNDS, motions: STAGE_MOTIONS, limits: STAGE_LIMITS };

/* ------------------------------------------------------------------ sketch: the escape hatch inside a scene
 * When no prop in the kit fits, a scene item may carry `sketch`: an array of SVG element strings. They are checked by the SAME rules as the
 * catalogue's agent_sketchpad atom (a port of its validator, see atoms_charts.gs): allowlisted tags and attributes only, values limited to
 * letters, digits and  # . , - ( ) %  (so no ':' means no javascript: and no external url, and no quotes or '<'), no style, no href, no id,
 * no text content, one element per string. Anything else is REFUSED with an error, never silently skipped. */
const SKETCH_TAGS = new Set(['circle', 'ellipse', 'rect', 'line', 'polyline', 'polygon', 'path', 'g']);
const SKETCH_ATTRS = new Set(['cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'width', 'height', 'x1', 'y1', 'x2', 'y2', 'points', 'd', 'fill', 'stroke', 'stroke-width',
  'opacity', 'fill-opacity', 'stroke-opacity', 'stroke-linecap', 'stroke-linejoin', 'transform']);
const SKETCH_SAFE = /^[A-Za-z0-9#.,\-\s()%]*$/;

function sketchParse(s, pos, depth) {
  if (depth > 6) return null;
  while (pos < s.length && /\s/.test(s[pos])) pos++;
  const m = /^<([a-zA-Z][a-zA-Z0-9]*)/.exec(s.slice(pos));
  if (!m) return null;
  const tag = m[1];
  pos += m[0].length;
  const attrs = {};
  for (;;) {
    while (pos < s.length && /\s/.test(s[pos])) pos++;
    if (s.slice(pos, pos + 2) === '/>') return { tag, attrs, children: [], pos: pos + 2 };
    if (s[pos] === '>') { pos++; break; }
    const am = /^([a-zA-Z][a-zA-Z0-9-]*)\s*=\s*"([^"]*)"|^([a-zA-Z][a-zA-Z0-9-]*)\s*=\s*'([^']*)'/.exec(s.slice(pos));
    if (!am) return null;                                      // stray, unquoted or malformed attribute text
    attrs[(am[1] || am[3]).toLowerCase()] = am[2] !== undefined ? am[2] : am[4];
    pos += am[0].length;
  }
  const close = '</' + tag + '>', children = [];
  for (;;) {
    while (pos < s.length && /\s/.test(s[pos])) pos++;
    if (s.slice(pos, pos + close.length) === close) return { tag, attrs, children, pos: pos + close.length };
    if (s[pos] !== '<') return null;                           // real text content is never valid here
    const child = sketchParse(s, pos, depth + 1);
    if (!child) return null;
    children.push(child);
    pos = child.pos;
  }
}
function sketchValid(el) {
  if (!SKETCH_TAGS.has(el.tag)) return false;
  for (const name of Object.keys(el.attrs)) if (!SKETCH_ATTRS.has(name) || !SKETCH_SAFE.test(el.attrs[name])) return false;
  return el.children.every(sketchValid);
}
function sketchSerialize(el) {
  let out = '<' + el.tag;
  for (const name of Object.keys(el.attrs)) out += ` ${name}="${esc(el.attrs[name])}"`;
  return el.children.length ? out + '>' + el.children.map(sketchSerialize).join('') + '</' + el.tag + '>' : out + '/>';
}
/** One SVG element string -> its re-serialised, validated markup, or null if it breaks any rule. */
function sketchElement(fragment) {
  if (typeof fragment !== 'string' || fragment.length > STAGE_LIMITS.sketch_chars) return null;
  const parsed = sketchParse(fragment, 0, 0);
  if (!parsed || /\S/.test(fragment.slice(parsed.pos)) || !sketchValid(parsed)) return null;
  return sketchSerialize(parsed);
}

/** scenery_add / actors_add append to whatever the layout (preset or explicit) provides, so a spec can extend a preset without rewriting it. */
function addExtras(spec) {
  const out = { ...spec };
  for (const [add, base] of [['scenery_add', 'scenery'], ['actors_add', 'actors']]) {
    if (out[add] === undefined) continue;
    if (Array.isArray(out[add])) out[base] = (Array.isArray(out[base]) ? out[base] : []).concat(out[add]);
    delete out[add];
  }
  return out;
}

/** Fill a stage spec's missing layout fields from its named preset. Explicit fields always win. */
function expandPreset(spec, atom) {
  const L = spec && spec.preset && atom.layouts && atom.layouts.layouts && atom.layouts.layouts[spec.preset];
  if (!L) return addExtras(spec);
  const out = { ...spec };
  for (const k of ['backdrop', 'ground', 'stage', 'scenery', 'actors']) if (out[k] === undefined) out[k] = JSON.parse(JSON.stringify(L[k]));
  if (out.camera === undefined) out.camera = { mode: L.camera };
  return addExtras(out);
}

function validateStage(input, atom) {
  const errors = [];
  const isObj = (v) => v && typeof v === 'object' && !Array.isArray(v);
  const only = (obj, keys, path) => { if (!isObj(obj)) { errors.push(`${path} must be an object`); return false; } for (const k of Object.keys(obj)) if (!keys.includes(k)) errors.push(`${path}.${k} is not a known field`); return true; };
  const num = (v, a, b) => typeof v === 'number' && Number.isFinite(v) && v >= a && v <= b;
  const Lm = STAGE_LIMITS, rng2 = ([a, b]) => `${a}..${b}`;
  if (input.preset !== undefined && !(atom.layouts && atom.layouts.layouts && atom.layouts.layouts[input.preset])) errors.push(`spec.preset must be one of: ${Object.keys((atom.layouts || {}).layouts || {}).join(', ')}`);
  for (const k of ['scenery_add', 'actors_add']) if (input[k] !== undefined && !Array.isArray(input[k])) errors.push(`spec.${k} must be an array`);
  const s = expandPreset(input, atom);
  if (!only(s, ['version', 'scene', 'preset', 'title', 'seed', 'theme', 'accent', 'motion', 'camera', 'backdrop', 'ground', 'stage', 'scenery', 'actors'], 'spec')) return { ok: false, errors, spec: null };
  if (s.version !== 1) errors.push('spec.version must be 1');
  if (typeof s.title !== 'string' || s.title.length > Lm.title) errors.push(`spec.title must be a string of at most ${Lm.title} characters`);
  if (!Number.isInteger(s.seed) || s.seed < Lm.seed[0] || s.seed > Lm.seed[1]) errors.push(`spec.seed must be an integer ${rng2(Lm.seed)}`);
  if (only(s.theme, ['time', 'weather', 'setting'], 'spec.theme')) {
    if (!ENUMS.time.includes(s.theme.time)) errors.push('spec.theme.time must be one of ' + ENUMS.time.join('|'));
    if (!ENUMS.weather.includes(s.theme.weather)) errors.push('spec.theme.weather must be one of ' + ENUMS.weather.join('|'));
    if (!ENUMS.setting.includes(s.theme.setting)) errors.push('spec.theme.setting must be one of ' + ENUMS.setting.join('|'));
  }
  if (s.accent !== undefined && !/^#[0-9a-fA-F]{6}$/.test(s.accent)) errors.push('spec.accent must be #rrggbb');
  if (only(s.motion, ['duration'], 'spec.motion') && !num(s.motion.duration, ...Lm.duration)) errors.push(`spec.motion.duration must be ${rng2(Lm.duration)} seconds`);
  if (only(s.camera, ['mode'], 'spec.camera') && !MODES.interior.includes(s.camera.mode)) errors.push(`spec.camera.mode must be one of ${MODES.interior.join('|')} for the stage scene`);
  if (!STAGE_BACKDROPS.includes(s.backdrop)) errors.push('spec.backdrop must be one of ' + STAGE_BACKDROPS.join('|'));
  if (!STAGE_GROUNDS.includes(s.ground)) errors.push('spec.ground must be one of ' + STAGE_GROUNDS.join('|'));
  if (only(s.stage, ['width', 'zoom', 'focus_y'], 'spec.stage')) {
    for (const k of ['width', 'zoom', 'focus_y']) if (!num(s.stage[k], ...Lm[k])) errors.push(`spec.stage.${k} must be ${rng2(Lm[k])}`);
  }
  const checkVariant = (it, p, path) => {
    if (it.variant === undefined) return;
    const names = p && p.variants ? Object.keys(p.variants) : [];
    if (!names.includes(it.variant)) errors.push(`${path}.variant must be one of: ${names.join(', ') || '(this prop has no variants)'}`);
  };
  let sketchCount = 0, sketchChars = 0;
  const checkSketch = (it, path) => {
    if (it.prop !== undefined || it.variant !== undefined) errors.push(`${path}: a sketch item takes no prop or variant`);
    const sk = it.sketch;
    sketchCount++;
    if (!Array.isArray(sk) || sk.length < 1 || sk.length > Lm.sketch_elements) { errors.push(`${path}.sketch must be an array of 1..${Lm.sketch_elements} SVG element strings`); return; }
    sk.forEach((el, j) => {
      if (typeof el !== 'string' || el.length > Lm.sketch_chars) { errors.push(`${path}.sketch[${j}] must be a string of at most ${Lm.sketch_chars} characters`); return; }
      sketchChars += el.length;
      if (!sketchElement(el)) errors.push(`${path}.sketch[${j}] is not an allowed sketch element (one element per string; tags ${[...SKETCH_TAGS].join(', ')}; attributes ${[...SKETCH_ATTRS].join(', ')}; values only letters, digits and # . , - ( ) %; no text, style or href)`);
    });
  };
  if (!Array.isArray(s.scenery) || s.scenery.length > Lm.scenery) errors.push(`spec.scenery must be an array of at most ${Lm.scenery} items`);
  else s.scenery.forEach((it, i) => {
    if (!only(it, ['prop', 'x', 'y', 'variant', 'scale', 'flip', 'sketch'], `spec.scenery[${i}]`)) return;
    const isSketch = it.sketch !== undefined;
    const p = isSketch ? null : atom.byId[it.prop];
    if (isSketch) checkSketch(it, `spec.scenery[${i}]`);
    else if (!p) errors.push(`spec.scenery[${i}].prop must be a registry prop (or give a sketch)`);
    if (!num(it.x, ...Lm.scenery_x)) errors.push(`spec.scenery[${i}].x must be ${rng2(Lm.scenery_x)}`);
    if (it.y !== undefined && !num(it.y, ...Lm.scenery_y)) errors.push(`spec.scenery[${i}].y must be ${rng2(Lm.scenery_y)}`);
    if (it.scale !== undefined && !num(it.scale, ...Lm.scale)) errors.push(`spec.scenery[${i}].scale must be ${rng2(Lm.scale)}`);
    if (it.flip !== undefined && typeof it.flip !== 'boolean') errors.push(`spec.scenery[${i}].flip must be true or false`);
    if (!isSketch) checkVariant(it, p, `spec.scenery[${i}]`);
  });
  if (!Array.isArray(s.actors) || s.actors.length > Lm.actors) errors.push(`spec.actors must be an array of at most ${Lm.actors} items`);
  else s.actors.forEach((a, i) => {
    if (!only(a, ['prop', 'motion', 'x0', 'x1', 'y', 'period', 'phase', 'variant', 'scale', 'ry', 'sketch'], `spec.actors[${i}]`)) return;
    const isSketch = a.sketch !== undefined;
    const p = isSketch ? null : atom.byId[a.prop];
    if (isSketch) checkSketch(a, `spec.actors[${i}]`);
    else if (!p) errors.push(`spec.actors[${i}].prop must be a registry prop (or give a sketch)`);
    if (!STAGE_MOTIONS.includes(a.motion)) errors.push(`spec.actors[${i}].motion must be one of ${STAGE_MOTIONS.join('|')}`);
    for (const k of ['x0', 'x1']) if (!num(a[k], ...Lm.actor_x)) errors.push(`spec.actors[${i}].${k} must be ${rng2(Lm.actor_x)}`);
    if (!num(a.y, ...Lm.actor_y)) errors.push(`spec.actors[${i}].y must be ${rng2(Lm.actor_y)}`);
    if (!num(a.period, ...Lm.period)) errors.push(`spec.actors[${i}].period must be ${rng2(Lm.period)} seconds`);
    if (!num(a.phase, ...Lm.phase)) errors.push(`spec.actors[${i}].phase must be ${rng2(Lm.phase)}`);
    if (a.scale !== undefined && !num(a.scale, ...Lm.scale)) errors.push(`spec.actors[${i}].scale must be ${rng2(Lm.scale)}`);
    if (a.ry !== undefined && !num(a.ry, ...Lm.ry)) errors.push(`spec.actors[${i}].ry must be ${rng2(Lm.ry)}`);
    if (!isSketch) checkVariant(a, p, `spec.actors[${i}]`);
  });
  if (sketchCount > Lm.sketches) errors.push(`a scene may hold at most ${Lm.sketches} sketches (scenery and actors together)`);
  if (sketchChars > Lm.sketch_total) errors.push(`the sketches of one scene may total at most ${Lm.sketch_total} characters`);
  if (errors.length) return { ok: false, errors, spec: null };
  const spec = JSON.parse(JSON.stringify(s));
  if (spec.accent === undefined) spec.accent = '#2f6fd6';
  return { ok: true, errors: [], spec };
}

/** Strict validation. Unknown keys are errors. Returns {ok, errors, spec} with the normalised spec. */
function validateSpec(input, atom) {
  const errors = [];
  const isObj = (v) => v && typeof v === 'object' && !Array.isArray(v);
  const only = (obj, keys, path) => { if (!isObj(obj)) { errors.push(`${path} must be an object`); return false; } for (const k of Object.keys(obj)) if (!keys.includes(k)) errors.push(`${path}.${k} is not a known field`); return true; };
  const int = (v) => Number.isInteger(v);
  const num = (v, a, b) => typeof v === 'number' && Number.isFinite(v) && v >= a && v <= b;
  const checkVariant = (it, p, path) => {
    if (it.variant === undefined) return;
    const names = p && p.variants ? Object.keys(p.variants) : [];
    if (!names.includes(it.variant)) errors.push(`${path}.variant must be one of: ${names.join(', ') || '(this prop has no variants)'}`);
  };
  const s = input;
  if (isObj(s) && s.scene === 'stage') return validateStage(s, atom);
  if (!only(s, ['version', 'scene', 'title', 'seed', 'theme', 'airport', 'aircraft', 'accent', 'actors', 'motion', 'camera', 'scenery', 'decor'], 'spec')) return { ok: false, errors, spec: null };
  if (s.version !== 1) errors.push('spec.version must be 1');
  if (s.scene !== undefined && !ENUMS.scene.includes(s.scene)) errors.push('spec.scene must be one of ' + ENUMS.scene.join('|'));
  if (typeof s.title !== 'string' || s.title.length > 80) errors.push('spec.title must be a string of at most 80 characters');
  if (!int(s.seed) || s.seed < 0 || s.seed > 4294967295) errors.push('spec.seed must be an integer 0..4294967295');
  if (only(s.theme, ['time', 'weather', 'setting'], 'spec.theme')) {
    if (!ENUMS.time.includes(s.theme.time)) errors.push('spec.theme.time must be one of ' + ENUMS.time.join('|'));
    if (!ENUMS.weather.includes(s.theme.weather)) errors.push('spec.theme.weather must be one of ' + ENUMS.weather.join('|'));
    if (!ENUMS.setting.includes(s.theme.setting)) errors.push('spec.theme.setting must be one of ' + ENUMS.setting.join('|'));
  }
  const interior = INTERIOR.includes(s.scene);
  if (interior) {
    for (const k of ['airport', 'aircraft']) if (s[k] !== undefined) errors.push(`spec.${k} is not used in the ${s.scene} scene`);
    if (s.accent !== undefined && !/^#[0-9a-fA-F]{6}$/.test(s.accent)) errors.push('spec.accent must be #rrggbb');
    if (!Array.isArray(s.actors) || s.actors.length < 1 || s.actors.length > 8) errors.push('spec.actors must be an array of 1 to 8 items');
    else s.actors.forEach((a, i) => {
      if (!only(a, ['prop', 'motion', 'x0', 'x1', 'y', 'period', 'phase', 'variant'], `spec.actors[${i}]`)) return;
      const p = atom.byId[a.prop];
      checkVariant(a, p, `spec.actors[${i}]`);
      if (!p || !(p.anchors || {}).actor) errors.push(`spec.actors[${i}].prop must be a registry actor prop (${atom.registry.entries.filter((e) => (e.anchors || {}).actor).map((e) => e.id).join(', ')})`);
      if (!['walk', 'ride'].includes(a.motion)) errors.push(`spec.actors[${i}].motion must be walk|ride`);
      for (const k of ['x0', 'x1']) if (!num(a[k], -300, 3000)) errors.push(`spec.actors[${i}].${k} must be -300..3000`);
      if (!num(a.y, -400, 60)) errors.push(`spec.actors[${i}].y must be -400..60`);
      if (!num(a.period, 4, 60)) errors.push(`spec.actors[${i}].period must be 4..60 seconds`);
      if (!num(a.phase, 0, 1)) errors.push(`spec.actors[${i}].phase must be 0..1`);
    });
  } else {
    if (s.actors !== undefined) errors.push(`spec.actors only applies to interior scenes, not ${s.scene || 'takeoff'}`);
    if (s.accent !== undefined) errors.push('spec.accent only applies to interior scenes');
    if (only(s.airport, ['code'], 'spec.airport') && !/^[A-Z]{3,4}$/.test(s.airport.code)) errors.push('spec.airport.code must be 3-4 capital letters');
    if (only(s.aircraft, ['prop', 'livery'], 'spec.aircraft')) {
      const p = atom.byId[s.aircraft.prop];
      if (!p || p.kind !== 'aircraft') errors.push(`spec.aircraft.prop must be a registry aircraft (${atom.registry.entries.filter((e) => e.kind === 'aircraft').map((e) => e.id).join(', ')})`);
      else if (!(p.anchors.scenes || []).includes(s.scene || 'takeoff')) errors.push(`spec.aircraft.prop ${p.id} cannot be used in scene ${s.scene || 'takeoff'}`);
      if (!/^#[0-9a-fA-F]{6}$/.test(s.aircraft.livery)) errors.push('spec.aircraft.livery must be #rrggbb');
    }
  }
  if (only(s.motion, ['duration', 'climb'], 'spec.motion')) {
    if (!num(s.motion.duration, 6, 40)) errors.push('spec.motion.duration must be 6..40 seconds');
    if (!num(s.motion.climb, 0.5, 1.5)) errors.push('spec.motion.climb must be 0.5..1.5');
  }
  const modes = MODES[interior ? 'interior' : 'aircraft'];
  if (only(s.camera, ['mode'], 'spec.camera') && !modes.includes(s.camera.mode)) errors.push(`spec.camera.mode must be one of ${modes.join('|')} for the ${s.scene || 'takeoff'} scene`);
  if (!Array.isArray(s.scenery) || s.scenery.length > 12) errors.push('spec.scenery must be an array of at most 12 items');
  else s.scenery.forEach((it, i) => {
    if (!only(it, ['prop', 'x', 'y', 'variant'], `spec.scenery[${i}]`)) return;
    const p = atom.byId[it.prop];
    if (!p || p.kind !== 'scenery') errors.push(`spec.scenery[${i}].prop must be a registry scenery prop`);
    if (!num(it.x, -300, 3000)) errors.push(`spec.scenery[${i}].x must be -300..3000`);
    if (it.y !== undefined && !num(it.y, -400, 60)) errors.push(`spec.scenery[${i}].y must be -400..60`);
    checkVariant(it, p, `spec.scenery[${i}]`);
  });
  if (only(s.decor, ['trees'], 'spec.decor') && !(int(s.decor.trees) && s.decor.trees >= 0 && s.decor.trees <= 40)) errors.push('spec.decor.trees must be an integer 0..40');
  if (errors.length) return { ok: false, errors, spec: null };
  const spec = JSON.parse(JSON.stringify(s));
  if (spec.scene === undefined) spec.scene = 'takeoff';
  if (INTERIOR.includes(spec.scene) && spec.accent === undefined) spec.accent = '#d9853b';
  return { ok: true, errors: [], spec };
}

/* ------------------------------------------------------- motion + camera */
const N = 90;              // samples per loop; every animation shares these keyTimes
const T_START = 0.06;      // brake release
const T_ROTATE = 0.50;     // nose starts to lift
const X0 = 80, X_ROTATE = 1700;
const GY = 10;             // world y of the wheel-contact line (runway centreline)
const AIR = { w: 900, h: 506.25 };

function takeoffTrajectory(spec) {
  const climb = spec.motion.climb;
  const vR = (2 * (X_ROTATE - X0)) / (T_ROTATE - T_START);
  const x = (t) => {
    if (t < T_START) return X0;
    if (t < T_ROTATE) return X0 + (X_ROTATE - X0) * ((t - T_START) / (T_ROTATE - T_START)) ** 2;
    const s = t - T_ROTATE;
    return X_ROTATE + vR * s + 0.5 * (0.4 * vR) * s * s;
  };
  const peak = Math.min(18, 12 * climb);
  const pitch = (t) => {
    if (t < T_ROTATE) return 0;
    const u = (t - T_ROTATE) / 0.07;
    if (u < 1) return peak * smooth(u);
    return peak * (1 - 0.25 * clamp((t - T_ROTATE - 0.07) / (1 - T_ROTATE - 0.07), 0, 1));
  };
  const tLift = T_ROTATE + 0.045;
  const samples = [];
  let alt = 0, prevX = x(0), tPrev = 0;
  for (let i = 0; i <= N; i++) {
    const t = i / N;
    const sub = 8;
    for (let k = 1; k <= sub; k++) {
      const tt = tPrev + ((t - tPrev) * k) / sub;
      const xx = x(tt);
      if (tt > tLift) alt += Math.tan((pitch(tt) * Math.PI) / 180) * (xx - prevX);
      prevX = xx;
    }
    tPrev = t;
    samples.push({ t, x: x(t), alt, pitch: pitch(t) });
  }
  return { samples, tLift, tRotate: T_ROTATE };
}

/* Landing: 5-degree glide, flare, touch-down, decelerating roll-out. Speed is continuous at touch-down. */
const LAND = { tFlare: 0.5, tTouch: 0.58, xTouch: 500, xStart: -2900, altFlare: 40 };
function landingTrajectory(spec) {
  const { tFlare, tTouch, xTouch, xStart, altFlare } = LAND;
  const va = (xTouch - xStart) / tTouch;
  const roll = (va * (1 - tTouch)) / 2;
  const slope = Math.tan(((5 * spec.motion.climb) * Math.PI) / 180);
  const x = (t) => (t <= tTouch ? xStart + va * t : xTouch + roll * (1 - (1 - (t - tTouch) / (1 - tTouch)) ** 2));
  const alt = (t) => {
    if (t >= tTouch) return 0;
    if (t >= tFlare) return altFlare * (1 - smooth((t - tFlare) / (tTouch - tFlare)));
    return altFlare + slope * (x(tFlare) - x(t));
  };
  const pitch = (t) => (t < tFlare ? 2.5 : t < tTouch ? lerp(2.5, 6, smooth((t - tFlare) / (tTouch - tFlare))) : 6 * (1 - smooth((t - tTouch) / 0.05)));
  const samples = Array.from({ length: N + 1 }, (_, i) => { const t = i / N; return { t, x: x(t), alt: alt(t), pitch: pitch(t) }; });
  return { samples, tTouch, tFlare };
}

/* Fly-by: the aircraft crosses the airfield at cruise height on a gentle wave (agent traffic). */
function flybyTrajectory() {
  const dx = 3300, x = (t) => -350 + dx * t;
  const samples = Array.from({ length: N + 1 }, (_, i) => {
    const t = i / N;
    const dAlt = 45 * 2 * Math.PI * Math.cos(2 * Math.PI * t);
    return { t, x: x(t), alt: 380 + 45 * Math.sin(2 * Math.PI * t), pitch: (Math.atan2(dAlt, dx) * 180) / Math.PI };
  });
  return { samples };
}

/* Launch: hold, ignite, shake, lift, accelerate, gravity-turn to the right. Vertical rocket: 'pitch' stores minus the tilt so
 * the shared -pitch rotation tilts the nose clockwise (toward +x). */
const LAUNCH = { tIgnite: 0.12, tLift: 0.24, pad: 20, x: 600 };
function launchTrajectory(spec) {
  const { tIgnite, tLift, pad, x: x0 } = LAUNCH;
  const A = 2900 * spec.motion.climb;
  const u = (t) => clamp((t - tLift) / (1 - tLift), 0, 1);
  const alt = (t) => pad + A * u(t) ** 2;
  const x = (t) => x0 + 520 * u(t) ** 3 + (t >= tIgnite && t < tLift ? 2.2 * Math.sin(t * 900) : 0);
  const samples = Array.from({ length: N + 1 }, (_, i) => {
    const t = i / N, e = 1 / (N * 4);
    const dAlt = alt(Math.min(1, t + e)) - alt(Math.max(0, t - e)), dX = x(Math.min(1, t + e)) - x(Math.max(0, t - e));
    const tilt = t > tLift ? clamp((Math.atan2(dX, Math.max(dAlt, 1e-6)) * 180) / Math.PI, 0, 35) : 0;
    return { t, x: x(t), alt: alt(t), pitch: -tilt };
  });
  return { samples, tIgnite, tLift };
}

function trajectory(spec) {
  if (spec.scene === 'launch') return launchTrajectory(spec);
  if (spec.scene === 'landing') return landingTrajectory(spec);
  if (spec.scene === 'orchestrator') return flybyTrajectory(spec);
  return takeoffTrajectory(spec);
}

/* Zoom keyframes [t, viewport width] for the cinematic mode, per scene. */
const CINEMATIC_WIDTH = {
  takeoff: [[0, 1500], [0.22, 1000], [0.46, 800], [0.62, 1100], [1, 2400]],
  landing: [[0, 1600], [0.35, 1250], [0.58, 850], [0.8, 1000], [1, 1500]],
  orchestrator: [[0, 1500], [0.5, 1100], [1, 1500]],
  launch: [[0, 1250], [0.3, 950], [0.6, 1500], [1, 2800]],
};

function cameraPath(spec, samples) {
  const mode = spec.camera.mode, scene = spec.scene;
  const key = CINEMATIC_WIDTH[scene];
  const widthAt = (t) => {
    for (let i = 1; i < key.length; i++) {
      if (t <= key[i][0]) return lerp(key[i - 1][1], key[i][1], smooth((t - key[i - 1][0]) / (key[i][0] - key[i - 1][0])));
    }
    return key[key.length - 1][1];
  };
  const tower = (spec.scenery.find((it) => it.prop === 'control-tower') || { x: 700 }).x;
  const wideW = (t) => (scene === 'takeoff' ? lerp(2200, 2600, t) : scene === 'landing' ? 2400 : scene === 'launch' ? 3000 : 2800);
  const target = (s, w) => {
    if (mode === 'follow') return s.x + 0.18 * w;
    if (scene === 'takeoff') return mode === 'wide' ? 700 + s.x * 0.72 : s.x;
    if (scene === 'landing') return mode === 'wide' ? s.x + 0.15 * w : s.x;
    if (scene === 'launch') return s.x;
    return mode === 'wide' ? 0.5 * s.x + 0.5 * tower : 0.6 * tower + 0.4 * s.x;     // orchestrator: hold the tower, let traffic cross
  };
  const climbFollow = scene === 'orchestrator' ? 0.55 : scene === 'launch' ? 0.95 : 0.62;
  const centreLift = scene === 'launch' ? 120 : 60;     // height of the vehicle's visual centre above its origin
  const out = [];
  let cx = 0, cy = 0;
  samples.forEach((s, i) => {
    const w = mode === 'wide' ? wideW(s.t) : mode === 'follow' ? 900 : widthAt(s.t);
    const h = (w * AIR.h) / AIR.w;
    const tx = target(s, w);
    const ty = Math.min(-95, -95 - climbFollow * s.alt);
    if (i === 0 || mode === 'follow') { cx = tx; cy = ty; }
    else { const a = mode === 'wide' ? 0.3 : 0.4; cx += (tx - cx) * a; cy += (ty - cy) * a; }
    // Whatever the smoothing did, the aircraft must stay inside the frame.
    const planeY = GY - s.alt - centreLift, lim = h / 2 - 110;
    cy = clamp(cy, planeY - lim, planeY + lim);
    const limX = w / 2 - 140;
    cx = clamp(cx, s.x - limX, s.x + limX);
    out.push({ cx, cy, w, h });
  });
  return out;
}

/* ---------------------------------------------------------- scene builder */
const vals = (arr) => arr.join(';');
const keyTimes = (n) => vals(Array.from({ length: n }, (_, i) => fmt2(i / (n - 1))));
const fmt2 = (n) => String(Math.round(n * 1000) / 1000);

function propInner(entry, palette, variant) {
  const m = entry.svg.match(/^\s*<svg[^>]*>([\s\S]*)<\/svg>\s*$/);
  if (!m) throw new Error('prop ' + entry.id + ' is not a single <svg>');
  const pal = { ...(entry.tokens || {}), ...palette, ...((entry.variants || {})[variant] || {}) };
  return m[1].replace(TOKEN_RE, (_, k) => {
    if (pal[k] === undefined) throw new Error(`prop ${entry.id}: token {{${k}}} has no value`);
    return pal[k];
  });
}

/** Find props by words. Every query term must match the id, name, category or a tag (prefix match); results are ranked so exact
 * tag and id hits come first. Intended for agents choosing artwork: searchProps(atom, 'crane') or ('medical bed'). */
function searchProps(atom, query, { category, limit = 50 } = {}) {
  const terms = String(query || '').toLowerCase().split(/[^a-z0-9-]+/).filter(Boolean);
  const out = [];
  for (const e of atom.registry.entries) {
    if (category && e.category !== category) continue;
    const words = [e.id, ...e.id.split('-'), ...e.name.toLowerCase().split(/[^a-z0-9]+/), e.category, ...e.tags];
    let score = 0, ok = true;
    for (const t of terms) {
      let best = 0;
      for (const w of words) best = Math.max(best, w === t ? 3 : e.tags.includes(w) && w.startsWith(t) ? 2 : w.startsWith(t) ? 1 : 0);
      if (!best) { ok = false; break; }
      score += best;
    }
    if (ok) out.push({ id: e.id, name: e.name, category: e.category, tags: e.tags, score });
  }
  return out.sort((a, b) => b.score - a.score || a.id.localeCompare(b.id)).slice(0, limit);
}

/** A small standalone preview of one prop under one lighting, for the prop library. */
function renderPropPreview(atom, id, variant, time = 'day') {
  const entry = atom.byId[id];
  if (!entry) throw new Error('unknown prop ' + id);
  if (variant !== undefined && !(entry.variants || {})[variant]) throw new Error(`prop ${id} has no variant ${variant}`);
  const P = paletteFor({ theme: { time, weather: 'clear' }, aircraft: { livery: '#2f6fd6' } });
  return { viewBox: entry.svg.match(/viewBox="([^"]+)"/)[1], markup: propInner(entry, P, variant), background: P.skyBot };
}

function hills(rand, x0, x1, base, hMin, hMax, colour) {
  const pts = [];
  for (let x = x0; x <= x1 + 120; x += 110) pts.push([x, base - lerp(hMin, hMax, rand())]);
  let d = `M${fmt(pts[0][0])},${base + 40} L${fmt(pts[0][0])},${fmt(pts[0][1])}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const mx = (pts[i][0] + pts[i + 1][0]) / 2, my = (pts[i][1] + pts[i + 1][1]) / 2;
    d += ` Q${fmt(pts[i][0])},${fmt(pts[i][1])} ${fmt(mx)},${fmt(my)}`;
  }
  const last = pts[pts.length - 1];
  d += ` L${fmt(last[0])},${fmt(last[1])} L${fmt(last[0])},${base + 40} Z`;
  return `<path d="${d}" fill="${colour}"/>`;
}

/* Shared by every scene type: provenance record, metadata and the standalone SVG shell. */
function wrapScene({ spec, atom, used, usedVariants = {}, procedural, cam, kt, D, defs, S, body, extra, sketches = [] }) {
  const assets = [...used].sort().map((id) => {
    const e = atom.byId[id];
    return { id, name: e.name, kind: e.kind, ...(usedVariants[id] ? { variants: [...usedVariants[id]].sort() } : {}), origin: e.origin.type, author: e.origin.author, license: e.origin.license, source_url: e.origin.source_url, attribution: e.origin.attribution, sha256: e.sha256 };
  });
  const provenance = {
    generator: { name: 'scene-atom', version: RENDERER_VERSION },
    spec_sha256: sha256Hex(JSON.stringify(spec)),
    registry_sha256: atom.registrySha256,
    assets,
    procedural: [...new Set(procedural)],
    ...(sketches.length ? { sketches } : {}),                    // agent-authored geometry that did NOT come from the kit
    attributions: [...new Set(assets.filter((a) => atom.allow.attribution_required.includes(a.license)).map((a) => a.attribution))],
  };
  const vb0 = cam[0];
  const viewBoxValues = vals(cam.map((c) => `${fmt(c.cx - c.w / 2)} ${fmt(c.cy - c.h / 2)} ${fmt(c.w)} ${fmt(c.h)}`));
  const meta = `<metadata><scene-atom:provenance xmlns:scene-atom="urn:scene-atom:1">${esc(JSON.stringify(provenance))}</scene-atom:provenance></metadata>`;
  const svg = `<svg xmlns="${SVG_NS}" id="scene" viewBox="${fmt(vb0.cx - vb0.w / 2)} ${fmt(vb0.cy - vb0.h / 2)} ${fmt(vb0.w)} ${fmt(vb0.h)}" width="1280" height="720" preserveAspectRatio="xMidYMid slice" role="img" aria-label="${esc(spec.title)}">` +
    `<title>${esc(spec.title)}</title><desc>Animated scene generated by scene-atom ${RENDERER_VERSION}. Scene: ${spec.scene}; camera mode: ${spec.camera.mode}.</desc>${meta}` +
    `<animate attributeName="viewBox" values="${viewBoxValues}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/>` +
    `<defs>${defs.join('')}</defs>${body}</svg>`;
  return { svg, provenance, spec, meta: { scene: spec.scene, samples: S, camera: cam, duration: D, ...extra } };
}

/* ------------------------------------------------------------ interior scene */
const ROOM = { x0: -300, x1: 2400, ceiling: -560, floor: 400 };
const ROOM_DIM = { day: 0.15, dawn: 0.3, dusk: 0.38, night: 0.72 };        // how far the wall is pulled toward the dark tone
const ROOM_SHADE = { day: 0, dawn: 0.1, dusk: 0.18, night: 0.34 };         // darkness overlay opacity
const LOOP = (n) => Array.from({ length: n + 1 }, (_, i) => ({ t: i / n }));

/* Interior cameras loop seamlessly: pan and push-in return to where they started. */
function workshopCamera(spec, samples) {
  const mode = spec.camera.mode;
  return samples.map(({ t }) => {
    const ease = (1 - Math.cos(2 * Math.PI * t)) / 2;                     // 0 -> 1 -> 0
    const w = mode === 'static' ? 1300 : mode === 'pan' ? 1000 : lerp(1600, 850, ease);
    const cx = mode === 'static' ? 1000 : mode === 'pan' ? lerp(350, 1650, ease) : lerp(1000, 1300, ease);
    const cy = mode === 'push-in' ? lerp(-230, -190, ease) : -230;
    return { cx, cy, w, h: (w * AIR.h) / AIR.w };
  });
}

function buildInterior(spec, atom) {
  const P = paletteFor(spec);
  const D = spec.motion.duration;
  const S = LOOP(90);
  const cam = workshopCamera(spec, S);
  const kt = keyTimes(S.length);
  const used = new Set();
  const defs = [];
  const usedVariants = {};
  const defOf = (id, variant) => {
    const key = 'a-' + id + (variant ? '--' + variant : '');
    if (variant) (usedVariants[id] = usedVariants[id] || new Set()).add(variant);
    if (!defs.some((d) => d.startsWith(`<g id="${key}"`))) { used.add(id); defs.push(`<g id="${key}">${propInner(atom.byId[id], P, variant)}</g>`); }
    return key;
  };
  const time = spec.theme.time, dim = ROOM_DIM[time];
  const wall = mix(P.structure, P.dark, dim), floor = mix(P.runway, P.dark, 0.25);
  const { x0, x1, ceiling } = ROOM, span = x1 - x0;

  /* walls, windows, ceiling, floor (procedural) */
  let room = `<rect x="-1200" y="-1400" width="4800" height="2600" fill="${P.dark}"/>` +
    `<rect x="${x0}" y="${ceiling}" width="${span}" height="${-ceiling}" fill="${wall}"/>`;
  for (let x = x0 + 120; x < x1; x += 240) room += `<path d="M${x},${ceiling} L${x},0" fill="none" stroke="${P.dark}" stroke-opacity="0.13" stroke-width="3"/>`;
  room += `<rect x="${x0}" y="-110" width="${span}" height="110" fill="${mix(P.glass, P.dark, 0.5)}"/><path d="M${x0},-110 L${x1},-110" fill="none" stroke="${P.roof}" stroke-width="6"/>`;
  for (let i = 0; i < 5; i++) {
    const wx = 190 + i * 430;
    room += `<rect x="${wx}" y="-470" width="200" height="140" fill="${P.skyBot}" stroke="${P.dark}" stroke-width="6"/><rect x="${wx}" y="-470" width="200" height="60" fill="${P.skyTop}" fill-opacity="0.85"/>` +
      `<path d="M${wx + 100},-470 L${wx + 100},-330 M${wx},-400 L${wx + 200},-400" fill="none" stroke="${P.dark}" stroke-width="4"/>`;
  }
  room += `<rect x="${x0}" y="-640" width="${span}" height="100" fill="${mix(P.roof, P.dark, 0.4)}"/>`;
  for (let x = x0; x < x1; x += 200) room += `<path d="M${x},-545 L${x + 100},-600 L${x + 200},-545" fill="none" stroke="${P.dark}" stroke-width="6" stroke-linejoin="round"/>`;
  room += `<path d="M${x0},-545 L${x1},-545" fill="none" stroke="${P.dark}" stroke-width="8"/>` +
    `<rect x="${x0}" y="0" width="${span}" height="${ROOM.floor}" fill="${floor}"/><path d="M${x0},0 L${x1},0" fill="none" stroke="${P.dark}" stroke-width="5"/>` +
    `<path d="M${x0},64 L${x1},64" fill="none" stroke="${P.sun}" stroke-width="10" stroke-dasharray="26 26"/><path d="M${x0},64 L${x1},64" fill="none" stroke="${P.dark}" stroke-width="10" stroke-dasharray="26 26" stroke-dashoffset="26"/>`;

  /* scenery from the registry */
  let scenery = '';
  for (const it of spec.scenery) {
    const anchors = atom.byId[it.prop].anchors || {};
    const y = it.y !== undefined ? it.y : anchors.base_y !== undefined ? anchors.base_y : 0;
    scenery += `<use href="#${defOf(it.prop, it.variant)}" transform="translate(${fmt(it.x)} ${fmt(y)})"/>`;
  }

  /* actors: robots patrol, crates ride the belt. Each loops on its own period; phase spreads them out. */
  let actors = '';
  for (const a of spec.actors) {
    const id = defOf(a.prop, a.variant), begin = `-${fmt2(a.phase * a.period)}s`, dur = `${a.period}s`;
    if (a.motion === 'walk') {
      actors += `<g><animateTransform attributeName="transform" type="translate" values="${fmt(a.x0)} ${fmt(a.y)};${fmt(a.x1)} ${fmt(a.y)};${fmt(a.x0)} ${fmt(a.y)}" keyTimes="0;0.5;1" dur="${dur}" begin="${begin}" repeatCount="indefinite"/>` +
        `<g><animateTransform attributeName="transform" type="scale" values="1 1;-1 1" keyTimes="0;0.5" calcMode="discrete" dur="${dur}" begin="${begin}" repeatCount="indefinite"/><use href="#${id}"/></g></g>`;
    } else {
      actors += `<g><animateTransform attributeName="transform" type="translate" values="${fmt(a.x0)} ${fmt(a.y)};${fmt(a.x1)} ${fmt(a.y)}" dur="${dur}" begin="${begin}" repeatCount="indefinite"/>` +
        `<animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.04;0.96;1" dur="${dur}" begin="${begin}" repeatCount="indefinite"/><use href="#${id}"/></g>`;
    }
  }

  /* ambient shading, then lamps and their light cones on top */
  const shade = ROOM_SHADE[time] ? `<rect x="${x0}" y="${ceiling}" width="${span}" height="${ROOM.floor - ceiling}" fill="${P.dark}" fill-opacity="${ROOM_SHADE[time]}"/>` : '';
  const glow = time === 'night' ? 0.17 : time === 'day' ? 0.06 : 0.11;
  let lamps = '';
  for (let x = 100; x < x1; x += 500) {
    lamps += `<path d="M${x - 14},-482 L${x - 150},0 L${x + 150},0 L${x + 14},-482 Z" fill="${P.window}" fill-opacity="${glow}"/>` +
      `<path d="M${x},-545 L${x},-500" fill="none" stroke="${P.dark}" stroke-width="3"/><path d="M${x - 26},-478 L${x - 12},-500 L${x + 12},-500 L${x + 26},-478 Z" fill="${P.roof}" stroke="${P.dark}" stroke-width="3" stroke-linejoin="round"/>` +
      `<circle cx="${x}" cy="-476" r="7" fill="${P.window}"/>`;
  }
  const procedural = ['interior walls and floor', 'ceiling lamps and light cones', 'ambient shading', 'camera path'];
  return wrapScene({ spec, atom, used, usedVariants, procedural, cam, kt, D, defs, S, body: `<g id="world">${room}${scenery}${actors}${shade}${lamps}</g>`, extra: {} });
}

/* ------------------------------------------------------------ stage scene (data-driven layouts) */
const STAGE_INTERIOR_TINT = { 'interior-office': '#8a97a8', 'interior-industrial': '#7d766c', 'interior-lab': '#c9d3d9', 'interior-civic': '#b8a78a', 'interior-home': '#cdb08f', 'interior-dark': '#2a2f3a' };
const STAGE_GROUND_COLOUR = { sand: '#d9c28a', snow: '#eef3f8', concrete: '#9aa0a8', wood: '#b28a5e' };

function stageCamera(spec, samples) {
  const { width, zoom, focus_y } = spec.stage, mode = spec.camera.mode;
  return samples.map(({ t }) => {
    const ease = (1 - Math.cos(2 * Math.PI * t)) / 2;                     // 0 -> 1 -> 0, so every mode loops seamlessly
    const w = mode === 'push-in' ? lerp(zoom * 1.25, zoom * 0.85, ease) : zoom;
    const lo = Math.min(w / 2, width / 2), hi = Math.max(width - w / 2, width / 2);
    const cx = mode === 'pan' ? lerp(lo, hi, ease) : width / 2;
    return { cx, cy: focus_y, w, h: (w * AIR.h) / AIR.w };
  });
}

function skyline(rand, x0, x1, base, hMin, hMax, colour, window) {
  let out = '';
  for (let x = x0; x < x1;) {
    const w = lerp(60, 130, rand()), h = lerp(hMin, hMax, rand());
    out += `<rect x="${fmt(x)}" y="${fmt(base - h)}" width="${fmt(w)}" height="${fmt(h + 40)}" fill="${colour}"/>`;
    if (window) for (let yy = base - h + 16; yy < base - 20; yy += 34) for (let xx = x + 10; xx < x + w - 14; xx += 24) if (rand() < 0.28) out += `<rect x="${fmt(xx)}" y="${fmt(yy)}" width="8" height="12" fill="${window}" fill-opacity="0.8"/>`;
    x += w + lerp(0, 14, rand());
  }
  return out;
}

function peaks(rand, x0, x1, base, hMin, hMax, colour, cap) {
  let out = '';
  for (let x = x0; x < x1;) {
    const w = lerp(260, 520, rand()), h = lerp(hMin, hMax, rand());
    out += `<path d="M${fmt(x)},${base + 40} L${fmt(x + w / 2)},${fmt(base - h)} L${fmt(x + w)},${base + 40} Z" fill="${colour}"/>`;
    if (cap) out += `<path d="M${fmt(x + w / 2 - w * 0.13)},${fmt(base - h + h * 0.26)} L${fmt(x + w / 2)},${fmt(base - h)} L${fmt(x + w / 2 + w * 0.13)},${fmt(base - h + h * 0.26)} L${fmt(x + w / 2 + w * 0.04)},${fmt(base - h + h * 0.2)} L${fmt(x + w / 2 - w * 0.03)},${fmt(base - h + h * 0.27)} Z" fill="${cap}"/>`;
    x += w * lerp(0.5, 0.8, rand());
  }
  return out;
}

function buildStage(spec, atom) {
  const P = paletteFor(spec);
  const rand = rng(spec.seed);
  const D = spec.motion.duration;
  const S = LOOP(90);
  const cam = stageCamera(spec, S);
  const kt = keyTimes(S.length);
  const used = new Set(), defs = [], usedVariants = {};
  const defOf = (id, variant) => {
    const key = 'a-' + id + (variant ? '--' + variant : '');
    if (variant) (usedVariants[id] = usedVariants[id] || new Set()).add(variant);
    if (!defs.some((d) => d.startsWith(`<g id="${key}"`))) {
      const use = (i) => { used.add(i); for (const r of atom.byId[i].requires || []) use(r); };
      use(id);
      defs.push(`<g id="${key}">${propInner(atom.byId[id], P, variant)}</g>`);
    }
    return key;
  };
  const { width, zoom, focus_y } = spec.stage, time = spec.theme.time;
  const interior = spec.backdrop.startsWith('interior-');
  const dim = ROOM_DIM[time], X0 = -2400, X1 = width + 2400;
  const procedural = ['camera path'];
  let back = '';

  if (interior) {
    const wall = mix(mix(STAGE_INTERIOR_TINT[spec.backdrop], P.structure, 0.25), P.dark, dim), H = 620;
    procedural.push('interior walls', 'ambient shading');
    back += `<rect x="${X0}" y="-2400" width="${X1 - X0}" height="4800" fill="${P.dark}"/><rect x="0" y="${-H}" width="${width}" height="${H}" fill="${wall}"/>`;
    const line = `stroke="${P.dark}" stroke-opacity="0.16" stroke-width="3" fill="none"`;
    if (spec.backdrop === 'interior-office') for (let x = 140; x < width; x += 300) back += `<rect x="${x}" y="-470" width="200" height="150" fill="${P.skyBot}" stroke="${P.dark}" stroke-width="6"/><path d="M${x + 100},-470 V-320" ${line}/>`;
    else if (spec.backdrop === 'interior-industrial') for (let x = 0; x < width; x += 220) back += `<path d="M${x},${-H} L${x + 110},-440 L${x + 220},${-H} M${x},-440 H${x + 220}" ${line}/>`;
    else if (spec.backdrop === 'interior-lab') for (let x = 0; x < width; x += 120) back += `<path d="M${x},${-H} V0" ${line}/>`;
    else if (spec.backdrop === 'interior-civic') for (let x = 120; x < width; x += 340) back += `<path d="M${x},0 V-380 A60,60 0 0 1 ${x + 120},-380 V0" ${line}/><rect x="${x - 14}" y="-420" width="148" height="18" fill="${P.dark}" fill-opacity="0.14"/>`;
    else if (spec.backdrop === 'interior-home') {                       // wallpaper stripes, picture rail, skirting board
      for (let x = 0; x < width; x += 90) back += `<rect x="${x}" y="${-H}" width="45" height="${H}" fill="${P.dark}" fill-opacity="0.045"/>`;
      back += `<path d="M0,-470 H${width}" ${line}/><rect x="0" y="-46" width="${width}" height="46" fill="${P.dark}" fill-opacity="0.14"/><path d="M0,-46 H${width}" fill="none" stroke="${P.dark}" stroke-opacity="0.3" stroke-width="3"/>`;
    }
    else for (let x = 200; x < width; x += 520) back += `<path d="M${x - 40},${-H} L${x - 260},0 L${x + 180},0 L${x + 40},${-H} Z" fill="${P.window}" fill-opacity="0.06"/>`;
    back += `<rect x="0" y="${-H}" width="${width}" height="70" fill="${P.dark}" fill-opacity="0.35"/>`;
  } else {
    if (spec.backdrop === 'space') {
      back += `<rect x="${X0}" y="-3600" width="${X1 - X0}" height="3700" fill="#03050c"/>`;
      let stars = '';
      for (let i = 0; i < 140; i++) stars += `<circle cx="${fmt(lerp(-800, width + 800, rand()))}" cy="${fmt(-lerp(20, zoom * 1.1, rand()))}" r="${fmt(lerp(1, 2.8, rand()))}" fill="#ffffff" fill-opacity="${fmt2(lerp(0.4, 0.95, rand()))}">${i % 6 === 0 ? `<animate attributeName="fill-opacity" values="0.9;0.25;0.9" dur="${fmt(lerp(2, 5, rand()))}s" begin="-${fmt(rand() * 4)}s" repeatCount="indefinite"/>` : ''}</circle>`;
      back += stars;
      procedural.push('star field');
    } else {
      back += `<defs><linearGradient id="skyg" gradientUnits="userSpaceOnUse" x1="0" y1="${fmt(-zoom * 0.9)}" x2="0" y2="0"><stop offset="0" stop-color="${P.skyTop}"/><stop offset="1" stop-color="${P.skyBot}"/></linearGradient></defs><rect x="${X0}" y="-4000" width="${X1 - X0}" height="4100" fill="url(#skyg)"/>`;
      procedural.push('sky gradient');
      if (P.stars) {
        for (let i = 0; i < 90; i++) back += `<circle cx="${fmt(lerp(-800, width + 800, rand()))}" cy="${fmt(-lerp(zoom * 0.25, zoom * 1.1, rand()))}" r="${fmt(lerp(0.8, 2.2, rand()))}" fill="#ffffff" fill-opacity="${fmt2(lerp(0.4, 0.95, rand()))}"/>`;
        procedural.push('stars');
      }
      const cel = P.celestial, celId = defOf(cel);
      back += `<use href="#${celId}" transform="translate(${fmt(width * 0.78)} ${fmt(-zoom * 0.42)}) scale(${fmt2((zoom / AIR.w) * (cel === 'sun' ? 1 : 0.9))})"/>`;
      const nCloud = { clear: 4, cloudy: 9, overcast: 15 }[spec.theme.weather], cloudId = defOf('cloud-cumulus');
      for (let i = 0; i < nCloud; i++) {
        const drift = lerp(-90, 90, rand());
        back += `<g opacity="${fmt2(lerp(0.75, 0.97, rand()))}"><animateTransform attributeName="transform" type="translate" values="0 0;${fmt(drift)} 0;0 0" dur="${D}s" repeatCount="indefinite"/><use href="#${cloudId}" transform="translate(${fmt(lerp(-400, width + 400, rand()))} ${fmt(-zoom * lerp(0.22, 0.6, rand()))}) scale(${fmt2((zoom / AIR.w) * lerp(0.6, 1.5, rand()))})"/></g>`;
      }
      procedural.push('cloud placement');
    }
    const bd = spec.backdrop, dusk = (c) => mix(c, P.dark, time === 'night' ? 0.55 : time === 'dusk' ? 0.25 : 0.05);
    if (bd === 'sky-city') { back += skyline(rand, X0 / 2, X1 / 2 + width, 0, 160, 420, mix(P.hillFar, P.structure, 0.3), null) + skyline(rand, X0 / 2, X1 / 2 + width, 0, 90, 250, mix(P.hillNear, P.dark, 0.25), P.stars ? P.window : null); procedural.push('city skyline'); }
    else if (bd === 'sky-hills') { back += hills(rand, X0, X1, 0, 80, 240, P.hillFar) + hills(rand, X0, X1, 0, 30, 120, P.hillNear); procedural.push('hill silhouettes'); }
    else if (bd === 'sky-mountains') { back += peaks(rand, X0, X1, 0, 260, 620, dusk('#6f7f95'), '#f2f6fa') + hills(rand, X0, X1, 0, 30, 110, P.hillNear); procedural.push('mountain silhouettes'); }
    else if (bd === 'sky-desert') { back += hills(rand, X0, X1, 0, 40, 160, dusk('#cf9d62')) + hills(rand, X0, X1, 0, 10, 70, dusk('#dcb070')); procedural.push('dune silhouettes'); }
    else if (bd === 'sky-arctic') { back += peaks(rand, X0, X1, 0, 120, 340, dusk('#b7cbe0'), '#ffffff') + hills(rand, X0, X1, 0, 20, 80, dusk('#e3edf6')); procedural.push('ice silhouettes'); }
    else if (bd === 'sky-sea') { back += `<rect x="${X0}" y="-70" width="${X1 - X0}" height="90" fill="${P.sea}"/><path d="M${X0},-40 H${X1}" fill="none" stroke="#ffffff" stroke-opacity="0.35" stroke-width="3" stroke-dasharray="26 40"><animate attributeName="stroke-dashoffset" values="0;-66" dur="3s" repeatCount="indefinite"/></path>`; procedural.push('sea horizon'); }
  }

  /* ground */
  let ground = '';
  if (spec.ground !== 'none') {
    const gc = spec.ground === 'grass' ? P.grass : spec.ground === 'road' ? P.runway : spec.ground === 'water' ? P.sea : mix(STAGE_GROUND_COLOUR[spec.ground], P.dark, dim);
    ground += `<rect x="${X0}" y="0" width="${X1 - X0}" height="1400" fill="${gc}"/><path d="M${X0},0 H${X1}" fill="none" stroke="${P.dark}" stroke-opacity="0.35" stroke-width="4"/>`;
    if (spec.ground === 'road') ground += `<path d="M${X0},70 H${X1}" fill="none" stroke="#ffffff" stroke-opacity="0.8" stroke-width="6" stroke-dasharray="60 50"/>`;
    if (spec.ground === 'water') ground += `<path d="M${X0},30 H${X1}" fill="none" stroke="#ffffff" stroke-opacity="0.35" stroke-width="3" stroke-dasharray="26 40"><animate attributeName="stroke-dashoffset" values="0;-66" dur="3s" repeatCount="indefinite"/></path><path d="M${X0},80 H${X1}" fill="none" stroke="#ffffff" stroke-opacity="0.25" stroke-width="3" stroke-dasharray="18 52"><animate attributeName="stroke-dashoffset" values="0;70" dur="4s" repeatCount="indefinite"/></path>`;
    procedural.push('ground plane');
  }

  /* placed props */
  let scenery = '', cones = '';
  const glow = time === 'night' ? 0.17 : time === 'day' ? 0.06 : 0.11;
  const sketches = [];
  const sketchMarkup = (list) => { const marks = list.map(sketchElement); sketches.push({ elements: list.length, sha256: sha256Hex(list.join('\n')) }); return marks.join(''); };
  for (const it of spec.scenery) {
    if (it.sketch) {                                            // agent-drawn: validated primitives, origin at the ground point like a prop
      const sc = it.scale === undefined ? 1 : it.scale;
      scenery += `<g transform="translate(${fmt(it.x)} ${fmt(it.y === undefined ? 0 : it.y)}) scale(${fmt2(it.flip ? -sc : sc)} ${fmt2(sc)})">${sketchMarkup(it.sketch)}</g>`;
      continue;
    }
    const a = atom.byId[it.prop].anchors || {};
    const y = it.y !== undefined ? it.y : a.base_y !== undefined ? a.base_y : 0;
    const sc = it.scale === undefined ? 1 : it.scale, sx = it.flip ? -sc : sc;
    if (it.prop === 'ceiling-light') cones += `<path d="M${fmt(it.x - 14)},${fmt(y)} L${fmt(it.x - 170)},0 L${fmt(it.x + 170)},0 L${fmt(it.x + 14)},${fmt(y)} Z" fill="${P.window}" fill-opacity="${glow}"/>`;
    scenery += `<use href="#${defOf(it.prop, it.variant)}" transform="translate(${fmt(it.x)} ${fmt(y)}) scale(${fmt2(sx)} ${fmt2(sc)})"/>`;
  }
  if (cones) procedural.push('light cones');

  /* actors */
  let actors = '';
  for (const a of spec.actors) {
    const id = a.sketch ? null : defOf(a.prop, a.variant), begin = `-${fmt2(a.phase * a.period)}s`, dur = `${a.period}s`;
    const skMarks = a.sketch ? sketchMarkup(a.sketch) : '';
    const sc = a.scale === undefined ? 1 : a.scale, dir = a.x1 < a.x0 ? -1 : 1, rep = `dur="${dur}" begin="${begin}" repeatCount="indefinite"`;
    const inner = (flip) => a.sketch ? `<g transform="scale(${fmt2(flip * sc)} ${fmt2(sc)})">${skMarks}</g>` : `<use href="#${id}" transform="scale(${fmt2(flip * sc)} ${fmt2(sc)})"/>`;
    if (a.motion === 'walk') {
      actors += `<g><animateTransform attributeName="transform" type="translate" values="${fmt(a.x0)} ${fmt(a.y)};${fmt(a.x1)} ${fmt(a.y)};${fmt(a.x0)} ${fmt(a.y)}" keyTimes="0;0.5;1" ${rep}/>` +
        `<g><animateTransform attributeName="transform" type="scale" values="${dir} 1;${-dir} 1" keyTimes="0;0.5" calcMode="discrete" ${rep}/>${inner(1)}</g></g>`;
    } else if (a.motion === 'ride' || a.motion === 'drive' || a.motion === 'fly') {
      const bob = a.motion === 'fly' ? `<animateTransform attributeName="transform" type="translate" values="0 0;0 ${fmt(-(a.ry === undefined ? 14 : a.ry))};0 0" dur="${fmt(a.period / 3)}s" begin="${begin}" repeatCount="indefinite"/>` : '';
      actors += `<g><animateTransform attributeName="transform" type="translate" values="${fmt(a.x0)} ${fmt(a.y)};${fmt(a.x1)} ${fmt(a.y)}" ${rep}/><animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.04;0.96;1" ${rep}/><g>${bob}${inner(dir)}</g></g>`;
    } else if (a.motion === 'hover') {
      const ry = a.ry === undefined ? 14 : a.ry, mx = (a.x0 + a.x1) / 2;
      actors += `<g><animateTransform attributeName="transform" type="translate" values="${fmt(a.x0)} ${fmt(a.y)};${fmt(mx)} ${fmt(a.y - ry)};${fmt(a.x1)} ${fmt(a.y)};${fmt(mx)} ${fmt(a.y + ry)};${fmt(a.x0)} ${fmt(a.y)}" ${rep}/>${inner(dir)}</g>`;
    } else {
      const cx = (a.x0 + a.x1) / 2, rx = Math.abs(a.x1 - a.x0) / 2, ry = a.ry === undefined ? 60 : a.ry, N = 24;
      const pts = Array.from({ length: N + 1 }, (_, i) => `${fmt(cx + rx * Math.cos((2 * Math.PI * i) / N))} ${fmt(a.y + ry * Math.sin((2 * Math.PI * i) / N))}`);
      actors += `<g><animateTransform attributeName="transform" type="translate" values="${pts.join(';')}" ${rep}/>${inner(1)}</g>`;
    }
  }
  procedural.push('actor motion');
  if (sketches.length) procedural.push('agent-drawn sketches (validated SVG primitives)');

  const shade = interior && ROOM_SHADE[time] ? `<rect x="0" y="-620" width="${width}" height="1020" fill="${P.dark}" fill-opacity="${ROOM_SHADE[time]}"/>` : '';
  return wrapScene({ spec, atom, used, usedVariants, procedural, cam, kt, D, defs, S, body: `<g id="world">${back}${ground}${scenery}${actors}${shade}${cones}</g>`, extra: { preset: spec.preset || null }, sketches });
}

function buildScene(specIn, atom) {
  const v = validateSpec(specIn, atom);
  if (!v.ok) throw new Error('Invalid scene spec:\n' + v.errors.join('\n'));
  const spec = v.spec;
  if (spec.scene === 'stage') return buildStage(spec, atom);
  if (INTERIOR.includes(spec.scene)) return buildInterior(spec, atom);
  const P = paletteFor(spec);
  const rand = rng(spec.seed);
  const D = spec.motion.duration;
  const traj = trajectory(spec);
  const S = traj.samples;
  const cam = cameraPath(spec, S);
  const kt = keyTimes(S.length);
  const used = new Set();
  const use = (id) => { used.add(id); for (const r of atom.byId[id].requires || []) use(r); return atom.byId[id]; };
  const isLaunch = spec.scene === 'launch';
  const procedural = isLaunch ? ['sky gradient', 'ground plane', 'launch smoke', 'trajectory + camera path'] : ['sky gradient', 'ground plane', 'runway markings', 'plane shadow', 'trajectory + camera path'];

  const defs = [];
  const usedVariants = {};
  const defOf = (id, variant) => {
    const key = 'a-' + id + (variant ? '--' + variant : '');
    if (variant) (usedVariants[id] = usedVariants[id] || new Set()).add(variant);
    if (!defs.some((d) => d.startsWith(`<g id="${key}"`))) defs.push(`<g id="${key}">${propInner(use(id), P, variant)}</g>`);
    return key;
  };

  const minX = Math.min(...cam.map((c) => c.cx - c.w / 2)) - 400;
  const maxX = Math.max(...cam.map((c) => c.cx + c.w / 2)) + 400;
  const maxW = Math.max(...cam.map((c) => c.w));
  const wide = maxX - minX;

  /* --- pinned sky (parallax 0): translate to camera centre, scale with zoom --- */
  const darken = (from, to) => isLaunch ? `<animate attributeName="stop-color" values="${from};${from};${to}" keyTimes="0;${fmt2(traj.tLift)};1" dur="${D}s" repeatCount="indefinite"/>` : '';
  let sky = `<defs><linearGradient id="skyg" gradientUnits="userSpaceOnUse" x1="0" y1="-254" x2="0" y2="95"><stop offset="0" stop-color="${P.skyTop}">${darken(P.skyTop, '#03050c')}</stop><stop offset="1" stop-color="${P.skyBot}">${darken(P.skyBot, mix(P.skyBot, '#03050c', 0.7))}</stop></linearGradient></defs>`;
  sky += `<rect x="-800" y="-500" width="1600" height="1000" fill="url(#skyg)"/>`;
  if (P.stars) {
    let stars = '';
    for (let i = 0; i < 70; i++) {
      const sx = lerp(-450, 450, rand()), sy = lerp(-253, 40, rand()), r = lerp(0.6, 1.6, rand());
      stars += `<circle cx="${fmt(sx)}" cy="${fmt(sy)}" r="${fmt(r)}" fill="#ffffff" fill-opacity="${fmt2(lerp(0.4, 0.95, rand()))}">${i % 5 === 0 ? `<animate attributeName="fill-opacity" values="0.9;0.25;0.9" dur="${fmt(lerp(2, 5, rand()))}s" begin="-${fmt(rand() * 4)}s" repeatCount="indefinite"/>` : ''}</circle>`;
    }
    sky += stars;
    procedural.push('stars');
  }
  const cel = P.celestial;
  const celId = defOf(cel);
  sky += `<use href="#${celId}" transform="translate(${P.sunPos[0]} ${P.sunPos[1]}) scale(${cel === 'sun' ? 1 : 0.9})"/>`;
  const skyLayer = `<g><animateTransform attributeName="transform" type="translate" values="${vals(cam.map((c) => `${fmt(c.cx)} ${fmt(c.cy)}`))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/>` +
    `<g><animateTransform attributeName="transform" type="scale" values="${vals(cam.map((c) => fmt2(c.w / AIR.w)))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/>${sky}</g></g>`;

  /* --- parallax layer helper: content is drawn in layer space, shifted by cx*(1-k) --- */
  const layer = (k, inner) => `<g><animateTransform attributeName="transform" type="translate" values="${vals(cam.map((c) => `${fmt(c.cx * (1 - k))} 0`))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/>${inner}</g>`;
  const layerRange = (k) => [k * Math.min(...cam.map((c) => c.cx)) - maxW / 2 - 300, k * Math.max(...cam.map((c) => c.cx)) + maxW / 2 + 300];

  let far = '';
  if (spec.theme.setting === 'coast') {
    const [a, b] = layerRange(0.9);
    procedural.push('sea + wave shimmer');
    far = layer(0.9, `<rect x="${fmt(a)}" y="-96" width="${fmt(b - a)}" height="70" fill="${P.sea}"/>` +
      `<path d="M${fmt(a)},-70 H${fmt(b)}" fill="none" stroke="#ffffff" stroke-opacity="0.35" stroke-width="3" stroke-dasharray="26 40"><animate attributeName="stroke-dashoffset" values="0;-66" dur="3s" repeatCount="indefinite"/></path>` +
      `<path d="M${fmt(a)},-50 H${fmt(b)}" fill="none" stroke="#ffffff" stroke-opacity="0.25" stroke-width="2" stroke-dasharray="18 52"><animate attributeName="stroke-dashoffset" values="0;70" dur="4s" repeatCount="indefinite"/></path>`);
  } else {
    const [a1, b1] = layerRange(0.5), [a2, b2] = layerRange(0.8);
    procedural.push('hill silhouettes');
    far = layer(0.5, hills(rand, a1, b1, -28, 90, 230, P.hillFar)) + layer(0.8, hills(rand, a2, b2, -28, 40, 130, P.hillNear));
  }

  /* --- clouds (world space, drifting) --- */
  const cloudCount = { clear: 5, cloudy: 14, overcast: 22 }[spec.theme.weather] * (isLaunch ? 2 : 1);
  const cloudId = defOf('cloud-cumulus');
  let clouds = '';
  for (let i = 0; i < cloudCount; i++) {
    const cx = lerp(minX, maxX, rand()), cyy = -lerp(190, isLaunch ? 1700 : 1150, rand() ** 0.8), sc = lerp(0.6, 1.7, rand());
    const drift = lerp(-70, 70, rand());
    clouds += `<g opacity="${fmt2(lerp(0.75, 0.97, rand()))}"><animateTransform attributeName="transform" type="translate" values="0 0;${fmt(drift)} 0;0 0" dur="${D}s" repeatCount="indefinite"/><use href="#${cloudId}" transform="translate(${fmt(cx)} ${fmt(cyy)}) scale(${fmt2(sc)})"/></g>`;
  }
  procedural.push('cloud placement');

  /* --- ground, runway --- */
  const rwA = -300, rwB = 2700;
  let ground = `<rect x="${fmt(minX)}" y="-30" width="${fmt(wide)}" height="1100" fill="${P.grass}"/>` +
    `<rect x="${fmt(minX)}" y="30" width="${fmt(wide)}" height="1100" fill="${P.verge}"/>` +
    (isLaunch ? `<rect x="${LAUNCH.x - 420}" y="-4" width="840" height="30" fill="${P.runway}"/>` :
      `<rect x="${rwA}" y="-8" width="${rwB - rwA}" height="38" fill="${P.runway}"/>` +
      `<path d="M${rwA},-6 H${rwB} M${rwA},28 H${rwB}" fill="none" stroke="#ffffff" stroke-opacity="0.75" stroke-width="2"/>` +
      `<path d="M${rwA + 40},${GY + 1} H${rwB - 40}" fill="none" stroke="#ffffff" stroke-opacity="0.85" stroke-width="3" stroke-dasharray="46 38"/>` +
      `<path d="M${rwA + 10},4 H${rwA + 110} M${rwA + 10},${GY + 8} H${rwA + 110} M${rwA + 10},18 H${rwA + 110} M${rwA + 10},24 H${rwA + 110}" fill="none" stroke="#ffffff" stroke-opacity="0.8" stroke-width="3"/>`);

  /* --- scenery + trees + runway lights --- */
  let scenery = '';
  const treeId = defOf(spec.theme.setting === 'coast' ? 'palm-tree' : 'conifer');
  for (let i = 0; i < spec.decor.trees; i++) {
    const tx = lerp(-250, 2900, rand()), sc = lerp(0.7, 1.35, rand());
    scenery += `<use href="#${treeId}" transform="translate(${fmt(tx)} -27) scale(${fmt2(sc)})"/>`;
  }
  for (const it of spec.scenery) {
    const baseY = it.y !== undefined ? it.y : atom.byId[it.prop].anchors.base_y !== undefined ? atom.byId[it.prop].anchors.base_y : -28;
    if (isLaunch && it.prop === 'gantry-arm') {
      const a = fmt2(traj.tIgnite), b = fmt2(traj.tIgnite + 0.05);
      scenery += `<g transform="translate(${fmt(it.x)} ${fmt(baseY)})"><g><animateTransform attributeName="transform" type="rotate" values="0;0;-78;-78" keyTimes="0;${a};${b};1" dur="${D}s" repeatCount="indefinite"/><use href="#${defOf(it.prop)}"/></g></g>`;
      continue;
    }
    scenery += `<use href="#${defOf(it.prop, it.variant)}" transform="translate(${fmt(it.x)} ${fmt(baseY)})"/>`;
  }
  const terminal = spec.scenery.find((it) => it.prop === 'terminal-building');
  if (terminal) {
    scenery += `<g><rect x="${fmt(terminal.x - 34)}" y="-128" width="68" height="20" rx="3" fill="${P.dark}"/><text x="${fmt(terminal.x)}" y="-113.5" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-weight="700" font-size="14" letter-spacing="2" fill="${P.window}">${esc(spec.airport.code)}</text></g>`;
  }
  let lights = '';
  if (spec.scene === 'landing') {
    const approachId = defOf('approach-lights');
    for (let i = 0, x = -1400; x <= -320; x += 100, i++) {
      const chase = P.lights ? `<animate attributeName="opacity" values="1;0.2;0.2;1" keyTimes="0;0.15;0.85;1" dur="1.2s" begin="${fmt2((10 - i) * 0.1)}s" repeatCount="indefinite"/>` : '';
      lights += `<use href="#${approachId}" transform="translate(${x} ${GY + 6})">${chase}</use>`;
    }
    procedural.push('approach-light placement');
  }
  if (P.lights && !isLaunch) {
    const lightId = defOf('runway-light');
    let i = 0;
    for (let x = rwA + 30; x <= rwB - 30; x += 130, i++) {
      for (const y of [-11, 33]) lights += `<use href="#${lightId}" transform="translate(${x} ${y})"><animate attributeName="opacity" values="1;0.25;0.25;1" keyTimes="0;0.2;0.9;1" dur="1.6s" begin="${fmt2(i * 0.07)}s" repeatCount="indefinite"/></use>`;
    }
    procedural.push('runway light sequencing');
  }

  /* --- shadow, plane (translate + pitch), gear --- */
  const shadow = isLaunch ? '' : `<ellipse cy="${GY + 9}" ry="6" fill="#000000"><animate attributeName="cx" values="${vals(S.map((s) => fmt(s.x)))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/><animate attributeName="rx" values="${vals(S.map((s) => fmt(120 / (1 + s.alt / 260))))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/><animate attributeName="opacity" values="${vals(S.map((s) => fmt2(0.32 / (1 + s.alt / 150))))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/></ellipse>`;
  const ac = use(spec.aircraft.prop);
  const gearEntry = ac.requires.length ? atom.byId[ac.requires[0]] : null;
  const [px, py] = ac.anchors.pivot;
  const hy = gearEntry ? gearEntry.anchors.hinge[1] : 0;
  const takeoff = spec.scene === 'takeoff';
  const tg0 = takeoff ? traj.tLift + 0.03 : null, tg1 = takeoff ? traj.tLift + 0.09 : null;
  let gear = '';
  if (takeoff) {
    gear = `<g transform="translate(0 ${hy})"><g><animateTransform attributeName="transform" type="scale" values="1 1;1 1;1 0.02;1 0.02" keyTimes="0;${fmt2(tg0)};${fmt2(tg1)};1" dur="${D}s" repeatCount="indefinite"/>` +
      `<animate attributeName="opacity" values="1;1;0;0" keyTimes="0;${fmt2(tg0)};${fmt2(tg1)};1" dur="${D}s" repeatCount="indefinite"/><g transform="translate(0 ${-hy})">${propInner(gearEntry, P)}</g></g></g>`;
  } else if (spec.scene === 'landing') {
    gear = propInner(gearEntry, P);            // gear down for the whole approach and roll-out
  } else if (gearEntry) {
    used.delete(gearEntry.id);                 // cruise fly-by: gear is up and never drawn
  }
  let plume = '', smoke = '';
  if (isLaunch) {
    const ig = fmt2(traj.tIgnite), ig2 = fmt2(traj.tIgnite + 0.03);
    plume = `<g transform="translate(0 6)"><g><animateTransform attributeName="transform" type="scale" values="0.001 0.001;0.001 0.001;1 1;1 1" keyTimes="0;${ig};${ig2};1" dur="${D}s" repeatCount="indefinite"/><use href="#${defOf('exhaust-plume')}"/></g></g>`;
    for (let i = 0; i < 9; i++) {
      const dir = i % 2 ? 1 : -1, reach = lerp(120, 460, rand()), rise = lerp(20, 90, rand()), r1 = lerp(46, 84, rand());
      const t0 = traj.tIgnite + i * 0.012, t1 = Math.min(0.97, t0 + 0.4);
      const kts = `0;${fmt2(t0)};${fmt2((t0 + t1) / 2)};${fmt2(t1)};1`;
      smoke += `<circle cy="-6" fill="${P.cloud}" fill-opacity="0"><animate attributeName="cx" values="${LAUNCH.x};${LAUNCH.x};${fmt(LAUNCH.x + dir * reach * 0.5)};${fmt(LAUNCH.x + dir * reach)};${fmt(LAUNCH.x + dir * reach)}" keyTimes="${kts}" dur="${D}s" repeatCount="indefinite"/>` +
        `<animate attributeName="cy" values="-6;-6;${fmt(-6 - rise * 0.6)};${fmt(-6 - rise)};${fmt(-6 - rise)}" keyTimes="${kts}" dur="${D}s" repeatCount="indefinite"/>` +
        `<animate attributeName="r" values="8;8;${fmt(r1 * 0.7)};${fmt(r1)};${fmt(r1)}" keyTimes="${kts}" dur="${D}s" repeatCount="indefinite"/>` +
        `<animate attributeName="fill-opacity" values="0;0;0.75;0;0" keyTimes="${kts}" dur="${D}s" repeatCount="indefinite"/></circle>`;
    }
  }
  const plane = `<g id="plane"><animateTransform attributeName="transform" type="translate" values="${vals(S.map((s) => `${fmt(s.x)} ${fmt(GY - s.alt)}`))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/>` +
    `<g><animateTransform attributeName="transform" type="rotate" values="${vals(S.map((s) => `${fmt(-s.pitch)} ${px} ${py}`))}" keyTimes="${kt}" dur="${D}s" repeatCount="indefinite"/>${gear}${plume}${propInner(ac, P)}</g></g>`;

  return wrapScene({
    spec, atom, used, usedVariants, procedural, cam, kt, D, defs, S,
    body: `${skyLayer}${far}<g id="world">${clouds}${ground}${scenery}${lights}${shadow}${smoke}${plane}</g>`,
    extra: { tLift: traj.tLift, tRotate: traj.tRotate, tTouch: traj.tTouch, tFlare: traj.tFlare, tIgnite: traj.tIgnite, gearRetract: takeoff ? [tg0, tg1] : null },
  });
}

  var ATOM = null, ATOM_FULL = null, CORE = null;
  function hx(h) { return typeof h === 'string' ? h.replace('.', '') : h; }        // digests are stored as two 32-hex halves joined by '.', see gen_scene_gs.split_hex
  function fixEntry(e) { var c = {}, k; for (k in e) c[k] = e[k]; c.sha256 = hx(e.sha256); return c; }
  function unpack(b) {
    var o = {}, k, t = {};
    for (k in b) o[k] = b[k];
    o.registry_sha256 = hx(b.registry_sha256);
    o.entries = b.entries.map(fixEntry);
    if (b.trusted_sha256) { for (k in b.trusted_sha256) t[k] = hx(b.trusted_sha256[k]); o.trusted_sha256 = t; }
    return o;
  }
  function core() {
    // SCENE_STAGE_DATA lives in atoms_scene_data.gs, read lazily so file load order does not matter. Some bundles leave it out
    // on purpose: say so instead of throwing a bare ReferenceError.
    if (typeof SCENE_STAGE_DATA === 'undefined') throw new Error('the scene kit data is not bundled on this surface (scenes render on Apps Script web and in the Worker)');
    if (!CORE) CORE = unpack(SCENE_STAGE_DATA);
    return CORE;
  }
  function hasFull() { return typeof SCENE_STAGE_FULL !== 'undefined'; }   // atoms_scene_full.gs: the whole kit, Worker module only
  function atom() {
    if (!ATOM) ATOM = atomFromBundle(core(), { skipSvgStructure: true });
    return ATOM;                                             // hashes were verified when the data was minted, and are re-checked here
  }
  function fullAtom() {
    if (!ATOM_FULL) ATOM_FULL = atomFromBundle({ schema: 1, registry_sha256: core().registry_sha256, allow: core().allow, layouts: core().layouts, entries: SCENE_STAGE_FULL.entries.map(fixEntry) }, { skipSvgStructure: true });
    return ATOM_FULL;
  }
  /* The bundle carries only the core props. A server (the Worker) attaches the further props one block needs as block._kit; each
   * must hash to the TRUSTED table baked into this file, so a payload cannot introduce SVG that was never vetted. */
  function kitAtom(kit) {
    var C = core(), trusted = C.trusted_sha256 || {}, have = {}, entries = C.entries.slice(), total = 0, i, e;
    if (!kit || !Array.isArray(kit.entries) || kit.entries.length > 300) throw new Error('the scene kit attachment is malformed');
    for (i = 0; i < C.entries.length; i++) have[C.entries[i].id] = true;
    for (i = 0; i < kit.entries.length; i++) {
      e = kit.entries[i];
      if (!e || typeof e.id !== 'string' || typeof e.svg !== 'string' || !trusted[e.id]) throw new Error('the scene kit attachment names a prop that is not in the kit');
      e = fixEntry(e);
      total += e.svg.length;
      if (total > 600000) throw new Error('the scene kit attachment is too large');
      if (sha256Hex(e.svg) !== trusted[e.id] || e.sha256 !== trusted[e.id]) throw new Error('scene kit prop ' + e.id + ' failed verification against the trusted hash table');
      if (!have[e.id]) { entries.push(e); have[e.id] = true; }
    }
    return atomFromBundle({ schema: 1, registry_sha256: C.registry_sha256, allow: C.allow, layouts: C.layouts, entries: entries }, { skipSvgStructure: true });
  }
  function atomFor(b) { if (b && b._kit) return kitAtom(b._kit); return hasFull() ? fullAtom() : atom(); }
  /** Worker side: the props this block needs that the bundle core does not carry, as an attachment (or null). Needs the full kit. */
  function kitFor(b) {
    if (!hasFull() || !b || typeof b !== 'object') return null;
    var want = {}, have = {}, byId = {}, out = [], seen = {}, C = core(), L = b.preset && C.layouts.layouts[b.preset];
    function add1(it) { if (it && typeof it.prop === 'string') want[it.prop] = true; }
    if (typeof b.asset === 'string') want[b.asset] = true;
    ['scenery', 'actors', 'scenery_add', 'actors_add'].forEach(function (k) { if (Array.isArray(b[k])) b[k].forEach(add1); });
    if (L) { if (b.scenery === undefined) L.scenery.forEach(add1); if (b.actors === undefined) L.actors.forEach(add1); }
    C.entries.forEach(function (e) { have[e.id] = true; });
    SCENE_STAGE_FULL.entries.forEach(function (e) { byId[e.id] = e; });
    function need(id) { if (seen[id] || !byId[id]) return; seen[id] = true; if (!have[id]) out.push(byId[id]); (byId[id].requires || []).forEach(need); }
    Object.keys(want).forEach(need);
    return out.length ? { schema: 1, entries: out } : null;
  }
  function specFromBlock(b) {
    // canonical key order, so the same logical spec always has the same spec_sha256 in its provenance
    var th = b.theme || {}, s = { version: 1, scene: 'stage' }, k;
    if (b.preset !== undefined) s.preset = b.preset;
    s.title = b.title !== undefined ? b.title : String(b.preset || 'Scene').slice(0, 80);
    s.seed = b.seed !== undefined ? b.seed : parseInt(sha256Hex(String(b.preset || s.title)).slice(0, 8), 16);
    s.theme = { time: th.time || 'day', weather: th.weather || 'clear', setting: th.setting || 'countryside' };
    s.motion = { duration: (b.motion && b.motion.duration) || 20 };
    for (k in b) if (Object.prototype.hasOwnProperty.call(b, k) && !Object.prototype.hasOwnProperty.call(s, k) && k !== 'type' && k !== '_kit') s[k] = b[k];
    if (s.preset === undefined) {                       // a layout written in full: a model may reasonably leave these out
      if (s.camera === undefined) s.camera = { mode: 'static' };
      if (s.scenery === undefined) s.scenery = [];
      if (s.actors === undefined) s.actors = [];
    }
    return s;
  }
  function figure(svg, title, extra) {
    svg = svg.replace(' width="1280" height="720"', ' style="width:100%;height:auto;display:block"');
    return '<figure class="a2ui-scene" style="margin:1rem 0;max-width:1280px;">' + svg +
      '<figcaption style="font-size:0.8rem;color:#64748b;margin-top:4px;">' + esc(title) + (extra || '') + '</figcaption></figure>';
  }
  function failure(e) {
    return '<div style="padding:12px 16px;border:1px solid #fca5a5;border-radius:8px;color:#991b1b;background:#fef2f2;font-size:0.85rem;white-space:pre-wrap;">scene_stage: ' + esc(e && e.message ? e.message : e) + '</div>';
  }
  /** scene_stage block -> HTML string (an animated SVG figure). */
  function render(b) {
    try { var r = buildScene(specFromBlock(b), atomFor(b)); return figure(r.svg, r.spec.title); } catch (e) { return failure(e); }
  }
  /** clipart block -> HTML string: one prop drawn on a transparent stage, at its own size. */
  function renderClipart(b) {
    try {
      var a = atomFor(b), e = a.byId[b.asset];
      if (!e) throw new Error(core().trusted_sha256[b.asset] ? 'clipart.asset ' + esc(b.asset) + ' is in the kit but not embedded on this surface: the server attaches it (render_surface and the Worker do)' : 'clipart.asset must be an id from the asset index (got ' + esc(b.asset) + ')');
      var r = renderPropPreview(a, b.asset, b.variant, b.time || 'day');
      var sc = b.scale === undefined ? 1 : Math.max(0.2, Math.min(5, Number(b.scale) || 1));
      var vb = r.viewBox.split(/\s+/).map(Number), w = Math.round(vb[2] * sc), flip = b.flip ? ' transform="scale(-1 1)" transform-origin="center"' : '';
      return '<figure class="a2ui-clipart" style="margin:0.5rem 0;display:inline-block;">' +
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' + r.viewBox + '" style="width:' + w + 'px;max-width:100%;height:auto;display:block" role="img" aria-label="' + esc(b.alt || e.name) + '"><g' + flip + '>' + r.markup + '</g></svg>' +
        (b.label ? '<figcaption style="font-size:0.8rem;color:#64748b;text-align:center;">' + esc(b.label) + '</figcaption>' : '') + '</figure>';
    } catch (err) { return failure(err); }
  }
  return { render: render, renderClipart: renderClipart, buildScene: buildScene, atom: atom, kitFor: kitFor, hasFull: hasFull, sha256Hex: sha256Hex, version: RENDERER_VERSION };
})();

_RENDERERS['scene_stage'] = function (b) { return SceneStage.render(b); };
_RENDERERS['clipart'] = function (b) { return SceneStage.renderClipart(b); };
