#!/usr/bin/env python3
"""gen_basic_icons.py — atoms/basic-catalog-icons.json -> apps-script-surface/gas-wired-renderer/atoms_v1_icons.gs

The A2UI Basic Catalog's Icon component names one of 59 built-in icons. One path-data table
(Material Symbols, Apache-2.0) serves both renderers: this writes the web renderer's copy; the
Android library copies the JSON into its assets at build time. tests/test_basic_catalog_coverage.py
fails if the .gs falls out of step with the JSON.

    python3 scripts/gen_basic_icons.py           # write
    python3 scripts/gen_basic_icons.py --check   # exit 1 if the .gs is stale
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "atoms" / "basic-catalog-icons.json"
OUT = ROOT / "apps-script-surface" / "gas-wired-renderer" / "atoms_v1_icons.gs"


def render() -> str:
    doc = json.loads(SRC.read_text(encoding="utf-8"))
    paths = {name: v["d"] for name, v in doc["icons"].items()}
    return ("// GENERATED by scripts/gen_basic_icons.py from atoms/basic-catalog-icons.json. Do not edit.\n"
            "// A2UI Basic Catalog Icon built-in names -> SVG path data. " + doc["_source"].split(" (")[0]
            + ", " + doc["_license"] + ".\n"
            "var _A2UI_ICON_VIEWBOX = " + json.dumps(doc["viewBox"]) + ";\n"
            "var _A2UI_ICON_PATHS = " + json.dumps(paths, separators=(",", ":")) + ";\n")


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run scripts/gen_basic_icons.py")
            sys.exit(1)
        print("atoms_v1_icons.gs up to date")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
