#!/usr/bin/env python3
"""Stamp atoms/brand-tokens.yaml into the site's CSS/logo and the private brand doc.

Outputs (never hand-edit):
  scripts/_brand_generated.py       BRAND_HASH, BRAND_TOKEN_CSS, BRAND_LOGO_HTML  (imported by
                                    generate_atom_pages.py and gen_trust_pages.py)
  ../a2ui-private/spec/brand.md     the block between <!-- brand:tokens:start/end --> (only when
                                    the private sibling is present; skipped silently in CI)

  python3 scripts/gen_brand.py          # write
  python3 scripts/gen_brand.py --check  # exit 1 if any output is stale
"""
import hashlib
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "atoms" / "brand-tokens.yaml"
PY_OUT = ROOT / "scripts" / "_brand_generated.py"
BRAND_MD = ROOT.parent / "a2ui-private" / "spec" / "brand.md"
START, END = "<!-- brand:tokens:start -->", "<!-- brand:tokens:end -->"


def build():
    d = yaml.safe_load(SRC.read_text())
    digest = hashlib.sha256(SRC.read_bytes()).hexdigest()[:8]

    def decls(m):
        return "".join(f"--{k}:{v};" for k, v in m.items())

    light = "  color-scheme:light;\n  " + "\n  ".join(
        decls({k: v for k, v in list(d["light"].items())[i:i + 4]})
        for i in range(0, len(d["light"]), 4)) + "\n  " + decls(d["aliases"])
    dark = "  color-scheme:dark;\n  " + "\n  ".join(
        decls({k: v for k, v in list(d["dark"].items())[i:i + 4]})
        for i in range(0, len(d["dark"]), 4))
    css = (f"/*brand-tokens:{digest}*/\n:root{{\n{light}\n}}\n"
           f":root[data-theme=\"dark\"]{{\n{dark}\n}}\n")

    els = []
    for e in d["logo"]["elements"]:
        attrs = " ".join(f'{k}="{v}"' for k, v in e.items() if k != "tag")
        els.append(f"<{e['tag']} {attrs}/>")
    logo = (f'<svg class="logo-atom" viewBox="{d["logo"]["viewBox"]}" aria-hidden="true">{"".join(els)}</svg>'
            f'<span><span class="grad">{d["wordmark"]["accent"]}</span>{d["wordmark"]["rest"]}</span>')

    py = (f'"""GENERATED by scripts/gen_brand.py from atoms/brand-tokens.yaml -- do not edit."""\n'
          f"BRAND_HASH = {digest!r}\n"
          f"BRAND_NAME = {d['name']!r}\n"
          f"BRAND_TOKEN_CSS = {css!r}\n"
          f"BRAND_LOGO_HTML = {logo!r}\n")

    def row(k, lv, dv):
        return f"| `--{k}` | `{lv}` | `{dv if dv is not None else '(same)'}` |"

    table = ["| token | light | dark |", "|---|---|---|"]
    for k, v in d["light"].items():
        table.append(row(k, v, d["dark"].get(k)))
    md = (f"{START}\n<!-- GENERATED by scripts/gen_brand.py from a2ui-catalogue/atoms/brand-tokens.yaml "
          f"(hash {digest}) -- edit the YAML, not this block. -->\n\n"
          f"Font: `{d['font_stack']}` · mono: `{d['mono_stack']}`\n\n" + "\n".join(table) + f"\n{END}")
    return py, md, digest


def main():
    py, md, digest = build()
    outs = {PY_OUT: py}
    brand_md = None
    if BRAND_MD.exists():
        cur = BRAND_MD.read_text()
        if START in cur and END in cur:
            brand_md = cur[:cur.index(START)] + md + cur[cur.index(END) + len(END):]
            outs[BRAND_MD] = brand_md
    if "--check" in sys.argv:
        stale = [str(p) for p, t in outs.items() if not p.exists() or p.read_text() != t]
        if stale:
            print("stale (run scripts/gen_brand.py):", *stale, sep="\n  ")
            return 1
        return 0
    for p, t in outs.items():
        p.write_text(t)
        print("wrote", p if p == BRAND_MD else p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
