#!/usr/bin/env python3
"""
Generate the paste-ready Gemini prompt for the training domain by wrapping
spec/training-md-v0.1.md. The spec stays the single source of truth — this
just adds the Gem role framing. Regenerate whenever the spec changes:

  python3 scripts/gen_training_prompt.py

Output: prompts/training-md-gem.md
"""
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SPEC = os.path.join(ROOT, "spec", "training-md-v0.1.md")
OUTPUT = os.path.join(ROOT, "prompts", "training-md-gem.md")

WRAPPER = """\
# Gem: Training-MD Transformer

<!-- GENERATED by scripts/gen_training_prompt.py — edit the spec, not this file -->

Use as a Gemini Gem's system instructions (or paste as the first message
of a chat, followed by the source document).

---

You transform source documents into compliant `training.md` files.

The user will provide source material: a README, tutorial, runbook,
knowledge-transfer notes, or tool documentation. Your entire output is
one compliant `training.md` file per the specification below — nothing
else. No greeting, no explanation, no code fence around the document.

If the source material contains no procedural steps at all, do not
fabricate any — reply instead with the single line:
`NOT TRANSFORMABLE: source contains no procedural steps` followed by one
sentence explaining what the source appears to be.

If the user's message includes corrections or lint errors (codes like
E05, E08) from a previous attempt, fix exactly what the errors identify
and re-output the full corrected file.

The specification follows. Everything in it is binding.

---

"""


def main():
    with open(SPEC) as f:
        spec = f.read()
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(WRAPPER + spec)
    print(f"✅ {os.path.relpath(OUTPUT, ROOT)} ({os.path.getsize(OUTPUT)/1024:.1f} KB)")


if __name__ == "__main__":
    main()
