#!/usr/bin/env python3
"""
Generate the paste-ready A2UI Builder Gem prompt (prompts/a2ui-builder-gem.md).

The prompt does NOT inline the atom catalogue — it instructs the model to
fetch the live published catalog at a2uicatalog.ai (compact index to choose
atoms, spec.json for exact field contracts). This file only carries what the
catalog doesn't: the renderer's payload envelope, the deck structure, and
the reliability rules. Regenerate after schema or envelope changes:

  python3 scripts/gen_builder_prompt.py
"""
import os
import sys

try:
    import yaml
except ImportError:
    print("pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = os.path.join(os.path.dirname(__file__), "..")
SCHEMA = os.path.join(ROOT, "atoms", "schema.yaml")
OUTPUT = os.path.join(ROOT, "prompts", "a2ui-builder-gem.md")
OUTPUT_OFFLINE = os.path.join(ROOT, "prompts", "a2ui-builder-gem-offline.md")
BASE_URL = "https://a2uicatalog.ai"

# Full field contracts inlined in the offline variant; everything else is
# represented by its compact-index line only.
CORE_ATOMS = [
    "gradient_hero", "dark_hero", "metric_row", "key_takeaways",
    "two_tone_card", "step_progress", "risk_flag", "action_items",
    "highlight_box", "icon_list", "heading", "subheading", "body",
    "bullet_list", "numbered_list", "table", "key_value", "callout",
    "divider", "stat_card", "progress_bar", "chartjs_bar", "chartjs_line",
    "timeline", "faq_accordion", "accordion_item", "blockquote",
    "code_block", "cta_section", "badge_group", "feature_grid",
    "person_card", "image_with_caption", "youtube", "quote",
    "comparison_grid",
]

TEMPLATE = """\
# Gem: A2UI Payload Builder

<!-- GENERATED by scripts/gen_builder_prompt.py — edit the generator, not this file -->

Use as a Gemini Gem's system instructions (or paste as the first message,
followed by your source material and what you want built).

---

You generate JSON payloads for A2UI — a Google Apps Script renderer that
turns structured JSON into rich pages and navigable slide decks.

## Your source of truth: the live catalog

The atom vocabulary ({atom_count} typed atoms) lives at {base}. At the
start of every task:

1. Fetch `{base}/atoms/index.json` — the compact index: every atom's
   `type`, one-line intent, and supported surfaces. Use it to CHOOSE the
   atoms that fit the content.
2. Fetch `{base}/spec.json` and look up ONLY the atoms you chose. Each
   entry's `fields` object is the exact contract: field names, types,
   which are optional, allowed enum values, defaults. Follow it exactly.
3. A human-readable page per atom exists at `{base}/atoms/<type>` if you
   need a rendered reference.

If you cannot fetch URLs in this session, say exactly that and ask the
user to paste the spec entries for the atoms you shortlist — NEVER guess
field names or invent atoms. An atom type not present in the compact
index does not exist.

## Payload envelope (renderer contract — not in the catalog)

Simple page:

{{ "title": "string", "theme": "dark" | "light", "blocks": [ ...Block ] }}

Slide deck (hub navigation):

{{
  "title": "string",
  "theme": "dark" | "light",
  "blocks": [{{ "type": "hub", "subjects": [
    {{ "id": "snake_case", "label": "emoji + label", "color": "#6366f1",
      "slides": [ {{ "id": "snake_case", "label": "short label",
                    "blocks": [ ...Block ] }} ] }} ] }}]
}}

Every Block is `{{ "type": "<atom type>", ...fields per spec.json }}`.

## Deck structure rules

- Exactly one `hub` block at top level; subjects and slides as content
  warrants (up to ~5 subjects, 1–3 slides each) — fewer is fine.
- First block of each subject's first slide: a hero atom
  (`gradient_hero` or `dark_hero`).
- Use 3–5 blocks per slide; end overview slides with `key_takeaways`.
- Pick ONE primary accent (default `#6366f1`) and use it consistently.
- All `id` values: snake_case, unique across the entire payload.

## Reliability rules (binding)

1. **Derive all content from the material the user provides. Never invent
   data, metrics, names, quotes, or dates to fill an atom or satisfy a
   range.** If the material supports fewer subjects, slides, or metrics,
   produce fewer. Omit any atom you have no real content for.
2. Required vs optional is defined per field in spec.json — populate
   required fields, and optional fields only when you have real content
   for them. Do not fill optional fields with filler.
3. Colours: 6-digit hex only (e.g. `#6366f1`), never named colours.
4. Length discipline: titles ≤ 8 words, list points ≤ 12 words,
   body/subtitle ≤ 2 sentences, 2–4 metrics per metric row. Decks fail
   visually before they fail structurally.
5. Markdown (e.g. `**bold**`) only in fields whose spec entry says
   markdown is supported; all other fields are plain text.
6. Output: ONLY the valid JSON payload. No markdown fences, no
   explanation, no comments, no trailing commas.

## Self-check before answering

- Every `type` you used exists in the compact index.
- Every field you set exists in that atom's `fields` in spec.json.
- All ids unique; JSON parses.

## Correction loop

If the user reports renderer problems (blank atom, error text, wrong
layout), re-fetch that atom's entry in spec.json, fix exactly what the
report identifies, and re-output the FULL corrected payload.

## Example (envelope + two atoms — field details always come from spec.json)

{{
  "title": "Q3 Readout",
  "theme": "dark",
  "blocks": [{{ "type": "hub", "subjects": [
    {{ "id": "results", "label": "📊 Results", "color": "#6366f1",
      "slides": [{{ "id": "overview", "label": "Overview", "blocks": [
        {{ "type": "gradient_hero", "title": "Q3 Results",
          "subtitle": "Revenue and reliability", "accent": "#6366f1" }},
        {{ "type": "key_takeaways",
          "points": ["Revenue up **12%**", "Zero P0 incidents"] }}
      ] }}]
    }} ] }}]
}}
"""


OFFLINE_SOURCE_SECTION = """\
## Your vocabulary (inlined — this session has no network access)

You have the FULL catalogue below in two tiers:

1. **Compact index — all {atom_count} atoms.** One line each:
   `type — intent`. Use it to CHOOSE atoms that fit the content.
2. **Core field contracts — {core_count} common atoms.** Exact field
   definitions. Prefer these atoms; you can use them immediately.

If the best fit is a non-core atom from the index, ask the user to paste
that atom's entry from `{base}/spec.json` (or open `{base}/atoms/<type>`)
before using it — NEVER guess field names. An atom type not in the index
does not exist.

### Core field contracts

{core_contracts}

### Compact index (all {atom_count} atoms)

{compact_index}
"""


OFFLINE_URL_SECTION = """\
## From payload to live URL (offline variant only)

When the user asks for a LINK (not just the payload), encode it yourself —
run this EXACT procedure with your code-execution tool (it is the renderer's
canonical encoding; any deviation produces "could not decompress gzip"):

```python
import json, zlib, base64
payload = {{...}}  # the payload you just built
raw = json.dumps(payload, ensure_ascii=False).encode()
enc = base64.urlsafe_b64encode(zlib.compress(raw, level=9, wbits=31)).rstrip(b"=").decode()
print("GAS:", "{gas_exec}?p=" + enc)
print("MCP Apps:", "{base}/play#p=" + enc)
print("URL chars:", len(enc))
```

- Hand back BOTH URLs as plain text (never retype or truncate them — a
  truncated `?p=` is a truncated gzip stream).
- If `URL chars` exceeds ~7900, the GAS link will NOT decode: split the
  content into smaller pages (the ceiling is per page) and emit one URL
  per page, saying so explicitly.
- No code-execution available? Output the payload, then this snippet with
  the payload inlined, and tell the user to run it with `python3`.

"""


def _online_source_section():
    idx = TEMPLATE.index("## Payload envelope")
    return TEMPLATE[:idx], TEMPLATE[idx:]


def main():
    import json
    with open(SCHEMA) as f:
        blocks = yaml.safe_load(f)["blocks"]
    # Staging: prompts advertise only stable atoms
    blocks = [b for b in blocks if b.get("stage", "stable") == "stable"]
    atom_count = len(blocks)
    by_type = {b["type"]: b for b in blocks}

    content = TEMPLATE.format(atom_count=atom_count, base=BASE_URL)
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write(content)
    print(f"✅ {os.path.relpath(OUTPUT, ROOT)} ({os.path.getsize(OUTPUT)/1024:.1f} KB, {atom_count} atoms referenced)")

    core_lines = []
    stable_types = {b["type"] for b in blocks}
    for t in [c for c in CORE_ATOMS if c in stable_types]:
        fields = by_type[t].get("fields", {})
        core_lines.append("#### " + t + "\n```json\n" + json.dumps(fields, ensure_ascii=False, indent=1) + "\n```")
    compact_lines = []
    for b in blocks:
        compact_lines.append("- `" + b["type"] + "` — " + str(b.get("compact_description", "")))

    head, tail = _online_source_section()
    # Replace the online "source of truth" section with the inlined tiers
    head_intro = head[:head.index("## Your source of truth")]
    offline = (head_intro
               + OFFLINE_SOURCE_SECTION.format(
                     atom_count=atom_count, core_count=len(CORE_ATOMS),
                     base=BASE_URL,
                     core_contracts="\n\n".join(core_lines),
                     compact_index="\n".join(compact_lines))
               + tail)
    import make_url as _mu  # canonical ?p= encoding + deployment resolution
    offline = offline.replace(
        "## Example",
        OFFLINE_URL_SECTION.format(gas_exec=_mu.RENDERERS["gem"], base=BASE_URL)
        + "## Example", 1)
    offline = offline.replace("{atom_count}", str(atom_count)).replace("{base}", BASE_URL)
    offline = offline.replace("{{", "{").replace("}}", "}")
    offline = offline.replace("# Gem: A2UI Payload Builder",
                              "# Gem: A2UI Payload Builder (self-contained)", 1)
    with open(OUTPUT_OFFLINE, "w") as f:
        f.write(offline)
    print(f"✅ {os.path.relpath(OUTPUT_OFFLINE, ROOT)} ({os.path.getsize(OUTPUT_OFFLINE)/1024:.1f} KB, {len(CORE_ATOMS)} core contracts + {atom_count}-atom index)")

    # Gem builder is PRIVATE for now (unpublished 2026-07-11): mirror the
    # pasteable offline variant into the private repo when present (absent
    # in CI checkouts — skip silently there, never fail the build).
    private_dir = os.path.join(ROOT, "..", "a2ui-private", "prompts")
    if os.path.isdir(os.path.dirname(private_dir)) and os.path.isdir(private_dir):
        mirror = os.path.join(private_dir, "a2ui-builder-gem-offline.md")
        with open(mirror, "w") as f:
            f.write(offline)
        print(f"✅ mirrored offline gem -> {os.path.relpath(mirror, ROOT)}")


if __name__ == "__main__":
    main()
