#!/usr/bin/env python3
"""gen_openapi.py — compile public/openapi.json and public/llms.txt.

Both documents state the size of the catalogue ("474 typed UI atoms"), and
both were originally hand-written with that number baked in — so every atom
added silently made the two most agent-facing documents on the site wrong.
They are compiled here from public/spec.json (the PUBLISHED artifact, so the
count already reflects the stage/visibility filter) exactly like
gen_compat_matrix.py and gen_readme_badges.py do.

Publishing an OpenAPI document at all is the fix for a concrete finding: an
agent-readiness audit (2026-07-31) scored the site 0/7 on "OpenAPI spec
published" and 0/6 on "developer portal", and its agent review concluded
"impossible to proceed with any integration".

Run:
  python3 scripts/gen_openapi.py            # after gen_public_catalog.py
"""
import json
import os
import sys
import yaml

ROOT = os.path.join(os.path.dirname(__file__), "..")
PUBLIC = os.path.join(ROOT, "public")
SPEC = os.path.join(PUBLIC, "spec.json")
BASE = "https://a2uicatalog.ai"


def _counts():
    if not os.path.isfile(SPEC):
        sys.exit("public/spec.json missing — run scripts/gen_public_catalog.py first")
    with open(SPEC, encoding="utf-8") as f:
        spec = json.load(f)
    atoms = spec.get("atoms") or spec.get("blocks") or []
    n = spec.get("atomCount") or len(atoms)
    surfaces = set()
    for a in atoms:
        for s in ((a.get("surfaces") or {}).get("works_on") or []):
            surfaces.add(s)
    mcp = sum(1 for a in atoms
              if "mcp-apps" in ((a.get("surfaces") or {}).get("works_on") or []))
    return n, len(surfaces), mcp


def build_openapi(n_atoms, n_surfaces):
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "A2UI Atomic Catalog",
            "version": "1.0.0",
            "summary": "Typed UI vocabulary and rendering API for AI agents",
            "description": (
                f"{n_atoms} typed UI atoms an agent composes into real rendered "
                f"interfaces — charts, gauges, steppers, dashboards — across "
                f"{n_surfaces} surfaces including web, Google Meet, Apps Script, "
                "Google Chat and MCP Apps hosts. The agent names a component from a "
                "fixed vocabulary; a renderer that already knows that component draws "
                "it, so no HTML is ever generated by the model.\n\n"
                "The primary integration surface is the MCP (Model Context Protocol) "
                "server at /mcp, which exposes its tools over JSON-RPC 2.0. The REST "
                "paths documented here are the supporting surfaces: the "
                "machine-readable catalog, the declared data proxy, and the natural "
                "language composer.\n\n"
                "No API key, no signup, no OAuth required for normal use.\n\n"
                "## Versioning\n\n"
                "The wire-format version is carried in an `X-API-Version` response "
                "header (currently `1`), not a URL path prefix — the MCP endpoint URL "
                "lives in users' client config files and moving it would break every "
                "existing integration. Additive changes (new atoms, tools, optional "
                "fields) ship without notice; breaking changes are announced on the "
                "affected responses via `Deprecation` (RFC 9745) and `Sunset` "
                "(RFC 8594) headers with a minimum 90 days between them. Backward "
                "compatibility is enforced in CI by a parity gate that fails the "
                "deploy if any response shape changes without being declared. Full "
                "policy: https://a2uicatalog.ai/versioning.md"
            ),
            "license": {"name": "MIT", "identifier": "MIT"},
            "contact": {"name": "A2UI Atomic Catalog",
                        "url": "https://github.com/a2uicatalog/a2ui"},
        },
        "servers": [{"url": BASE, "description": "Production"}],
        "externalDocs": {"description": "Agent-facing overview (llms.txt)",
                         "url": f"{BASE}/llms.txt"},
        "tags": [
            {"name": "mcp", "description": "Model Context Protocol server — the primary integration surface"},
            {"name": "catalog", "description": "Machine-readable atom vocabulary and discovery documents"},
            {"name": "compose", "description": "Natural language to atom blocks"},
            {"name": "data", "description": "Declared, rate-limited data sources for live atoms"},
        ],
        "paths": _paths(),
        "components": _components(),
    }


def _paths():
    return {
        "/mcp": {
            "get": {
                "tags": ["mcp"], "operationId": "describeMcpServer",
                "summary": "Server descriptor",
                "description": ("Content-negotiated. Accept: application/json returns a "
                                "machine-readable descriptor (name, transport, tools, rate "
                                "limits, docs). Accept: text/html returns a human landing "
                                "page. Accept: text/event-stream returns 405 — this server "
                                "is stateless and has no server-initiated stream."),
                "parameters": [{"name": "Accept", "in": "header", "required": False,
                                "schema": {"type": "string",
                                           "enum": ["application/json", "text/html", "text/plain"]}}],
                "responses": {
                    "200": {"description": "Server descriptor",
                            "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"}},
                            "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ServerDescriptor"}}}},
                    "405": {"description": "Accept: text/event-stream — no server-initiated stream",
                            "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
                },
            },
            "post": {
                "tags": ["mcp"], "operationId": "mcpJsonRpc",
                "summary": "MCP JSON-RPC 2.0 endpoint",
                "description": ("Streamable HTTP transport. Supports initialize, tools/list, "
                                "tools/call, ping and notifications. Call tools/list for the "
                                "authoritative tool set with full input schemas."),
                "requestBody": {"required": True, "content": {"application/json": {
                    "schema": {"$ref": "#/components/schemas/JsonRpcRequest"},
                    "examples": {
                        "toolsList": {"summary": "List tools",
                                      "value": {"jsonrpc": "2.0", "id": 1, "method": "tools/list"}},
                        "callTool": {"summary": "Render a payload to a shareable URL",
                                     "value": {"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                                               "params": {"name": "preview_url", "arguments": {"payload": {
                                                   "title": "Demo", "blocks": [{"type": "stat_card",
                                                   "value": "1,234", "label": "Daily users", "delta": "+12%"}]}}}}},
                    }}}},
                "responses": {"200": {"description": "JSON-RPC response",
                    "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"},
                                "Deprecation": {"$ref": "#/components/headers/Deprecation"},
                                "Sunset": {"$ref": "#/components/headers/Sunset"}},
                    "content": {
                    "application/json": {"schema": {"$ref": "#/components/schemas/JsonRpcResponse"}}}}},
            },
        },
        "/spec.json": {"get": {
            "tags": ["catalog"], "operationId": "getCatalogSpec",
            "summary": "Full atom vocabulary",
            "description": ("Every published atom with its type, description, field contracts "
                            "and per-surface support. This is what an agent reads to compose a "
                            "payload without guessing field names."),
            "responses": {"200": {"description": "Catalog specification", "content": {
                "application/json": {"schema": {"$ref": "#/components/schemas/CatalogSpec"}}}}}}},
        "/catalogue/index.json": {"get": {
            "tags": ["catalog"], "operationId": "getCatalogIndex",
            "summary": "Catalog selection menu",
            "description": ("Compact index of catalogs with a when-to-use line each, so an agent "
                            "can select a slice without loading the full vocabulary into context."),
            "responses": {"200": {"description": "Catalog index",
                                  "content": {"application/json": {"schema": {"type": "object"}}}}}}},
        "/catalogue/atoms-json-schema.json": {"get": {
            "tags": ["catalog"], "operationId": "getAtomJsonSchema",
            "summary": "Strict per-atom JSON Schema",
            "description": ("Per-atom JSON Schema suitable for constrained decoding "
                            "(response_format / grammar), so a model cannot emit an atom that "
                            "fails validation."),
            "responses": {"200": {"description": "JSON Schema", "content": {
                "application/schema+json": {"schema": {"type": "object"}}}}}}},
        "/.well-known/ard.json": {"get": {
            "tags": ["catalog"], "operationId": "getCanonicalArdCatalog",
            "summary": "Agentic Resource Discovery catalog (ARD v0.91 canonical path)",
            "description": ("ARD-compliant discovery document (specVersion 1.0) describing this "
                            "host and every atom as an addressable capability."),
            "responses": {"200": {"description": "ARD catalog",
                                  "content": {"application/json": {"schema": {"type": "object"}}}}}}},
        "/.well-known/ai-catalog.json": {"get": {
            "tags": ["catalog"], "operationId": "getArdCatalog",
            "summary": "Agentic Resource Discovery catalog (legacy alias)",
            "description": ("ARD-compliant discovery document (specVersion 1.0) describing this "
                            "host and every atom as an addressable capability."),
            "responses": {"200": {"description": "ARD catalog",
                                  "content": {"application/json": {"schema": {"type": "object"}}}}}}},
        "/api/render": {"post": {
            "tags": ["render"], "operationId": "renderSurface",
            "summary": "A2UI payload to HTML",
            "description": ("POST a payload, get a complete self-contained HTML page back. "
                            "The protocol-free path: no MCP, no connector, no deployment — "
                            "compose against spec.json and render here. Serves the 474 "
                            "published atoms; preview-stage atoms are reported in "
                            "X-A2UI-Unpublished and rendered as a comment rather than markup. "
                            "Atoms that perform a render-time server fetch (data_source, "
                            "firestore_read, doc_ai_summary, multi_doc_ai_brief, "
                            "gemini_handoff) are refused with 400 — deploy your own renderer "
                            "for those. Limits: 256 KB body, 300 blocks, 12 levels of nesting, "
                            "50 requests per IP per day."),
            "parameters": [{
                "name": "surface", "in": "query", "required": False,
                "schema": {"type": "string",
                           "enum": ["web", "mcp-apps", "google-apps-script-web", "google-meet-stage"]},
                "description": ("Apply that surface's declared compatibility policy. Atoms marked "
                                "degraded_on for it render and are named in X-A2UI-Degraded; atoms "
                                "marked incompatible_on are replaced by a visible note and named in "
                                "X-A2UI-Incompatible. Selects a POLICY, not a renderer — one renderer "
                                "serves every accepted surface. pdf, email and google-chat are refused "
                                "with 400: this endpoint emits HTML, and answering half-honestly about "
                                "portability is worse than not answering. Omit for no policy."),
            }, {"$ref": "#/components/parameters/IdempotencyKey"}],
            "requestBody": {"required": True, "content": {"application/json": {
                "schema": {"type": "object", "required": ["blocks"], "properties": {
                    "title": {"type": "string", "description": "Page title"},
                    "theme": {"type": "string", "enum": ["light", "dark"]},
                    "blocks": {"type": "array", "items": {"type": "object"},
                               "description": "A2UI blocks-dialect atoms — see /spec.json"}}},
                "example": {"title": "Weekly numbers", "theme": "light", "blocks": [
                    {"type": "heading", "text": "This week"},
                    {"type": "stat_card", "value": "1,234", "label": "Daily users", "delta": "+12%"}]}}}},
            "responses": {
                "200": {"description": "Rendered HTML page",
                        "content": {"text/html": {"schema": {"type": "string"}}}},
                "400": {"description": "Malformed payload, unrenderable atom, or limit exceeded",
                        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
                "413": {"description": "Body larger than 256 KB",
                        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
                "429": {"$ref": "#/components/responses/RateLimited"}}}},
        "/api/render/batch": {"post": {
            "tags": ["render"], "operationId": "renderSurfaceBatch",
            "summary": "Render many payloads in one call",
            "description": ("Same guards and surface policy as /api/render, applied per payload. "
                            "PARTIAL SUCCESS is the contract: a malformed or refused payload returns "
                            "its own status inside the results array and the rest still render — the "
                            "batch is never failed over one bad entry. Max 25 payloads, 1 MB body, and "
                            "one call against the daily allowance regardless of batch size."),
            "parameters": [{
                "name": "surface", "in": "query", "required": False,
                "schema": {"type": "string",
                           "enum": ["web", "mcp-apps", "google-apps-script-web", "google-meet-stage"]},
                "description": "One surface for the whole batch; applied to every payload.",
            }, {"$ref": "#/components/parameters/IdempotencyKey"}],
            "requestBody": {"required": True, "content": {"application/json": {
                "schema": {"type": "object", "required": ["payloads"], "properties": {
                    "payloads": {"type": "array", "maxItems": 25, "items": {"type": "object"}}}},
                "example": {"payloads": [
                    {"title": "Q1", "blocks": [{"type": "heading", "text": "Q1"}]},
                    {"title": "Q2", "blocks": [{"type": "heading", "text": "Q2"}]}]}}}},
            "responses": {
                "200": {"description": "Per-payload results",
                        "content": {"application/json": {"schema": {"type": "object", "properties": {
                            "ok": {"type": "boolean"}, "rendered": {"type": "integer"},
                            "failed": {"type": "integer"},
                            "results": {"type": "array", "items": {"type": "object", "properties": {
                                "index": {"type": "integer"}, "status": {"type": "integer"},
                                "html": {"type": "string"}, "error": {"type": "string"},
                                "degraded": {"type": "array", "items": {"type": "string"}},
                                "incompatible": {"type": "array", "items": {"type": "string"}}}}}}}}}},
                "400": {"description": "Malformed batch, unknown surface, or over the 25-payload cap",
                        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
                "413": {"description": "Body larger than 1 MB",
                        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
                "429": {"$ref": "#/components/responses/RateLimited"}}}},
        "/api/compose": {"post": {
            "tags": ["compose"], "operationId": "composeFromText",
            "summary": "Natural language to atom blocks",
            "description": ("Two-stage routing over atom embeddings returns candidate atom blocks "
                            "for a plain-English UI request. Rate limited to 20 requests per IP "
                            "per day (free-tier inference)."),
            "parameters": [{"$ref": "#/components/parameters/IdempotencyKey"}],
            "requestBody": {"required": True, "content": {"application/json": {
                "schema": {"type": "object", "required": ["prompt"], "properties": {
                    "prompt": {"type": "string", "description": "Plain-English description of the UI wanted"}}},
                "example": {"prompt": "a dashboard with daily users and a bar chart of traffic sources"}}}},
            "responses": {
                "200": {"description": "Atom blocks",
                        "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"},
                                    "Deprecation": {"$ref": "#/components/headers/Deprecation"},
                                    "Sunset": {"$ref": "#/components/headers/Sunset"}},
                        "content": {"application/json": {"schema": {
                    "type": "object", "properties": {"blocks": {"type": "array", "items": {
                        "$ref": "#/components/schemas/AtomBlock"}}}}}}},
                "429": {"$ref": "#/components/responses/RateLimited"}}}},
        "/api/data/{source}": {"get": {
            "tags": ["data"], "operationId": "getDeclaredDataSource",
            "summary": "Declared data-source proxy",
            "description": ("Proxies a data source declared in atoms/data-sources.yaml, with "
                            "per-source cache, rate and egress budgets. Only declared sources are "
                            "reachable — this is the single place network access is granted to "
                            "live atoms."),
            "parameters": [
                {"name": "source", "in": "path", "required": True,
                 "schema": {"type": "string"}, "description": "Declared source id"},
                {"name": "cursor", "in": "query", "required": False,
                 "schema": {"type": "string"},
                 "description": ("Opaque pagination cursor from a previous response's "
                                 "next_cursor. Only meaningful for sources whose declared "
                                 "shape is a list; omit for a single-object source.")},
                {"name": "limit", "in": "query", "required": False,
                 "schema": {"type": "integer", "minimum": 1, "maximum": 200},
                 "description": "Max items to return, for list-shaped sources. Source-defined default."},
            ],
            "responses": {
                "200": {"description": ("Source payload, unpaginated by default (backward "
                                        "compatible with every existing caller). Pass cursor "
                                        "and/or limit on a source whose declared shape is a list "
                                        "and the envelope additionally carries next_cursor "
                                        "(string, absent/null when exhausted) and has_more "
                                        "(boolean) alongside the sliced data — cursor-based, not "
                                        "page-number-based."),
                        "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"},
                                    "Deprecation": {"$ref": "#/components/headers/Deprecation"},
                                    "Sunset": {"$ref": "#/components/headers/Sunset"}},
                        "content": {"application/json": {"schema": {"type": "object", "properties": {
                            "next_cursor": {"type": "string", "nullable": True},
                            "has_more": {"type": "boolean"}}, "additionalProperties": True}}}},
                "404": {"$ref": "#/components/responses/NotFound"},
                "429": {"$ref": "#/components/responses/RateLimited"}}}},
        "/ask": {
            "get": {
                "tags": ["catalog"], "operationId": "askCatalogGet",
                "summary": "NLWeb natural-language catalog search (GET)",
                "description": ("NLWeb protocol (nlweb.ai) endpoint over the atom catalog. Ask a "
                                "plain-English question — \"what atom do I use for a countdown "
                                "timer?\" — and get back ranked, typed catalog matches instead of "
                                "having to scrape HTML. Reuses the same embedding search /api/compose "
                                "uses to pick relevant atoms."),
                "parameters": [
                    {"name": "query", "in": "query", "required": True, "schema": {"type": "string"}},
                    {"name": "mode", "in": "query", "required": False, "schema": {"type": "string"},
                     "description": "Comma-separated: list (default), summarize, generate."},
                    {"name": "site", "in": "query", "required": False, "schema": {"type": "string"}},
                    {"name": "query_id", "in": "query", "required": False, "schema": {"type": "string"}},
                    {"name": "Accept", "in": "header", "required": False, "schema": {"type": "string"},
                     "description": "text/event-stream requests an SSE stream (start/result/complete events)."}],
                "responses": {
                    "200": {"description": "Search results",
                            "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"},
                                        "Deprecation": {"$ref": "#/components/headers/Deprecation"},
                                        "Sunset": {"$ref": "#/components/headers/Sunset"}},
                            "content": {"application/json": {"schema": {"$ref": "#/components/schemas/NLWebAskResponse"}}}},
                    "400": {"$ref": "#/components/responses/NotFound"},
                    "429": {"$ref": "#/components/responses/RateLimited"}}},
            "post": {
                "tags": ["catalog"], "operationId": "askCatalogPost",
                "summary": "NLWeb natural-language catalog search (POST)",
                "description": "Same as GET /ask; accepts the flat REST body or the fuller NLWeb protocol's nested query/prefer/meta shape.",
                "requestBody": {"required": True, "content": {"application/json": {
                    "schema": {"$ref": "#/components/schemas/NLWebAskRequest"},
                    "example": {"query": "what atom do I use for a countdown timer?", "mode": "list,summarize"}}}},
                "responses": {
                    "200": {"description": "Search results",
                            "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"},
                                        "Deprecation": {"$ref": "#/components/headers/Deprecation"},
                                        "Sunset": {"$ref": "#/components/headers/Sunset"}},
                            "content": {"application/json": {"schema": {"$ref": "#/components/schemas/NLWebAskResponse"}}}},
                    "400": {"$ref": "#/components/responses/NotFound"},
                    "429": {"$ref": "#/components/responses/RateLimited"}}}},
        "/s/{id}": {"get": {
            "tags": ["mcp"], "operationId": "getPublishedSurface",
            "summary": "Published short link",
            "description": ("Resolves a short link minted by the publish_url tool. Appending "
                            ".json returns the stored payload by reference instead of "
                            "redirecting to the rendered surface."),
            "parameters": [{"name": "id", "in": "path", "required": True,
                            "schema": {"type": "string"}}],
            "responses": {
                "302": {"description": "Redirect to the rendered surface"},
                "200": {"description": "Stored payload (when requested as .json)",
                        "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"},
                                    "Deprecation": {"$ref": "#/components/headers/Deprecation"},
                                    "Sunset": {"$ref": "#/components/headers/Sunset"}},
                        "content": {
                    "application/json": {"schema": {"$ref": "#/components/schemas/A2uiPayload"}}}},
                "404": {"$ref": "#/components/responses/NotFound"}}}},
    }


def _components():
    return {
        "parameters": {
            "IdempotencyKey": {
                "name": "Idempotency-Key", "in": "header", "required": False,
                "schema": {"type": "string", "maxLength": 200},
                "description": ("Client-generated opaque token (UUID recommended). Retrying the "
                                "SAME key within a 10-minute window returns the cached first "
                                "response instead of recomputing — safe to retry after a network "
                                "failure without risk of acting twice on a duplicate. A new key "
                                "always runs fresh. These operations don't persist state on this "
                                "server (render is a pure function of the payload), so the "
                                "practical benefit is avoiding duplicate compute/quota spend on a "
                                "blind retry, not avoiding a duplicated side effect — but the "
                                "contract is the same shape a mutating endpoint would use."),
            },
        },
        "headers": {
            "ApiVersion": {
                "description": ("Wire-format version of this response, currently \"1\". The "
                                "additive alternative to a /v1/ path prefix: bump only on a "
                                "documented, intentional change to a response shape."),
                "schema": {"type": "string", "example": "1"}},
            "Deprecation": {
                "description": ("RFC 9745. Present only on a response the versioning policy has "
                                "announced as deprecated; its value is the deprecation date. "
                                "Paired with Sunset (the date the deprecated shape stops being "
                                "served) with a minimum 90 days between them. Absent on every "
                                "response not under an announced deprecation — see "
                                "https://a2uicatalog.ai/versioning.md."),
                "schema": {"type": "string", "format": "date", "example": "2026-09-01"}},
            "Sunset": {
                "description": ("RFC 8594. Present alongside Deprecation once a removal date is "
                                "set — the last date this response shape is served."),
                "schema": {"type": "string", "format": "date", "example": "2026-12-01"}}},
        "responses": {
            "RateLimited": {
                "description": ("Rate limit reached. See the descriptor at GET /mcp "
                                "(Accept: application/json) for current limits."),
                "headers": {
                    "X-RateLimit-Limit": {"description": "Requests allowed in the current window.",
                                          "schema": {"type": "integer"}},
                    "X-RateLimit-Remaining": {"description": "Requests remaining in the current window.",
                                              "schema": {"type": "integer"}},
                    "Retry-After": {"description": "Seconds until the window resets (present on some sources).",
                                    "schema": {"type": "integer"}},
                    "X-API-Version": {"$ref": "#/components/headers/ApiVersion"}},
                "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
            "NotFound": {
                "description": "No resource at this path.",
                "headers": {"X-API-Version": {"$ref": "#/components/headers/ApiVersion"}},
                "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorResponse"}}}},
        },
        "schemas": {
            "ErrorResponse": {
                "type": "object",
                "description": ("Shape of every non-2xx JSON response on the REST surface (the "
                                "/mcp JSON-RPC endpoint uses JsonRpcResponse.error instead — see "
                                "that schema — and a KNOWN tool failing during execution uses "
                                "result.isError plus result._meta.errorCode, a stable "
                                "machine-readable string such as INVALID_PAYLOAD_SHAPE)."),
                "properties": {
                    "ok": {"type": "boolean", "const": False},
                    "error": {"type": "string", "description": "Human-readable error message."},
                    "note": {"type": "string", "description": "Optional extra guidance (e.g. how to raise a limit)."}}},
            "ServerDescriptor": {
                "type": "object",
                "description": "Machine-readable description of the MCP server.",
                "properties": {
                    "name": {"type": "string"}, "description": {"type": "string"},
                    "protocol": {"type": "string", "const": "mcp"},
                    "transport": {"type": "string", "const": "streamable-http"},
                    "endpoint": {"type": "string", "format": "uri"},
                    "authentication": {"type": "object", "properties": {
                        "type": {"type": "string"}, "required": {"type": "boolean"}}},
                    "tools": {"type": "array", "items": {"type": "object", "properties": {
                        "name": {"type": "string"}, "description": {"type": "string"}}}},
                    "documentation": {"type": "object",
                                      "additionalProperties": {"type": "string", "format": "uri"}},
                    "rateLimits": {"type": "object", "additionalProperties": {"type": "string"}}}},
            "JsonRpcRequest": {
                "type": "object", "required": ["jsonrpc", "method"], "properties": {
                    "jsonrpc": {"type": "string", "const": "2.0"},
                    "id": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                    "method": {"type": "string",
                               "examples": ["initialize", "tools/list", "tools/call", "ping"]},
                    "params": {"type": "object"}}},
            "JsonRpcResponse": {
                "type": "object", "required": ["jsonrpc"], "properties": {
                    "jsonrpc": {"type": "string", "const": "2.0"},
                    "id": {"oneOf": [{"type": "integer"}, {"type": "string"}, {"type": "null"}]},
                    "result": {"type": "object", "description": (
                        "For tools/call against a KNOWN tool that fails during execution (bad "
                        "arguments, an unresolvable reference, a precondition not met), "
                        "result.isError: true — see result._meta.errorCode below — rather than "
                        "the top-level error field. An UNKNOWN tool NAME instead returns the "
                        "top-level error field (code -32602): the client asked for a method that "
                        "doesn't exist, which is a protocol-level problem, not a tool that ran "
                        "and failed.")},
                    "error": {"type": "object", "description": (
                        "Protocol-level error (JSON-RPC 2.0 §5.1): bad method, parse error, or "
                        "tools/call naming an unknown tool."),
                              "properties": {
                        "code": {"type": "integer", "examples": [-32700, -32600, -32601, -32602, -32603]},
                        "message": {"type": "string"}}}}},
            "AtomBlock": {
                "type": "object",
                "description": ("One typed UI component. `type` selects the atom; the remaining "
                                "fields are that atom's declared contract (see /spec.json)."),
                "required": ["type"],
                "properties": {"type": {"type": "string",
                                        "examples": ["stat_card", "chartjs_bar", "stepper", "callout"]}},
                "additionalProperties": True},
            "A2uiPayload": {
                "type": "object",
                "description": "A renderable surface: a title, a theme, and an ordered list of atom blocks.",
                "required": ["blocks"], "properties": {
                    "title": {"type": "string"},
                    "theme": {"type": "string", "enum": ["light", "dark", "site"]},
                    "blocks": {"type": "array", "items": {"$ref": "#/components/schemas/AtomBlock"}}}},
            "CatalogSpec": {
                "type": "object", "properties": {
                    "catalogId": {"type": "string"}, "displayName": {"type": "string"},
                    "atomCount": {"type": "integer"},
                    "atoms": {"type": "array", "items": {"type": "object"}}}},
            "NLWebAskRequest": {
                "type": "object",
                "description": "Accepts either the flat REST fields below, OR query as a nested {\"text\": \"...\"} object per the fuller NLWeb protocol spec.",
                "required": ["query"],
                "properties": {
                    "query": {"oneOf": [{"type": "string"}, {"type": "object", "properties": {
                        "text": {"type": "string"}}}]},
                    "site": {"type": "string"}, "mode": {"type": "string",
                        "description": "Comma-separated: list, summarize, generate."},
                    "streaming": {"type": "boolean"}, "query_id": {"type": "string"}}},
            "NLWebAskResult": {
                "type": "object",
                "description": "One catalog match, schema.org-flavored per the NLWeb spec.",
                "properties": {
                    "@type": {"type": "string", "examples": ["Thing", "SearchSummary"]},
                    "url": {"type": "string", "format": "uri"},
                    "name": {"type": "string"}, "site": {"type": "string"},
                    "score": {"type": "number"}, "description": {"type": "string"},
                    "schema_object": {"type": "object", "description": "The full spec.json atom entry."}}},
            "NLWebAskResponse": {
                "type": "object",
                "properties": {
                    "query_id": {"type": "string"},
                    "results": {"type": "array", "items": {"$ref": "#/components/schemas/NLWebAskResult"}},
                    "generated": {"type": "array", "items": {"$ref": "#/components/schemas/AtomBlock"},
                                 "description": "Present only for mode=generate: composed atom blocks answering the query."},
                    "routing": {"type": "string", "examples": ["embed", "chat"]},
                    "_meta": {"type": "object", "properties": {
                        "response_type": {"type": "string", "const": "answer"},
                        "version": {"type": "string"}}}}},
        },
    }


LLMS_TXT = """# A2UI Atomic Catalog

> Open-source, typed UI vocabulary ({n_atoms} atoms) an AI agent uses to compose real interfaces — web, Google Meet stages, Apps Script web apps, Google Chat cards, and MCP Apps — from one JSON schema payload, instead of generating HTML.

## Integrate

- [MCP server]({base}/mcp): Live JSON-RPC endpoint, no auth/signup required. GET with `Accept: application/json` returns a machine-readable server descriptor listing every tool.
- [Documentation MCP server]({base}/mcp-docs): A separate MCP identity (`a2uicatalog-docs`) for questions FROM this product's own docs — `search_docs(query)` and `list_docs()`. The product server above takes actions (compose/render/publish); this one only answers doc questions.
- [CLI / local MCP server (npm registry)](https://registry.npmjs.org/@a2uicatalog/mcp): `npx -p @a2uicatalog/mcp a2ui render page.json` renders a payload to HTML with no account and no MCP client. Also runs as a local MCP server (`a2uicatalog-mcp` bin) for Claude Desktop/Cursor, and deploys `training.md` to your own Google Apps Script web app via `build_app`. Source: `mcp/` in the [GitHub repository](https://github.com/a2uicatalog/a2ui). (npm's own package-page web UI 403s plain HTTP clients — the registry API link above is the one that resolves for a bot; `npm view @a2uicatalog/mcp` or a browser both work fine for a human.)
- [Agent Skills](https://a2uicatalog.ai/.well-known/agent-skills/index.json): three `SKILL.md` files (`a2ui-catalog`, `a2ui-compose`, `a2ui-mcp` — picking atoms, composing/rendering a payload, connecting a new agent over MCP) installable via `npx skills add a2uicatalog/a2ui`. Source: `skills/` in the GitHub repository.
- [Developer documentation]({base}/developers/): Integration guide, REST surfaces, code samples, self-hosting runbooks.
- [API documentation]({base}/docs/): REST API endpoints (/api/render, /api/compose, /ask), request/response schemas, and error shapes.
- [API docs and reference]({base}/api-docs/): Predictable entry point for developer resources, OpenAPI specs, and MCP endpoints.
- [NLWeb search]({base}/ask): Ask a plain-English question about the catalog (GET `?query=` or POST JSON) and get ranked, typed atom matches — no need to scrape HTML. `mode=summarize` adds a one-paragraph answer; `mode=generate` composes a real UI from the match. Supports SSE streaming (`Accept: text/event-stream`).
- [OpenAPI specification]({base}/openapi.json): The full API surface — MCP endpoint, catalog documents, compose, data-proxy and NLWeb routes.
- [Auth documentation]({base}/auth/): Authentication guide, enterprise OAuth discovery metadata, and public unauthenticated access policies.
- [Auth & rate limits]({base}/.well-known/agent-auth.md): No API key or signup — the actual per-tool call limits.
- [Authentication guide]({base}/auth.md): Why you almost certainly need no credential, plus the optional OAuth path for enterprise platforms that require one.
- [Webhooks & events]({base}/webhooks/): Event delivery, Server-Sent Events (SSE) streaming, and chat webhook destinations.
- [Pricing and rate limits]({base}/pricing/): Free tier limits and self-hosting options.
- [Versioning & deprecation policy]({base}/versioning/): What changes without notice, how breaking changes are announced (`Deprecation`/`Sunset` headers, 90-day minimum), and the CI parity gate that enforces it.
- [Machine-readable catalog]({base}/spec.json): The full atom vocabulary as structured JSON — every field contract, generated from the schema.
- [Strict per-atom JSON Schema]({base}/catalogue/atoms-json-schema.json): For constrained decoding, so a model cannot emit an invalid atom.
- [Agent discovery document]({base}/.well-known/ard.json): Canonical ARD v0.91 resource discovery catalog (legacy alias at /.well-known/ai-catalog.json; also referenced from robots.txt's `Agentmap:` directive).
- [MCP Apps playground]({base}/surfaces/mcp-apps): Renders atoms live inside MCP Apps-capable hosts (e.g. claude.ai); paste a payload or open a `#p=` link.
- [Self-host the renderer]({base}/renderer): Deploy your own Apps Script renderer in 4 commands — own the URL, no shared-demo rate limit.

## When to use this

Use the A2UI catalog when you need to SHOW something to a user rather than describe it — a chart, a status board, a step-by-step procedure, a comparison table, a dashboard. Call `list_catalogs` then `get_catalog` to read real field contracts before composing; never guess a field name. Use `render_surface` on MCP Apps-capable hosts to render inline, or `preview_url` elsewhere to get a shareable link.

Do not use it for plain prose answers, for data retrieval (it renders data, it does not fetch it beyond declared sources), or where the host cannot display HTML.

## Writing

Build logs and architecture write-ups from operating this catalog in production — real incidents, real fixes, dated and attributed. Full list below; [sitemap]({base}/blog/sitemap.xml) is the machine-readable version.

- [Building in the Age of Frontier Models: Why Frugality is My Go-To Architecture]({base}/blog/001-frugality-architecture/): Artifact distillation — spend the model once, keep the output forever. Five problems nobody asked me to solve.
- [Rich UI in Gemini Enterprise: A Field Report on A2A Agents and A2UI Primitives]({base}/blog/002-gemini-enterprise-field-report-a2a-a2ui-part1/): Every component in the A2UI v0.8 Basic Catalog tested against a real Gemini Enterprise agent, plus two working demo agents built entirely from them.
- [Rich UI in Gemini Enterprise, Part 2 — The Print-Rendering Workaround for Custom Catalogs]({base}/blog/003-gemini-enterprise-field-report-a2a-a2ui-part2/): Gemini Enterprise only renders 18 standard-catalog primitives; the fix renders custom charts/gauges server-side to an image through the one primitive that always works.
- [The A2UI Catalog Now Renders Inside Claude.ai]({base}/blog/004-mcp-apps-inside-claude-ai/): One connector URL, 474 typed atoms rendering inline in the conversation — no HTML written.
- [Rich UI in Google Chat: a real, self-hostable bot built on the print-channel trick]({base}/blog/005-google-chat-print-channel-bundle/): The self-hostable Cloud Run bundle, a wire-level trace of one request, and the Chat-setup gotchas Google's docs don't lead with.
- [The A2UI Catalog Now Renders Inside ChatGPT]({base}/blog/006-mcp-apps-inside-chatgpt/): Same connector URL, same payloads, a second host — and three latent defects that existing connections had been quietly hiding.
- [MCP Apps Isn't A2UI's Competitor — It's How It Travels]({base}/blog/007-mcp-apps-portability/): Where transport, envelope and document model actually sit — how the same payload reaches Claude, ChatGPT and this site without three separate builds.
- [MCP, A2UI, and a Durable Object per Human]({base}/blog/008-mcp-durable-state/): Where per-user UI state actually lives across MCP, A2UI and A2A — covers Cloudflare's Project Think, Durable Objects per reader, and six real defects found wiring it up.

## Source

- [GitHub repository](https://github.com/a2uicatalog/a2ui): Source, license, and the full atom schema.
- [Claude quickstart](https://raw.githubusercontent.com/a2uicatalog/a2ui/main/docs/quickstart-claude.md): Connect the MCP server, render a first atom, deploy your own renderer.
- [Gemini Enterprise quickstart](https://raw.githubusercontent.com/a2uicatalog/a2ui/main/docs/quickstart-gemini-enterprise.md): BYO-MCP setup for Gemini Enterprise agents.
"""


def build_api_catalog():
    """RFC 9727 api-catalog: a single Linkset document (application/linkset+json)
    enumerating every public API surface, so an agent finds them all from one
    well-known URL instead of guessing paths. Real RFC, verified against
    datatracker.ietf.org/doc/html/rfc9727 before implementing (2026-07-31)."""
    def item(href, rel_type, title):
        return {"href": href, "type": rel_type, "title": title}
    return {
        "linkset": [{
            "anchor": f"{BASE}/",
            "describedby": [item(f"{BASE}/openapi.json", "application/json", "OpenAPI 3.1 specification")],
            "service-desc": [
                item(f"{BASE}/openapi.json", "application/json", "OpenAPI 3.1 specification"),
                item(f"{BASE}/spec.json", "application/json", "Full atom vocabulary (machine-readable catalog)"),
            ],
            "item": [
                item(f"{BASE}/mcp", "application/json", "MCP server (JSON-RPC 2.0, Streamable HTTP)"),
                item(f"{BASE}/mcp-docs", "application/json", "Documentation MCP server (a2uicatalog-docs)"),
                item(f"{BASE}/ask", "application/json", "NLWeb natural-language catalog search"),
                item(f"{BASE}/api/compose", "application/json", "Natural language to atom blocks"),
                item(f"{BASE}/api/data/{{source}}", "application/json", "Declared data-source proxy"),
                item(f"{BASE}/catalogue/index.json", "application/json", "Catalog selection index"),
                item(f"{BASE}/catalogue/atoms-json-schema.json", "application/schema+json", "Strict per-atom JSON Schema"),
                item(f"{BASE}/.well-known/ard.json", "application/json", "ARD v0.91 discovery catalog"),
                item(f"{BASE}/.well-known/ai-catalog.json", "application/json", "ARD discovery catalog (legacy alias)"),
                item(f"{BASE}/.well-known/mcp.json", "application/json", "MCP discovery pointer"),
                item(f"{BASE}/.well-known/agent-card.json", "application/json", "A2A agent card"),
                # Path-suffixed per RFC 9728 §3.1 — this document describes
                # /mcp-auth, NOT the origin root. Published at the root path it
                # tells every client that the unauthenticated /mcp is protected
                # too; Claude then looked for dynamic client registration, found
                # none, and refused to connect ("automatic client registration
                # isn't supported... add an OAuth Client ID", 2026-08-01).
                item(f"{BASE}/.well-known/oauth-protected-resource/mcp-auth", "application/json", "OAuth protected-resource metadata for /mcp-auth (RFC 9728)"),
                item(f"{BASE}/.well-known/oauth-authorization-server", "application/json", "OAuth authorization-server metadata (RFC 8414)"),
            ],
            "describes": [
                item(f"{BASE}/developers/", "text/html", "Developer documentation and API guide"),
                item(f"{BASE}/docs/", "text/html", "API documentation and endpoint reference"),
                item(f"{BASE}/api-docs/", "text/html", "API docs and reference directory"),
                item(f"{BASE}/auth/", "text/html", "Authentication and security documentation"),
                item(f"{BASE}/webhooks/", "text/html", "Webhooks and event delivery documentation"),
                item(f"{BASE}/versioning/", "text/html", "Versioning and deprecation policy documentation"),
                item(f"{BASE}/pricing/", "text/html", "Pricing and rate limit documentation"),
                item(f"{BASE}/versioning.md", "text/markdown", "Versioning and deprecation policy"),
                item(f"{BASE}/auth.md", "text/markdown", "Authentication guide"),
                item(f"{BASE}/pricing.md", "text/markdown", "Pricing and rate limits"),
            ],
        }],
    }


def build_agent_view(n_atoms, n_surfaces):
    """The ?mode=agent payload: a structured summary of what this site offers an
    agent, instead of the marketing homepage. Generated (not hand-written) so the
    atom count comes from spec.json like every other count on the site — the
    homepage Worker just serves this file, keeping the Worker itself trivial and
    stateless."""
    return {
        "name": "A2UI Atomic Catalog",
        "description": (
            f"{n_atoms} typed UI atoms an AI agent composes into real rendered "
            f"interfaces across {n_surfaces} surfaces, instead of generating HTML."
        ),
        "authentication": {
            "required": False,
            "detail": "No API key, no signup. See /auth.md for the optional enterprise OAuth path.",
        },
        "primary_interface": {
            "protocol": "mcp",
            "transport": "streamable-http",
            "endpoint": f"{BASE}/mcp",
            "descriptor": f"GET {BASE}/mcp with Accept: application/json",
        },
        "endpoints": {
            "spec": f"{BASE}/spec.json",
            "json_schema": f"{BASE}/catalogue/atoms-json-schema.json",
            "catalog_index": f"{BASE}/catalogue/index.json",
            "nlweb_ask": f"{BASE}/ask",
            "compose": f"{BASE}/api/compose",
        },
        "documentation": {
            "openapi": f"{BASE}/openapi.json",
            "openapi_yaml": f"{BASE}/openapi.yaml",
            "developers": f"{BASE}/developers/",
            "api_docs": f"{BASE}/docs/",
            "api_reference": f"{BASE}/api-docs/",
            "auth_docs": f"{BASE}/auth/",
            "webhooks": f"{BASE}/webhooks/",
            "versioning_docs": f"{BASE}/versioning/",
            "pricing_docs": f"{BASE}/pricing/",
            "llms": f"{BASE}/llms.txt",
            "agents": f"{BASE}/agents.md",
            "auth": f"{BASE}/auth.md",
            "versioning": f"{BASE}/versioning.md",
            "pricing": f"{BASE}/pricing.md",
            "api_catalog": f"{BASE}/.well-known/api-catalog",
            "ard_catalog": f"{BASE}/.well-known/ard.json",
            "agent_card": f"{BASE}/.well-known/agent-card.json",
        },
        "capabilities": [
            "Browse a typed UI vocabulary and read real field contracts",
            "Compose a payload and render it inline (MCP Apps hosts) or as a shareable link",
            "Natural-language search over the catalog (/ask)",
            "Self-host the renderer for unlimited, unmetered rendering",
        ],
        "versioning": {"header": "X-API-Version", "current": "1", "policy": f"{BASE}/versioning.md"},
        "license": "MIT",
        "source": "https://github.com/a2uicatalog/a2ui",
    }


def main():
    n_atoms, n_surfaces, n_mcp = _counts()

    openapi_doc = build_openapi(n_atoms, n_surfaces)
    out = os.path.join(PUBLIC, "openapi.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(openapi_doc, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {out} ({n_atoms} atoms, {n_surfaces} surfaces)")

    out_yaml = os.path.join(PUBLIC, "openapi.yaml")
    with open(out_yaml, "w", encoding="utf-8") as f:
        yaml.safe_dump(openapi_doc, f, sort_keys=False, allow_unicode=True)
    print(f"wrote {out_yaml}")

    out2 = os.path.join(PUBLIC, "llms.txt")
    with open(out2, "w", encoding="utf-8") as f:
        f.write(LLMS_TXT.format(n_atoms=n_atoms, base=BASE))
    print(f"wrote {out2}")

    wk = os.path.join(PUBLIC, ".well-known")
    os.makedirs(wk, exist_ok=True)
    out3 = os.path.join(wk, "api-catalog")
    with open(out3, "w", encoding="utf-8") as f:
        json.dump(build_api_catalog(), f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {out3}")

    out4 = os.path.join(PUBLIC, "agent-view.json")
    with open(out4, "w", encoding="utf-8") as f:
        json.dump(build_agent_view(n_atoms, n_surfaces), f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"wrote {out4}")


if __name__ == "__main__":
    main()
