#!/usr/bin/env python3
"""gen_pack_map — emit the atom->pack map as a .gs the renderer reads at runtime.

The renderer can't read atoms/atom-packs.yaml (it's GAS), so we compile the partition
into apps-script-surface/gas-wired-renderer/PackMap.gs as `var ATOM_PACK = {...}`.
renderAtoms() uses it to gate dispatch by enabled packs (see the pack-gate in atom.gs):
a lean workbench sets A2UI_ENABLED_PACKS='core' and every non-core atom degrades
gracefully — no file surgery, all 497 atoms stay put.

GENERATED — do not hand-edit PackMap.gs; edit atoms/atom-packs.yaml and rebuild.
Wired into the catalog-rebuild process.
"""
import json
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PACKS = os.path.join(ROOT, "atoms", "atom-packs.yaml")
OUT = os.path.join(ROOT, "apps-script-surface", "gas-wired-renderer", "PackMap.gs")

ALWAYS = ["a2ui-atoms-v1"]   # base catalog — always resolved even in a lean workbench


def main():
    part = yaml.safe_load(open(PACKS))
    atom_pack = {a: bucket for bucket, atoms in part.items() for a in atoms}
    # deterministic key order for a stable diff
    ordered = {k: atom_pack[k] for k in sorted(atom_pack)}
    body = json.dumps(ordered, indent=0, separators=(",", ":")).replace("\n", "")
    always = json.dumps(ALWAYS)
    text = (
        "// PackMap.gs — GENERATED by scripts/gen_pack_map.py from atoms/atom-packs.yaml.\n"
        "// atom type -> pack bucket. Consumed by renderAtoms() to gate dispatch by\n"
        "// enabled packs (A2UI_ENABLED_PACKS script property, or opts.enabledPacks).\n"
        "// DO NOT EDIT — edit atoms/atom-packs.yaml then `ops.py run catalog-rebuild`.\n"
        f"var ATOM_PACK = {body};\n"
        f"var ALWAYS_ON_PACKS = {always};\n"
    )
    open(OUT, "w").write(text)
    print(f"wrote {OUT} — {len(ordered)} atoms mapped, always-on={ALWAYS}")


if __name__ == "__main__":
    main()
