#!/usr/bin/env python3
"""Stamp atoms/design-tokens.yaml into every palette implementation.

Outputs (never hand-edit):
  renderers/_design_tokens.py
  apps-script-surface/gas-wired-renderer/atoms_tokens.gs

  python3 scripts/gen_design_tokens.py           # write
  python3 scripts/gen_design_tokens.py --check   # exit 1 if outputs are stale
"""
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "atoms" / "design-tokens.yaml"
PY_OUT = ROOT / "renderers" / "_design_tokens.py"
GS_OUT = ROOT / "apps-script-surface" / "gas-wired-renderer" / "atoms_tokens.gs"

HEADER = ("GENERATED by scripts/gen_design_tokens.py from atoms/design-tokens.yaml"
          " -- do not edit; change the YAML and re-run.")


def load():
    d = yaml.safe_load(SRC.read_text())
    order = [(t["field"], t["name"]) for t in d["tokens"]]
    names = {n for _, n in order}
    for p, vals in d["presets"].items():
        bad = set(vals) - names
        assert not bad, f"preset {p} names unknown tokens {bad}"
    return d, order


def render_py(d, order):
    return f'''"""{HEADER}"""
import re

TOKEN_ORDER = {json.dumps(order)}
TOKEN_PRESETS = {json.dumps(d["presets"], indent=4)}
_SAFE = re.compile(r"[{d["safe_chars"]}]{{1,{d["safe_max_len"]}}}")


def token_css(b):
    """`--a2ui-<name>:<value>;` for every token the palette block sets, in
    declared order. Explicit fields beat the preset; unsafe values are dropped."""
    key = b.get("preset")
    preset = TOKEN_PRESETS.get(key, {{}}) if isinstance(key, str) else {{}}
    out = ""
    for field, name in TOKEN_ORDER:
        v = b.get(field)
        if not (isinstance(v, str) and v):
            v = preset.get(name)
        if isinstance(v, str) and _SAFE.fullmatch(v):
            out += "--a2ui-" + name + ":" + v + ";"
    return out
'''


def render_gs(d, order):
    safe = d["safe_chars"].replace("/", "\\/")
    return f'''// {HEADER}
var _TOKEN_ORDER = {json.dumps(order)};
var _TOKEN_PRESETS = {json.dumps(d["presets"], indent=2)};
var _TOKEN_SAFE = /^[{safe}]{{1,{d["safe_max_len"]}}}$/;

// `--a2ui-<name>:<value>;` for every token the palette block sets, in declared
// order. Explicit fields beat the preset; unsafe values are dropped.
function _tokenCss(b) {{
  var key = b.preset;
  var preset = (typeof key === 'string' && Object.prototype.hasOwnProperty.call(_TOKEN_PRESETS, key)) ? _TOKEN_PRESETS[key] : {{}};
  var out = '';
  for (var i = 0; i < _TOKEN_ORDER.length; i++) {{
    var field = _TOKEN_ORDER[i][0], name = _TOKEN_ORDER[i][1];
    var v = b[field];
    if (!(typeof v === 'string' && v)) v = preset[name];
    if (typeof v === 'string' && _TOKEN_SAFE.test(v)) out += '--a2ui-' + name + ':' + v + ';';
  }}
  return out;
}}
'''


def main():
    d, order = load()
    outs = {PY_OUT: render_py(d, order), GS_OUT: render_gs(d, order)}
    if "--check" in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in outs.items()
                 if not p.exists() or p.read_text() != t]
        if stale:
            print("stale (run scripts/gen_design_tokens.py):", *stale, sep="\n  ")
            return 1
        return 0
    for p, t in outs.items():
        p.write_text(t)
        print("wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
