"""GENERATED by scripts/gen_design_tokens.py from atoms/design-tokens.yaml -- do not edit; change the YAML and re-run."""
import re

TOKEN_ORDER = [["radius", "radius"], ["radius_sm", "radius-sm"], ["border_color", "border"], ["border_soft_color", "border-soft"], ["surface_color", "surface"], ["surface_muted_color", "surface-muted"], ["text_color", "text"], ["muted_color", "muted"], ["faint_color", "faint"], ["shadow", "shadow"]]
TOKEN_PRESETS = {
    "modern": {
        "radius": "12px",
        "radius-sm": "6px",
        "border": "#eaeaea",
        "border-soft": "#f1f1f1",
        "surface": "#ffffff",
        "surface-muted": "#fafafa",
        "text": "#171717",
        "muted": "#666666",
        "faint": "#8f8f8f",
        "shadow": "0 1px 2px rgba(0,0,0,.04),0 4px 12px rgba(0,0,0,.04)"
    }
}
_SAFE = re.compile(r"[#A-Za-z0-9_ .,()%/-]{1,120}")


def token_css(b):
    """`--a2ui-<name>:<value>;` for every token the palette block sets, in
    declared order. Explicit fields beat the preset; unsafe values are dropped."""
    key = b.get("preset")
    preset = TOKEN_PRESETS.get(key, {}) if isinstance(key, str) else {}
    out = ""
    for field, name in TOKEN_ORDER:
        v = b.get(field)
        if not (isinstance(v, str) and v):
            v = preset.get(name)
        if isinstance(v, str) and _SAFE.fullmatch(v):
            out += "--a2ui-" + name + ":" + v + ";"
    return out
